Repository OCA/wms, pull requests merged in 2020-08, with the labels that each got.

#40 Make stock_storage_type depend on stock_putaway_hook
  stock_storage_type/__manifest__.py
  stock_storage_type/models/stock_location.py
Labels: approved, bot is merging ⏳, ready to merge

#43 Add printed flag on all released transfers
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: approved, bot is merging ⏳, ready to merge

#41 [13.0] Create module delivery_carrier_warehouse
  delivery_carrier_warehouse/__init__.py
  delivery_carrier_warehouse/__manifest__.py
  delivery_carrier_warehouse/models/__init__.py
  delivery_carrier_warehouse/models/sale_order.py
  delivery_carrier_warehouse/models/stock_warehouse.py
  delivery_carrier_warehouse/readme/CONTRIBUTORS.rst
  delivery_carrier_warehouse/readme/DESCRIPTION.rst
  delivery_carrier_warehouse/tests/__init__.py
  delivery_carrier_warehouse/tests/test_delivery_carrier_warehouse.py
  delivery_carrier_warehouse/views/stock_warehouse.xml
  setup/delivery_carrier_warehouse/odoo/addons/delivery_carrier_warehouse
  setup/delivery_carrier_warehouse/setup.py
Labels: bot is merging ⏳

#39 [13.0] stock_storage_type: Add package storage type on product
  stock_storage_type/__manifest__.py
  stock_storage_type/models/__init__.py
  stock_storage_type/models/product_template.py
  stock_storage_type/models/stock_quant_package.py
  stock_storage_type/views/product_template.xml
Labels: approved, bot is merging ⏳

#14 [13.0][MIG] stock_storage_type_putaway_abc
  setup/stock_storage_type_putaway_abc/odoo/addons/stock_storage_type_putaway_abc
  setup/stock_storage_type_putaway_abc/setup.py
  stock_storage_type_putaway_abc/__init__.py
  stock_storage_type_putaway_abc/__manifest__.py
  stock_storage_type_putaway_abc/models/__init__.py
  stock_storage_type_putaway_abc/models/product_template.py
  stock_storage_type_putaway_abc/models/stock_location.py
  stock_storage_type_putaway_abc/readme/CONTRIBUTORS.rst
  stock_storage_type_putaway_abc/readme/DESCRIPTION.rst
  stock_storage_type_putaway_abc/tests/__init__.py
  stock_storage_type_putaway_abc/tests/test_abc_location.py
  stock_storage_type_putaway_abc/views/product.xml
  stock_storage_type_putaway_abc/views/stock_location.xml
Labels: bot is merging ⏳

#38 [13.0] Rename module to delivery_carrier_preference
  delivery_carrier_preference/README.rst
  delivery_carrier_preference/__init__.py
  delivery_carrier_preference/__manifest__.py
  delivery_carrier_preference/models/__init__.py
  delivery_carrier_preference/models/delivery_carrier_preference.py
  delivery_carrier_preference/models/procurement_group.py
  delivery_carrier_preference/models/stock_location_route.py
  delivery_carrier_preference/models/stock_move.py
  delivery_carrier_preference/models/stock_picking.py
  delivery_carrier_preference/readme/CONFIGURE.rst
  delivery_carrier_preference/readme/CONTRIBUTORS.rst
  delivery_carrier_preference/readme/DESCRIPTION.rst
  delivery_carrier_preference/security/ir.model.access.csv
  delivery_carrier_preference/static/description/icon.png
  delivery_carrier_preference/static/description/index.html
  delivery_carrier_preference/tests/__init__.py
  delivery_carrier_preference/tests/test_delivery_carrier_preference.py
  delivery_carrier_preference/views/delivery_carrier_preference.xml
  delivery_carrier_preference/views/stock_location_route.xml
  delivery_carrier_preference/views/stock_move.xml
  delivery_carrier_preference/views/stock_picking.xml
  oca_dependencies.txt
  sale_delivery_carrier_preference/__manifest__.py
  sale_delivery_carrier_preference/i18n/sale_delivery_carrier_preference.pot
  sale_delivery_carrier_preference/models/__init__.py
  sale_delivery_carrier_preference/models/sale_order.py
  sale_delivery_carrier_preference/readme/CONFIGURE.rst
  sale_delivery_carrier_preference/readme/DESCRIPTION.rst
  sale_delivery_carrier_preference/readme/ROADMAP.rst
  sale_delivery_carrier_preference/security/ir.model.access.csv
  sale_delivery_carrier_preference/tests/test_delivery_carrier_preference.py
  setup/delivery_carrier_preference/odoo/addons/delivery_carrier_preference
  setup/delivery_carrier_preference/setup.py
  setup/sale_delivery_carrier_preference/odoo/addons/sale_delivery_carrier_preference
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: bot is merging ⏳
