Repository OCA/wms, pull requests merged in 2020-07, with the labels that each got.

#32 [13.0] sale_delivery_carrier_preference
  sale_delivery_carrier_preference/__init__.py
  sale_delivery_carrier_preference/__manifest__.py
  sale_delivery_carrier_preference/models/__init__.py
  sale_delivery_carrier_preference/models/delivery_carrier_preference.py
  sale_delivery_carrier_preference/models/sale_order.py
  sale_delivery_carrier_preference/readme/CONFIGURE.rst
  sale_delivery_carrier_preference/readme/CONTRIBUTORS.rst
  sale_delivery_carrier_preference/readme/DESCRIPTION.rst
  sale_delivery_carrier_preference/readme/ROADMAP.rst
  sale_delivery_carrier_preference/security/ir.model.access.csv
  sale_delivery_carrier_preference/tests/__init__.py
  sale_delivery_carrier_preference/tests/test_delivery_carrier_preference.py
  sale_delivery_carrier_preference/views/delivery_carrier_preference.xml
  setup/sale_delivery_carrier_preference/odoo/addons/sale_delivery_carrier_preference
  setup/sale_delivery_carrier_preference/setup.py
Labels: approved, bot is merging ⏳, needs review

#35 [13.0] Ignore unavailable carriers in preferences
  sale_delivery_carrier_preference/models/delivery_carrier_preference.py
Labels: bot is merging ⏳

#33 [13.0] Allow to select locations with 'none' strategy in putaway sequence
  stock_storage_type/models/stock_location.py
  stock_storage_type/models/stock_package_level.py
  stock_storage_type/models/stock_quant.py
  stock_storage_type/models/stock_storage_location_sequence.py
  stock_storage_type/readme/CONFIGURATION.rst
  stock_storage_type/readme/CONTRIBUTORS.rst
  stock_storage_type/tests/common.py
  stock_storage_type/tests/test_storage_type_move.py
  stock_storage_type/tests/test_storage_type_putaway_strategy.py
  stock_storage_type/views/stock_package_level.xml
  stock_storage_type/views/stock_storage_location_sequence.xml
Labels: approved, bot is merging ⏳

#27 [13.0] Add compatibility module for stock_picking_type_shipping_policy and...
  setup/stock_picking_type_shipping_policy_group_by/odoo/addons/stock_picking_type_shipping_policy_group_by
  setup/stock_picking_type_shipping_policy_group_by/setup.py
  stock_picking_type_shipping_policy/models/stock_move.py
  stock_picking_type_shipping_policy_group_by/__init__.py
  stock_picking_type_shipping_policy_group_by/__manifest__.py
  stock_picking_type_shipping_policy_group_by/models/__init__.py
  stock_picking_type_shipping_policy_group_by/models/stock_move.py
  stock_picking_type_shipping_policy_group_by/readme/CONTRIBUTORS.rst
  stock_picking_type_shipping_policy_group_by/readme/DESCRIPTION.rst
  stock_picking_type_shipping_policy_group_by/static/description/icon.png
  stock_picking_type_shipping_policy_group_by/tests/__init__.py
  stock_picking_type_shipping_policy_group_by/tests/test_stock_picking_type_shipping_policy.py
Labels: approved, bot is merging ⏳

#28 [13.0] Add stock_move_source_relocate
  setup/stock_move_source_relocate/odoo/addons/stock_move_source_relocate
  setup/stock_move_source_relocate/setup.py
  setup/stock_move_source_relocate_dynamic_routing/odoo/addons/stock_move_source_relocate_dynamic_routing
  setup/stock_move_source_relocate_dynamic_routing/setup.py
  stock_move_source_relocate/__init__.py
  stock_move_source_relocate/__manifest__.py
  stock_move_source_relocate/models/__init__.py
  stock_move_source_relocate/models/stock_location.py
  stock_move_source_relocate/models/stock_move.py
  stock_move_source_relocate/models/stock_source_relocate.py
  stock_move_source_relocate/readme/CONFIGURE.rst
  stock_move_source_relocate/readme/CONTRIBUTORS.rst
  stock_move_source_relocate/readme/DESCRIPTION.rst
  stock_move_source_relocate/security/ir.model.access.csv
  stock_move_source_relocate/tests/__init__.py
  stock_move_source_relocate/tests/test_source_relocate.py
  stock_move_source_relocate/views/stock_source_relocate_views.xml
  stock_move_source_relocate_dynamic_routing/__init__.py
  stock_move_source_relocate_dynamic_routing/__manifest__.py
  stock_move_source_relocate_dynamic_routing/models/__init__.py
  stock_move_source_relocate_dynamic_routing/models/stock_move.py
  stock_move_source_relocate_dynamic_routing/models/stock_routing.py
  stock_move_source_relocate_dynamic_routing/models/stock_source_relocate.py
  stock_move_source_relocate_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_move_source_relocate_dynamic_routing/readme/DESCRIPTION.rst
  stock_move_source_relocate_dynamic_routing/tests/__init__.py
  stock_move_source_relocate_dynamic_routing/tests/test_dynamic_relocate.py
  stock_move_source_relocate_dynamic_routing/views/stock_routing_views.xml
  stock_move_source_relocate_dynamic_routing/views/stock_source_relocate_views.xml
Labels: bot is merging ⏳

#30 [13.0] Add backorder link when partial quantities are released
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/readme/CONFIGURE.rst
  stock_available_to_promise_release/tests/test_reservation.py
Labels: bot is merging ⏳

#36 Add shipping line on sale order confirmation
  sale_delivery_carrier_preference/models/sale_order.py
Labels: approved, bot is merging ⏳
