Repository OCA/wms, pull requests merged in 2020-10, with the labels that each got.

#49 Ensure compatibility between release and dynamic routing
  setup/stock_available_to_promise_release_dynamic_routing/odoo/addons/stock_available_to_promise_release_dynamic_routing
  setup/stock_available_to_promise_release_dynamic_routing/setup.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release_dynamic_routing/__init__.py
  stock_available_to_promise_release_dynamic_routing/__manifest__.py
  stock_available_to_promise_release_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release_dynamic_routing/readme/DESCRIPTION.rst
  stock_available_to_promise_release_dynamic_routing/tests/__init__.py
  stock_available_to_promise_release_dynamic_routing/tests/test_release_dynamic_routing.py
  stock_dynamic_routing/models/stock_routing_rule.py
Labels: approved, bot is merging ⏳

#57 Fix manager access on stock storage types
  stock_storage_type/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, needs review

#51 [13.0] stock_storage_type & stock_storage_type_putaway_abc: handle max_height
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/__init__.py
  stock_storage_type/tests/test_stock_location.py
  stock_storage_type/tests/test_storage_type.py
  stock_storage_type_putaway_abc/models/stock_location.py
  stock_storage_type_putaway_abc/tests/test_abc_location.py
Labels: approved, bot is merging ⏳, ready to merge

#56 [13.0] Add picking_domain field on carrier pref. view
  delivery_carrier_preference/models/delivery_carrier_preference.py
  delivery_carrier_preference/views/delivery_carrier_preference.xml
Labels: approved, bot is merging ⏳
