Repository OCA/wms, pull requests merged in 2020-12, with the labels that each got.

#82 [13.0] shopfloor: add menu/service options
  shopfloor/__manifest__.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/checkout.py
  shopfloor/services/service.py
  shopfloor/tests/test_checkout_no_package.py
  shopfloor/tests/test_checkout_select_line.py
  shopfloor/tests/test_checkout_select_package_base.py
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: approved, bot is merging ⏳

#86 [13.0][FIX] stock_reception_screen: create package on step validation
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/tests/test_reception_screen.py
Labels: approved, bot is merging ⏳

#81 [13.0] stock_available_to_promise_release: fix previous qty compute
  .travis.yml
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: approved, bot is merging ⏳, ready to merge

#93 Prevent "need_release" to be copied on duplicate of stock.move
  stock_available_to_promise_release/models/stock_move.py
Labels: bot is merging ⏳

#98 13.0 Change license of stock_available_to_promise_release to LGPL-3
  sale_stock_available_to_promise_release/README.rst
  sale_stock_available_to_promise_release/__manifest__.py
  sale_stock_available_to_promise_release/models/procurement_group.py
  sale_stock_available_to_promise_release/models/sale_order.py
  sale_stock_available_to_promise_release/models/sale_order_line.py
  sale_stock_available_to_promise_release/models/stock_move.py
  sale_stock_available_to_promise_release/models/stock_picking.py
  sale_stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/models/product_product.py
  stock_available_to_promise_release/models/res_config_settings.py
  stock_available_to_promise_release/models/stock_location_route.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/models/stock_picking_type.py
  stock_available_to_promise_release/models/stock_rule.py
  stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/wizards/stock_release.py
Labels: bot is merging ⏳

#85 Fix error when location has no leaf locations
  stock_storage_type/models/stock_location.py
Labels: approved, bot is merging ⏳

#91 Fix error when a picking has no move lines
  stock_available_to_promise_release/models/stock_picking.py
Labels: approved, bot is merging ⏳

#102 stock_storage_type: fix warning non writeable field
  stock_storage_type/models/stock_quant_package.py
Labels: bot is merging ⏳

#100 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  .travis.yml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/shopfloor/odoo/addons/shopfloor
  setup/shopfloor/setup.py
  setup/shopfloor_batch_automatic_creation/odoo/addons/shopfloor_batch_automatic_creation
  setup/shopfloor_batch_automatic_creation/setup.py
  shopfloor/__manifest__.py
  shopfloor_batch_automatic_creation/__manifest__.py
  stock_reception_screen/__manifest__.py
  test-requirements.txt
Labels: help wanted, needs review
