Repository OCA/wms, pull requests merged in 2020-11, with the labels that each got.

#59 [IMP] stock_available_to_promise_release: handle the priority
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/views/stock_move_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#53 [13.0] Fix unpredictable package storage type on packages
  stock_storage_type/models/stock_quant_package.py
Labels: approved, bot is merging ⏳

#15 [13.0][MIG] stock_reception_screen
  setup/stock_reception_screen/odoo/addons/stock_reception_screen
  setup/stock_reception_screen/setup.py
  stock_reception_screen/README.rst
  stock_reception_screen/__init__.py
  stock_reception_screen/__manifest__.py
  stock_reception_screen/models/__init__.py
  stock_reception_screen/models/manual_barcode.py
  stock_reception_screen/models/product_packaging.py
  stock_reception_screen/models/stock_move.py
  stock_reception_screen/models/stock_move_line.py
  stock_reception_screen/models/stock_picking.py
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/readme/CONTRIBUTORS.rst
  stock_reception_screen/readme/DESCRIPTION.rst
  stock_reception_screen/security/ir.model.access.csv
  stock_reception_screen/static/description/index.html
  stock_reception_screen/static/src/js/autofocus.js
  stock_reception_screen/static/src/scss/screen.scss
  stock_reception_screen/tests/__init__.py
  stock_reception_screen/tests/test_reception_screen.py
  stock_reception_screen/views/assets.xml
  stock_reception_screen/views/manual_barcode.xml
  stock_reception_screen/views/stock_move_line.xml
  stock_reception_screen/views/stock_picking.xml
  stock_reception_screen/views/stock_reception_screen.xml
Labels: bot is merging ⏳

#65 [FIX] shopfloor, zone picking: do not ask the user to choose among lines
  shopfloor/services/zone_picking.py
Labels: approved, bot is merging ⏳

#60 [13.0][FIX] shopfloor, zone picking: ability to unload partial moves
  shopfloor/models/stock_move.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_start.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
Labels: approved, bot is merging ⏳

#47 [13.0] Search ordered available to promise
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/views/stock_move_views.xml
Labels: bot is merging ⏳

#67 [13.0] Improve performance of available to promise computation
  delivery_carrier_preference/models/stock_move.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/views/stock_move_views.xml
Labels: approved, bot is merging ⏳

#68 [FIX] shopfloor, zone picking: do not process line processed by someone else
  shopfloor/actions/message.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: bot is merging ⏳

#72 shopfloor: api docs fix api_key_demo not found
  shopfloor/services/service.py
Labels: bot is merging ⏳

#74 Shopfloor: misc fixes for zone_picking
  shopfloor/services/zone_picking.py
  shopfloor_mobile/static/wms/src/components/batch_picking_detail.js
  shopfloor_mobile/static/wms/src/components/list.js
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: approved, bot is merging ⏳

#61 [IMP] stock_reception_screen: scan several packages for the same product/lot
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/tests/test_reception_screen.py
  stock_reception_screen/views/stock_reception_screen.xml
Labels: approved, bot is merging ⏳, ready to merge

#70 [13.0][FIX] stock_reception_screen: able to cancel a receipt
  stock_reception_screen/models/stock_picking.py
Labels: approved, bot is merging ⏳

#75 Shopfloor: fix sorting of lines by scheduled date
  shopfloor/services/cluster_picking.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_cluster_picking_select.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: approved, bot is merging ⏳

#77 shopfloor: fix zone_picking._scan_source_location
  shopfloor/__manifest__.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/common.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: approved, bot is merging ⏳

#73 [13.0] stock_available_to_promise: Rework release screens
  sale_stock_available_to_promise_release/__manifest__.py
  sale_stock_available_to_promise_release/models/__init__.py
  sale_stock_available_to_promise_release/models/sale_order.py
  sale_stock_available_to_promise_release/models/stock_picking.py
  sale_stock_available_to_promise_release/views/product_product_views.xml
  sale_stock_available_to_promise_release/views/sale_order_views.xml
  sale_stock_available_to_promise_release/views/stock_picking_views.xml
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/models/__init__.py
  stock_available_to_promise_release/models/product_product.py
  stock_available_to_promise_release/models/res_company.py
  stock_available_to_promise_release/models/res_config_settings.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/models/stock_picking_type.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/views/product_product_views.xml
  stock_available_to_promise_release/views/res_config_settings.xml
  stock_available_to_promise_release/views/stock_move_views.xml
  stock_available_to_promise_release/views/stock_picking_type_views.xml
  stock_available_to_promise_release/views/stock_picking_views.xml
  stock_available_to_promise_release/wizards/__init__.py
  stock_available_to_promise_release/wizards/stock_move_release.py
  stock_available_to_promise_release/wizards/stock_release.py
  stock_available_to_promise_release/wizards/stock_release_views.xml
Labels: approved, bot is merging ⏳

#80 [13.0] shopfloor misc improvements
  shopfloor/__manifest__.py
  shopfloor/actions/__init__.py
  shopfloor/actions/move_line_search.py
  shopfloor/actions/search.py
  shopfloor/models/shopfloor_log.py
  shopfloor/services/menu.py
  shopfloor/services/schema.py
  shopfloor/services/service.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_db_logging.py
  shopfloor/tests/test_menu.py
  shopfloor/tests/test_menu_base.py
  shopfloor/tests/test_menu_counters.py
  shopfloor/tests/test_user.py
  shopfloor/tests/test_zone_picking_start.py
  shopfloor_mobile/__manifest__.py
  shopfloor_mobile/static/wms/src/components/list.js
  shopfloor_mobile/static/wms/src/components/manual_select.js
  shopfloor_mobile/static/wms/src/components/misc.js
  shopfloor_mobile/static/wms/src/components/screen.js
  shopfloor_mobile/static/wms/src/demo/demo.core.js
  shopfloor_mobile/static/wms/src/demo/demo.zone_picking.js
  shopfloor_mobile/static/wms/src/homepage.js
  shopfloor_mobile/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile/static/wms/src/lib/vuetify/vuetify.js
  shopfloor_mobile/static/wms/src/lib/vuetify/vuetify.min.css
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
  shopfloor_mobile/templates/assets.xml
Labels: approved, bot is merging ⏳, needs review
