Repository OCA/wms, pull requests merged in 2021-09, with the labels that each got.

#185 [MIG] delivery_carrier_preference: Migration to 14.0
  .pre-commit-config.yaml
  delivery_carrier_preference/README.rst
  delivery_carrier_preference/__manifest__.py
  delivery_carrier_preference/i18n/es_AR.po
  delivery_carrier_preference/readme/CONTRIBUTORS.rst
  delivery_carrier_preference/readme/CREDITS.rst
  delivery_carrier_preference/static/description/index.html
  setup/delivery_carrier_preference/odoo/addons/delivery_carrier_preference
  setup/delivery_carrier_preference/setup.py
Labels: bot is merging ⏳

#286 [13.0][FIX] shopfloor, single pack transfer fix
  shopfloor/models/priority_postpone_mixin.py
  shopfloor/services/single_pack_transfer.py
Labels: bug, approved, bot is merging ⏳

#281 [14.0][MIG] stock_dynamic_routing_reserve_rule
  setup/stock_dynamic_routing_reserve_rule/odoo/addons/stock_dynamic_routing_reserve_rule
  setup/stock_dynamic_routing_reserve_rule/setup.py
  stock_dynamic_routing/views/stock_routing_views.xml
  stock_dynamic_routing_reserve_rule/README.rst
  stock_dynamic_routing_reserve_rule/__init__.py
  stock_dynamic_routing_reserve_rule/__manifest__.py
  stock_dynamic_routing_reserve_rule/i18n/es_AR.po
  stock_dynamic_routing_reserve_rule/models/__init__.py
  stock_dynamic_routing_reserve_rule/models/stock_routing.py
  stock_dynamic_routing_reserve_rule/readme/DESCRIPTION.rst
  stock_dynamic_routing_reserve_rule/static/description/icon.png
  stock_dynamic_routing_reserve_rule/static/description/index.html
  stock_dynamic_routing_reserve_rule/templates/stock_routing_templates.xml
  stock_dynamic_routing_reserve_rule/views/stock_routing_views.xml
  stock_move_source_relocate_dynamic_routing/models/stock_routing.py
Labels: migration, needs review, approved, bot is merging ⏳

#279 [14.0][MIG] shopfloor_packing_info
  setup/shopfloor_packing_info/odoo/addons/shopfloor_packing_info
  setup/shopfloor_packing_info/setup.py
  shopfloor_packing_info/README.rst
  shopfloor_packing_info/__init__.py
  shopfloor_packing_info/__manifest__.py
  shopfloor_packing_info/demo/shopfloor_packing_info_demo.xml
  shopfloor_packing_info/i18n/es_AR.po
  shopfloor_packing_info/models/__init__.py
  shopfloor_packing_info/models/res_partner.py
  shopfloor_packing_info/models/shopfloor_packing_info.py
  shopfloor_packing_info/models/stock_picking.py
  shopfloor_packing_info/models/stock_picking_type.py
  shopfloor_packing_info/readme/CONTRIBUTORS.rst
  shopfloor_packing_info/readme/DESCRIPTION.rst
  shopfloor_packing_info/security/ir.model.access.csv
  shopfloor_packing_info/services/__init__.py
  shopfloor_packing_info/services/checkout.py
  shopfloor_packing_info/static/description/icon.png
  shopfloor_packing_info/static/description/index.html
  shopfloor_packing_info/tests/__init__.py
  shopfloor_packing_info/tests/test_checkout_scan_line.py
  shopfloor_packing_info/tests/test_shopfloor_packing_info.py
  shopfloor_packing_info/views/menus.xml
  shopfloor_packing_info/views/res_partner_views.xml
  shopfloor_packing_info/views/shopfloor_packing_info_views.xml
  shopfloor_packing_info/views/stock_picking_type_views.xml
  shopfloor_packing_info/views/stock_picking_views.xml
Labels: migration, needs review, bot is merging ⏳

#288 [14.0][MIG] stock_storage_type_putaway_abc: Migration to 14.0
  .pre-commit-config.yaml
  setup/stock_storage_type_putaway_abc/odoo/addons/stock_storage_type_putaway_abc
  setup/stock_storage_type_putaway_abc/setup.py
  stock_storage_type_putaway_abc/__manifest__.py
  stock_storage_type_putaway_abc/models/stock_location.py
Labels: migration, needs review, approved, bot is merging ⏳

#291 [MIG] stock_move_source_relocate_dynamic_routing: Migration to 14.0
  .pre-commit-config.yaml
  setup/stock_move_source_relocate_dynamic_routing/odoo/addons/stock_move_source_relocate_dynamic_routing
  setup/stock_move_source_relocate_dynamic_routing/setup.py
  stock_available_to_promise_release_dynamic_routing/README.rst
  stock_available_to_promise_release_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release_dynamic_routing/readme/CREDITS.rst
  stock_available_to_promise_release_dynamic_routing/static/description/index.html
  stock_move_source_relocate_dynamic_routing/__manifest__.py
  stock_move_source_relocate_dynamic_routing/i18n/es_AR.po
Labels: approved, bot is merging ⏳

#293 [14.0][MIG] stock_checkout_sync
  setup/stock_checkout_sync/odoo/addons/stock_checkout_sync
  setup/stock_checkout_sync/setup.py
  stock_checkout_sync/README.rst
  stock_checkout_sync/__init__.py
  stock_checkout_sync/__manifest__.py
  stock_checkout_sync/i18n/es_AR.po
  stock_checkout_sync/i18n/stock_checkout_sync.pot
  stock_checkout_sync/models/__init__.py
  stock_checkout_sync/models/stock_move.py
  stock_checkout_sync/models/stock_picking.py
  stock_checkout_sync/models/stock_picking_type.py
  stock_checkout_sync/readme/CONFIGURE.rst
  stock_checkout_sync/readme/CONTRIBUTORS.rst
  stock_checkout_sync/readme/CREDITS.rst
  stock_checkout_sync/readme/DESCRIPTION.rst
  stock_checkout_sync/security/ir.model.access.csv
  stock_checkout_sync/static/description/icon.png
  stock_checkout_sync/static/description/index.html
  stock_checkout_sync/static/description/sync-assistant.png
  stock_checkout_sync/tests/__init__.py
  stock_checkout_sync/tests/common.py
  stock_checkout_sync/tests/test_checkout_sync.py
  stock_checkout_sync/views/stock_picking_type_views.xml
  stock_checkout_sync/views/stock_picking_views.xml
  stock_checkout_sync/wizards/__init__.py
  stock_checkout_sync/wizards/stock_move_checkout_sync.py
  stock_checkout_sync/wizards/stock_move_checkout_sync_views.xml
Labels: migration, approved, bot is merging ⏳

#296 [FIX] s_a_to_promise_release: compatibility with 'stock_picking_batch'
  stock_available_to_promise_release/views/stock_picking_views.xml
Labels: bug, approved, bot is merging ⏳

#297 [14.0][MIG] stock_available_to_promise_release_dynamic_routing: Migrate to 14.0
  .pre-commit-config.yaml
  setup/stock_available_to_promise_release_dynamic_routing/odoo/addons/stock_available_to_promise_release_dynamic_routing
  setup/stock_available_to_promise_release_dynamic_routing/setup.py
  stock_available_to_promise_release_dynamic_routing/README.rst
  stock_available_to_promise_release_dynamic_routing/__manifest__.py
  stock_available_to_promise_release_dynamic_routing/i18n/es_AR.po
  stock_available_to_promise_release_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release_dynamic_routing/static/description/index.html
Labels: approved, bot is merging ⏳

#294 [14.0][MIG] shopfloor_checkout_sync
  .pre-commit-config.yaml
  setup/shopfloor_checkout_sync/odoo/addons/shopfloor_checkout_sync
  setup/shopfloor_checkout_sync/setup.py
  shopfloor_checkout_sync/README.rst
  shopfloor_checkout_sync/__manifest__.py
  shopfloor_checkout_sync/readme/CONTRIBUTORS.rst
  shopfloor_checkout_sync/readme/CREDITS.rst
  shopfloor_checkout_sync/static/description/index.html
  shopfloor_checkout_sync/tests/test_shopfloor_zone_picking_sync.py
Labels: migration, bot is merging ⏳
