Repository OCA/wms, pull requests merged in 2021-08, with the labels that each got.

#251 [14.0][MIG] shopfloor_mobile
  .eslintrc.yml
  .pre-commit-config.yaml
  setup/shopfloor_mobile/odoo/addons/shopfloor_mobile
  setup/shopfloor_mobile/setup.py
  shopfloor_mobile/__manifest__.py
  shopfloor_mobile/static/wms/src/components/detail/detail_lot.js
  shopfloor_mobile/static/wms/src/components/detail/detail_product.js
  shopfloor_mobile/static/wms/src/components/detail/detail_transfer.js
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.js
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/mixins.js
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_select.js
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_summary.js
  shopfloor_mobile/static/wms/src/css/main.css
  shopfloor_mobile/static/wms/src/demo/demo.checkout.js
  shopfloor_mobile/static/wms/src/demo/demo.delivery.js
  shopfloor_mobile/static/wms/src/demo/demo.location_content_transfer.js
  shopfloor_mobile/static/wms/src/demo/demo.zone_picking.js
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/scenario/cluster_picking.js
  shopfloor_mobile/static/wms/src/scenario/delivery.js
  shopfloor_mobile/static/wms/src/scenario/location_content_transfer.js
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
  shopfloor_mobile/static/wms/src/wms_utils.js
Labels: bot is merging ⏳

#167 [MIG] delivery_carrier_warehouse: Migration to 14.0
  .pre-commit-config.yaml
  delivery_carrier_warehouse/README.rst
  delivery_carrier_warehouse/__manifest__.py
  delivery_carrier_warehouse/readme/CONTRIBUTORS.rst
  delivery_carrier_warehouse/readme/CREDITS.rst
  delivery_carrier_warehouse/static/description/index.html
  delivery_carrier_warehouse/views/stock_warehouse.xml
  setup/delivery_carrier_warehouse/odoo/addons/delivery_carrier_warehouse
  setup/delivery_carrier_warehouse/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#245 [ADD] shopfloor_delivery_shipment
  setup/shopfloor_delivery_shipment/odoo/addons/shopfloor_delivery_shipment
  setup/shopfloor_delivery_shipment/setup.py
  shopfloor/actions/data.py
  shopfloor/actions/schema.py
  shopfloor/models/stock_picking.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_delivery_shipment/README.rst
  shopfloor_delivery_shipment/__init__.py
  shopfloor_delivery_shipment/__manifest__.py
  shopfloor_delivery_shipment/actions/__init__.py
  shopfloor_delivery_shipment/actions/data.py
  shopfloor_delivery_shipment/actions/message.py
  shopfloor_delivery_shipment/actions/schema.py
  shopfloor_delivery_shipment/actions/search.py
  shopfloor_delivery_shipment/data/shopfloor_scenario_data.xml
  shopfloor_delivery_shipment/demo/shopfloor_menu_demo.xml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.plantuml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.png
  shopfloor_delivery_shipment/docs/oca_logo.png
  shopfloor_delivery_shipment/models/__init__.py
  shopfloor_delivery_shipment/models/shopfloor_menu.py
  shopfloor_delivery_shipment/readme/CONTRIBUTORS.rst
  shopfloor_delivery_shipment/readme/CREDITS.rst
  shopfloor_delivery_shipment/readme/DESCRIPTION.rst
  shopfloor_delivery_shipment/services/__init__.py
  shopfloor_delivery_shipment/services/delivery_shipment.py
  shopfloor_delivery_shipment/static/description/index.html
  shopfloor_delivery_shipment/tests/__init__.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_base.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_loading_list.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_dock.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_lot.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_package.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_picking.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_product.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_unload.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_validate.py
  shopfloor_delivery_shipment/views/shopfloor_menu.xml
Labels: approved, bot is merging ⏳, ready to merge

#249 [13.0][FIX] s_r_screen: subcontracting fix with components tracked by lot
  stock_reception_screen_mrp_subcontracting/models/__init__.py
  stock_reception_screen_mrp_subcontracting/models/stock_move.py
  stock_reception_screen_mrp_subcontracting/tests/test_reception_screen.py
Labels: approved, bot is merging ⏳, ready to merge

#258 [13.0->14.0][oca-port-pr-#58] Add stock_storage_type_buffer
  setup/stock_storage_type_buffer/odoo/addons/stock_storage_type_buffer
  setup/stock_storage_type_buffer/setup.py
  stock_storage_type/models/stock_location.py
  stock_storage_type_buffer/__init__.py
  stock_storage_type_buffer/__manifest__.py
  stock_storage_type_buffer/models/__init__.py
  stock_storage_type_buffer/models/stock_location.py
  stock_storage_type_buffer/models/stock_location_storage_buffer.py
  stock_storage_type_buffer/readme/CONTRIBUTORS.rst
  stock_storage_type_buffer/readme/DESCRIPTION.rst
  stock_storage_type_buffer/security/ir.model.access.csv
  stock_storage_type_buffer/templates/stock_location_storage_buffer_templates.xml
  stock_storage_type_buffer/tests/__init__.py
  stock_storage_type_buffer/tests/test_storage_type_buffer.py
  stock_storage_type_buffer/views/stock_location_storage_buffer_views.xml
Labels: bot is merging ⏳, migration

#259 [13.0->14.0][oca-port-pr-#135] Add barcode on Package Storage Type, use it at reception screen
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/tests/test_reception_screen.py
  stock_reception_screen/views/stock_reception_screen.xml
  stock_storage_type/models/stock_package_storage_type.py
  stock_storage_type/views/stock_package_storage_type.xml
Labels: approved, bot is merging ⏳

#262 [13.0->14.0][oca-port-pr-#188] s_storage_type: no storage type for delivery
  stock_storage_type/models/stock_quant_package.py
  stock_storage_type/tests/__init__.py
  stock_storage_type/tests/test_auto_assign_storage_type.py
Labels: approved, bot is merging ⏳

#261 [13.0->14.0][oca-port-pr-#127] Shopfloor: use estimated package weight if weight is not set
  stock_storage_type/models/stock_location.py
  stock_storage_type/models/stock_quant.py
Labels: approved, bot is merging ⏳

#243 13.0: s_s_available_to_promise_release: fixes
  sale_stock_available_to_promise_release/i18n/ca.po
  sale_stock_available_to_promise_release/i18n/de.po
  sale_stock_available_to_promise_release/i18n/es_AR.po
  sale_stock_available_to_promise_release/i18n/fr.po
  sale_stock_available_to_promise_release/i18n/it.po
  sale_stock_available_to_promise_release/i18n/sale_stock_available_to_promise_release.pot
  sale_stock_available_to_promise_release/models/sale_order_line.py
  sale_stock_available_to_promise_release/reports/sale_order.xml
  sale_stock_available_to_promise_release/tests/test_sale_line_availability_status.py
  sale_stock_available_to_promise_release/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#264 [13.0->14.0][oca-port-pr-#164] stock_storage_type: optimize stored compute fields on stock.location
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/test_stock_location.py
  stock_storage_type_buffer/models/stock_location.py
  stock_storage_type_buffer/tests/test_storage_type_buffer.py
Labels: approved, bot is merging ⏳

#242 13.0: Add sale_stock_available_to_promise_release_cutoff
  sale_stock_available_to_promise_release_cutoff/README.rst
  sale_stock_available_to_promise_release_cutoff/__init__.py
  sale_stock_available_to_promise_release_cutoff/__manifest__.py
  sale_stock_available_to_promise_release_cutoff/models/__init__.py
  sale_stock_available_to_promise_release_cutoff/models/sale_order.py
  sale_stock_available_to_promise_release_cutoff/models/sale_order_line.py
  sale_stock_available_to_promise_release_cutoff/readme/CONTRIBUTORS.rst
  sale_stock_available_to_promise_release_cutoff/readme/DESCRIPTION.rst
  sale_stock_available_to_promise_release_cutoff/static/description/index.html
Labels: ready to merge, needs fixing, approved, bot is merging ⏳

#268 [13.0->14.0][oca-port-pr-#171] stock_storage_type: putaway strategy "do not mix" should give priorit…
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/test_storage_type_putaway_strategy.py
Labels: bot is merging ⏳

#263 [13.0->14.0][oca-port-pr-#195] stock_storage_type: allow to archive storage types/locations
  stock_storage_type/models/stock_location_storage_type.py
  stock_storage_type/models/stock_package_storage_type.py
  stock_storage_type/tests/test_storage_type.py
  stock_storage_type/views/stock_location_storage_type.xml
  stock_storage_type/views/stock_package_storage_type.xml
Labels: approved, bot is merging ⏳

#181 [MIG] stock_picking_type_shipping_policy_group_by: Migration to 14.0
  .pre-commit-config.yaml
  setup/stock_picking_type_shipping_policy_group_by/odoo/addons/stock_picking_type_shipping_policy_group_by
  setup/stock_picking_type_shipping_policy_group_by/setup.py
  stock_picking_type_shipping_policy_group_by/README.rst
  stock_picking_type_shipping_policy_group_by/__manifest__.py
  stock_picking_type_shipping_policy_group_by/i18n/es_AR.po
  stock_picking_type_shipping_policy_group_by/readme/CONTRIBUTORS.rst
  stock_picking_type_shipping_policy_group_by/readme/CREDITS.rst
  stock_picking_type_shipping_policy_group_by/static/description/index.html
  stock_picking_type_shipping_policy_group_by/tests/__init__.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#272 [14.0] shopfloor_mobile: un-delete sf_m/.../misc.js
  shopfloor_mobile/static/wms/src/components/misc.js
Labels: bot is merging ⏳

#271 [14.0][FW] shopfloor_workstation: multiple ports from 13.0
  .pre-commit-config.yaml
  .travis.yml
  setup/shopfloor_workstation/odoo/addons/shopfloor_workstation
  setup/shopfloor_workstation/setup.py
  shopfloor_batch_automatic_creation/services/cluster_picking.py
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
  shopfloor_batch_automatic_creation/views/shopfloor_menu_views.xml
  shopfloor_checkout_sync/__manifest__.py
  shopfloor_checkout_sync/services/cluster_picking.py
  shopfloor_checkout_sync/services/location_content_transfer.py
  shopfloor_checkout_sync/services/zone_picking.py
  shopfloor_workstation/__init__.py
  shopfloor_workstation/__manifest__.py
  shopfloor_workstation/demo/shopfloor_workstation_demo.xml
  shopfloor_workstation/models/__init__.py
  shopfloor_workstation/models/shopfloor_workstation.py
  shopfloor_workstation/readme/CONFIGURE.rst
  shopfloor_workstation/readme/CONTRIBUTORS.rst
  shopfloor_workstation/readme/DESCRIPTION.rst
  shopfloor_workstation/security/ir.model.access.csv
  shopfloor_workstation/services/__init__.py
  shopfloor_workstation/services/workstation.py
  shopfloor_workstation/tests/__init__.py
  shopfloor_workstation/tests/test_shopfloor_workstation.py
  shopfloor_workstation/views/shopfloor_workstation.xml
Labels: needs review

#267 [14.0][MIG] stock_dynamic_routing
  .pre-commit-config.yaml
  stock_dynamic_routing/__manifest__.py
  stock_dynamic_routing/models/stock_location.py
  stock_dynamic_routing/models/stock_move.py
  stock_dynamic_routing/tests/test_routing_pull.py
  stock_dynamic_routing/tests/test_routing_push.py
Labels: migration, approved, bot is merging ⏳

#270 [14.0][FW] stock_available_to_promise_release: multiple ports from 13.0
  sale_stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: needs review, bot is merging ⏳

#280 [13.0] Fix Package storage type message computation.
  stock_storage_type/models/stock_location.py
Labels: approved, bot is merging ⏳

#269 [14.0][FW] [13.0] Change sorting of locations in the pack putaway computation
  stock_storage_type/README.rst
  stock_storage_type/__manifest__.py
  stock_storage_type/demo/stock_location.xml
  stock_storage_type/models/stock_location.py
  stock_storage_type/readme/CONTRIBUTORS.rst
  stock_storage_type/readme/DESCRIPTION.rst
  stock_storage_type/tests/common.py
  stock_storage_type/tests/test_stock_location.py
  stock_storage_type/tests/test_storage_type.py
  stock_storage_type/views/stock_location.xml
  stock_storage_type_buffer/tests/test_storage_type_buffer.py
  stock_storage_type_putaway_abc/README.rst
  stock_storage_type_putaway_abc/__manifest__.py
  stock_storage_type_putaway_abc/models/stock_location.py
  stock_storage_type_putaway_abc/readme/CONTRIBUTORS.rst
  stock_storage_type_putaway_abc/readme/DESCRIPTION.rst
  stock_storage_type_putaway_abc/tests/test_abc_location.py
Labels: ready to merge, needs review, approved, bot is merging ⏳

#282 [13.0] stock_storage_type: add location smart buttons
  stock_storage_type/models/stock_location_storage_type.py
  stock_storage_type/models/stock_storage_location_sequence.py
  stock_storage_type/views/stock_location_storage_type.xml
  stock_storage_type/views/stock_storage_location_sequence.xml
Labels: approved, bot is merging ⏳

#283 [13.0] stock_storage_type: Fix putaway compution when a strategy is defined
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/test_storage_type.py
  stock_storage_type/tests/test_storage_type_putaway_strategy.py
Labels: approved, bot is merging ⏳
