Repository OCA/wms, pull requests merged in 2021-02, with the labels that each got.

#144 [13.0] shopfloor_mobile: Add setting page improvements
  shopfloor_mobile/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile/static/wms/src/main.js
  shopfloor_mobile/static/wms/src/settings/language.js
  shopfloor_mobile/static/wms/src/settings/profile.js
  shopfloor_mobile/static/wms/src/settings/settings.js
Labels: approved, bot is merging ⏳, ready to merge

#107 [13.0] stock_reception_screen: open from move line
  stock_reception_screen/models/stock_move_line.py
  stock_reception_screen/views/stock_move_line.xml
Labels: approved, bot is merging ⏳, ready to merge

#155 shopfloor: fix picking edit carrier form
  shopfloor_mobile/static/wms/src/components/detail/detail_transfer.js
  shopfloor_mobile/static/wms/src/scenario/form.js
Labels: bot is merging ⏳

#157 shopfloor: Improve package and product details
  shopfloor/actions/data_detail.py
  shopfloor/services/schema_detail.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor/tests/test_scan_anything.py
  shopfloor_mobile/static/wms/src/components/detail/detail_package.js
  shopfloor_mobile/static/wms/src/components/detail/detail_product.js
Labels: approved, bot is merging ⏳, ready to merge

#156 shopfloor: use db logging from rest_log
  shopfloor/__manifest__.py
  shopfloor/data/ir_config_parameter_data.xml
  shopfloor/data/ir_cron_data.xml
  shopfloor/models/shopfloor_log.py
  shopfloor/security/ir.model.access.csv
  shopfloor/services/service.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_db_logging.py
  shopfloor/views/menus.xml
  shopfloor/views/shopfloor_log_views.xml
Labels: approved, ready to merge

#154 [13.0][IMP] stock_reception_screen: minor improvements
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/tests/test_reception_screen.py
  stock_reception_screen/views/stock_reception_screen.xml
Labels: approved, bot is merging ⏳

#164 [13.0] stock_storage_type: optimize stored compute fields on stock.location
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/test_stock_location.py
  stock_storage_type_buffer/models/stock_location.py
  stock_storage_type_buffer/tests/test_storage_type_buffer.py
Labels: approved, bot is merging ⏳

#173 [13.0] Add shopfloor_workstation + sync w/ OCA/oca-addons-repo-template
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  oca_dependencies.txt
  requirements.txt
  sale_stock_available_to_promise_release/__manifest__.py
  setup/shopfloor_workstation/odoo/addons/shopfloor_workstation
  setup/shopfloor_workstation/setup.py
  shopfloor_mobile/static/wms/src/components/screen.js
  shopfloor_mobile/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile/static/wms/src/i18n/i18n.fr.js
  shopfloor_mobile/static/wms/src/main.js
  shopfloor_mobile/static/wms/src/router.js
  shopfloor_mobile/static/wms/src/settings/settings.js
  shopfloor_mobile/static/wms/src/settings/workstation.js
  shopfloor_workstation/__init__.py
  shopfloor_workstation/__manifest__.py
  shopfloor_workstation/demo/shopfloor_workstation_demo.xml
  shopfloor_workstation/models/__init__.py
  shopfloor_workstation/models/shopfloor_workstation.py
  shopfloor_workstation/readme/CONFIGURE.rst
  shopfloor_workstation/readme/CONTRIBUTORS.rst
  shopfloor_workstation/readme/DESCRIPTION.rst
  shopfloor_workstation/security/ir.model.access.csv
  shopfloor_workstation/services/__init__.py
  shopfloor_workstation/services/workstation.py
  shopfloor_workstation/tests/__init__.py
  shopfloor_workstation/tests/test_shopfloor_workstation.py
  shopfloor_workstation/views/shopfloor_workstation.xml
  stock_available_to_promise_release/__manifest__.py
  stock_move_source_relocate_dynamic_routing/__manifest__.py
  stock_reception_screen/__manifest__.py
Labels: bot is merging ⏳

#159 [13.0] stock_reception_screen exec picking action_done
  stock_reception_screen/models/stock_reception_screen.py
Labels: approved, bot is merging ⏳

#162 [13.0][FIX] shopfloor: handle better lines priority
  shopfloor/models/priority_postpone_mixin.py
  shopfloor/services/cluster_picking.py
  shopfloor/services/location_content_transfer.py
  shopfloor/tests/test_cluster_picking_skip.py
  shopfloor/tests/test_location_content_transfer_single.py
Labels: approved, bot is merging ⏳, ready to merge, work in progress

#170 [13.0] Shopfloor checkout: display carrier and validate packaging against it
  shopfloor/__manifest__.py
  shopfloor/actions/data.py
  shopfloor/actions/data_detail.py
  shopfloor/actions/message.py
  shopfloor/services/checkout.py
  shopfloor/services/schema.py
  shopfloor/services/schema_detail.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor/tests/test_checkout_list_package.py
  shopfloor/tests/test_checkout_scan_package_action.py
  shopfloor_mobile/static/wms/src/components/detail/detail_card.js
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: bot is merging ⏳

#174 [13.0] stock_available_to_promise_release: Fix release of operation containing canceled moves
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: approved, bot is merging ⏳, ready to merge

#165 [13.0] Use stock_helper to replace duplicated implementation
  shopfloor/__manifest__.py
  shopfloor/models/stock_location.py
  stock_dynamic_routing/__manifest__.py
  stock_dynamic_routing/models/stock_location.py
  stock_move_source_relocate/__manifest__.py
  stock_move_source_relocate/models/__init__.py
  stock_move_source_relocate/models/stock_location.py
Labels: approved, bot is merging ⏳, ready to merge

#172 [13.0][IMP] Reception screen warning messages
  stock_reception_screen/__manifest__.py
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/views/stock_reception_screen.xml
Labels: approved, bot is merging ⏳
