Repository OCA/wms, pull requests merged in 2021-01, with the labels that each got.

#108 [14.0][PORT] 98 from 13.0
  sale_stock_available_to_promise_release/README.rst
  sale_stock_available_to_promise_release/__manifest__.py
  sale_stock_available_to_promise_release/models/procurement_group.py
  sale_stock_available_to_promise_release/models/sale_order.py
  sale_stock_available_to_promise_release/models/sale_order_line.py
  sale_stock_available_to_promise_release/models/stock_move.py
  sale_stock_available_to_promise_release/models/stock_picking.py
  sale_stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/models/product_product.py
  stock_available_to_promise_release/models/res_config_settings.py
  stock_available_to_promise_release/models/stock_location_route.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/models/stock_picking_type.py
  stock_available_to_promise_release/models/stock_rule.py
  stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/wizards/stock_release.py
Labels: bot is merging ⏳

#109 [14.0][PORT] 85 from 13.0
  stock_storage_type/models/stock_location.py
Labels: bot is merging ⏳

#110 [14.0][PORT] 91 from 13.0
  stock_available_to_promise_release/models/stock_picking.py
Labels: bot is merging ⏳

#105 [13.0] Shopfloor: fix zone picking wide screen mode
  shopfloor_mobile/__manifest__.py
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: bot is merging ⏳, bug

#58 [13.0] Add stock_storage_type_buffer
  setup/stock_storage_type_buffer/odoo/addons/stock_storage_type_buffer
  setup/stock_storage_type_buffer/setup.py
  stock_storage_type/models/stock_location.py
  stock_storage_type_buffer/__init__.py
  stock_storage_type_buffer/__manifest__.py
  stock_storage_type_buffer/models/__init__.py
  stock_storage_type_buffer/models/stock_location.py
  stock_storage_type_buffer/models/stock_location_storage_buffer.py
  stock_storage_type_buffer/readme/CONTRIBUTORS.rst
  stock_storage_type_buffer/readme/DESCRIPTION.rst
  stock_storage_type_buffer/security/ir.model.access.csv
  stock_storage_type_buffer/templates/stock_location_storage_buffer_templates.xml
  stock_storage_type_buffer/tests/__init__.py
  stock_storage_type_buffer/tests/test_storage_type_buffer.py
  stock_storage_type_buffer/views/stock_location_storage_buffer_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#104 [FIX] shopfloor: cluster picking, remove unavailable picking from validated batch
  shopfloor/services/cluster_picking.py
  shopfloor/tests/test_cluster_picking_unload.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: bot is merging ⏳

#88 [FIX] stock_reception_screen: forbid view locations
  stock_reception_screen/views/stock_reception_screen.xml
Labels: bot is merging ⏳

#84 [FIX] shopfloor, checkout: ability to recover/restart
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_scan.py
Labels: approved, bot is merging ⏳, ready to merge

#94 [13.0][FIX] 'Release ready' based on the shipping policy of the order
  sale_stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
Labels: approved, bot is merging ⏳, ready to merge

#114 [FIX] shopfloor_mobile, delivery, rename button 'Mark as done' to 'Make partial delivery'
  shopfloor_mobile/static/wms/src/scenario/delivery.js
Labels: approved, bot is merging ⏳

#99 [13.0] shopfloor: fix zone picking scan source
  shopfloor/actions/message.py
  shopfloor/services/service.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: approved, bot is merging ⏳

#122 [14.0][FIX]stock_move_source_relocate_dynamic_routing fix __manifest__
  stock_move_source_relocate_dynamic_routing/__manifest__.py
Labels: bot is merging ⏳

#113 [IMP] shopfloor: create backorder when validating moves
  shopfloor/actions/__init__.py
  shopfloor/actions/stock.py
  shopfloor/models/stock_move.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_stock_split.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
Labels: approved, bot is merging ⏳, ready to merge

#120 [13.0] Shopfloor: misc improvements
  shopfloor/services/app.py
  shopfloor/services/user.py
  shopfloor/tests/test_app.py
  shopfloor/tests/test_user.py
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_select.js
  shopfloor_mobile/static/wms/src/components/screen.js
  shopfloor_mobile/static/wms/src/components/searchbar/searchbar.js
  shopfloor_mobile/static/wms/src/main.js
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/settings/settings.js
Labels: approved, bot is merging ⏳

#116 [13.0] stock_available_to_promise_release: Change test case helper methods as classmethod
  stock_available_to_promise_release/tests/common.py
Labels: approved, bot is merging ⏳

#106 stock_available_to_promise_release: Fix quantity available to promise of released moves
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, ready to merge

#62 [DOC] shopfloor: delivery + zone_picking sequence diagrams
  shopfloor/docs/delivery_diag_seq.png
  shopfloor/docs/delivery_diag_seq.txt
  shopfloor/docs/oca_logo.png
  shopfloor/docs/zone_picking_diag_seq.png
  shopfloor/docs/zone_picking_diag_seq.txt
  shopfloor/services/delivery.py
  shopfloor/services/zone_picking.py
Labels: bot is merging ⏳

#130 shopfloor_batch_automatic_creation: Reactivate failing test
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
Labels: bot is merging ⏳

#133 [13.0] shopfloor: adaptations for new base_rest API
  shopfloor/services/service.py
  shopfloor/tests/common.py
  shopfloor/tests/test_db_logging.py
  shopfloor/tests/test_picking_form.py
Labels: bot is merging ⏳

#124 [14.0] fix missing url key in manifests
  sale_stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/__manifest__.py
Labels: bot is merging ⏳

#135 [13.0] Add barcode on Package Storage Type, use it at reception screen
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/tests/test_reception_screen.py
  stock_reception_screen/views/stock_reception_screen.xml
  stock_storage_type/models/stock_package_storage_type.py
  stock_storage_type/views/stock_package_storage_type.xml
Labels: approved, bot is merging ⏳

#126 [13.0] stock_available_to_promise_release: Fix horizon - count released move outside horizon
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: approved, bot is merging ⏳, ready to merge

#125 [13.0] shopfloor: refine model and views
  shopfloor/__manifest__.py
  shopfloor/demo/shopfloor_profile_demo.xml
  shopfloor/i18n/shopfloor.pot
  shopfloor/migrations/13.0.2.1.0/post-migration.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/models/shopfloor_profile.py
  shopfloor/services/menu.py
  shopfloor/services/profile.py
  shopfloor/services/service.py
  shopfloor/tests/test_app.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_cluster_picking_base.py
  shopfloor/tests/test_cluster_picking_batch.py
  shopfloor/tests/test_db_logging.py
  shopfloor/tests/test_delivery_base.py
  shopfloor/tests/test_location_content_transfer_base.py
  shopfloor/tests/test_menu.py
  shopfloor/tests/test_picking_form.py
  shopfloor/tests/test_profile.py
  shopfloor/tests/test_single_pack_transfer_base.py
  shopfloor/tests/test_user.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor/views/shopfloor_profile_views.xml
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
  shopfloor_mobile/static/wms/src/demo/demo.core.js
Labels: approved, bot is merging ⏳, ready to merge

#115 [13.0] Add stock_checkout_sync
  setup/stock_checkout_sync/odoo/addons/stock_checkout_sync
  setup/stock_checkout_sync/setup.py
  setup/stock_dynamic_routing_checkout_sync/odoo/addons/stock_dynamic_routing_checkout_sync
  setup/stock_dynamic_routing_checkout_sync/setup.py
  stock_checkout_sync/__init__.py
  stock_checkout_sync/__manifest__.py
  stock_checkout_sync/models/__init__.py
  stock_checkout_sync/models/stock_move.py
  stock_checkout_sync/models/stock_picking.py
  stock_checkout_sync/models/stock_picking_type.py
  stock_checkout_sync/readme/CONFIGURE.rst
  stock_checkout_sync/readme/CONTRIBUTORS.rst
  stock_checkout_sync/readme/DESCRIPTION.rst
  stock_checkout_sync/static/description/sync-assistant.png
  stock_checkout_sync/tests/__init__.py
  stock_checkout_sync/tests/common.py
  stock_checkout_sync/tests/test_checkout_sync.py
  stock_checkout_sync/views/stock_picking_type_views.xml
  stock_checkout_sync/views/stock_picking_views.xml
  stock_checkout_sync/wizards/__init__.py
  stock_checkout_sync/wizards/stock_move_checkout_sync.py
  stock_checkout_sync/wizards/stock_move_checkout_sync_views.xml
  stock_dynamic_routing_checkout_sync/__init__.py
  stock_dynamic_routing_checkout_sync/__manifest__.py
  stock_dynamic_routing_checkout_sync/models/__init__.py
  stock_dynamic_routing_checkout_sync/readme/CONTRIBUTORS.rst
  stock_dynamic_routing_checkout_sync/readme/DESCRIPTION.rst
  stock_dynamic_routing_checkout_sync/tests/__init__.py
  stock_dynamic_routing_checkout_sync/tests/test_routing_sync.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, ready to merge

#138 [13.0][FIX] shopfloor: do not create operation if destination is invalid
  shopfloor/actions/message.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_location_content_transfer_putaway.py
  shopfloor/tests/test_single_pack_transfer_putaway.py
Labels: approved, bot is merging ⏳

#131 [13.0] Add plantuml diagram for single pack transfer
  shopfloor/docs/delivery_diag_seq.plantuml
  shopfloor/docs/single_pack_transfer_diag_seq.plantuml
  shopfloor/docs/single_pack_transfer_diag_seq.png
  shopfloor/docs/zone_picking_diag_seq.plantuml
  shopfloor/services/delivery.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/services/zone_picking.py
Labels: approved, bot is merging ⏳, ready to merge

#139 [14.0][PORT] 133 from 13.0
  shopfloor/services/service.py
  shopfloor/tests/common.py
  shopfloor/tests/test_db_logging.py
  shopfloor/tests/test_picking_form.py
Labels: bot is merging ⏳

#146 [13.0] shopfloor: add PlantUML diagram for cluster picking
  shopfloor/docs/cluster_picking_diag_seq.plantuml
  shopfloor/docs/cluster_picking_diag_seq.png
  shopfloor/services/cluster_picking.py
Labels: bot is merging ⏳

#112 [13.0] Ensure moves routed from different location are reserved before other
  stock_dynamic_routing/models/stock_move.py
  stock_dynamic_routing/tests/test_routing_pull.py
Labels: approved, bot is merging ⏳, ready to merge

#140 [14.0][PORT] 113 from 13.0
  shopfloor/actions/__init__.py
  shopfloor/actions/stock.py
  shopfloor/models/stock_move.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_stock_split.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
Labels: bot is merging ⏳

#132 [13.0] stock_storage_type: Optimize "will contain" computed fields on stock.location
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/common.py
  stock_storage_type/tests/test_stock_location.py
Labels: approved, bot is merging ⏳, ready to merge

#117 [13.0] Shopfloor: zone picking refactor shared vars handling
  shopfloor/__manifest__.py
  shopfloor/actions/data.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_location_content_transfer_mix.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_change_pack_lot.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor/tests/test_zone_picking_select_picking_type.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
  shopfloor/tests/test_zone_picking_stock_issue.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
  shopfloor/tests/test_zone_picking_unload_single.py
  shopfloor/tests/test_zone_picking_zero_check.py
  shopfloor_checkout_sync/tests/test_shopfloor_zone_picking_sync.py
  shopfloor_mobile/__manifest__.py
  shopfloor_mobile/static/wms/src/scenario/mixins.js
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
  shopfloor_mobile/static/wms/src/services/odoo.js
Labels: approved, ready to merge

#151 Shopfloor zone picking unload from all zones
  shopfloor/__manifest__.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_zone_picking_change_pack_lot.py
  shopfloor/tests/test_zone_picking_select_picking_type.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_buffer_lines.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
Labels: approved, bot is merging ⏳

#137 [13.0] Add validator handlers delegating to component validators
  shopfloor/__manifest__.py
  shopfloor/services/service.py
  shopfloor/services/validator.py
Labels: approved

#148 [13.0][FIX] shopfloor: handle backorders
  shopfloor/__manifest__.py
  shopfloor/actions/stock.py
  shopfloor/services/location_content_transfer.py
  shopfloor/tests/test_location_content_transfer_set_destination_all.py
Labels: approved

#127 [13.0] Shopfloor: use estimated package weight if weight is not set
  shopfloor/__manifest__.py
  shopfloor/actions/data.py
  shopfloor/models/stock_quant_package.py
  shopfloor/services/checkout.py
  shopfloor/services/cluster_picking.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor/tests/test_checkout_list_package.py
  stock_storage_type/models/stock_location.py
  stock_storage_type/models/stock_quant.py
Labels: approved, bot is merging ⏳
