Repository OCA/wms, pull requests merged in 2021-06, with the labels that each got.

#231 Add easy pack change in zone picking (shopfloor)
  shopfloor/actions/message.py
  shopfloor/docs/zone_picking_diag_seq.plantuml
  shopfloor/docs/zone_picking_diag_seq.png
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: approved, bot is merging ⏳

#226 [13.0] Shopfloor: Improve check valid destination + align checks in all scenario
  shopfloor/README.rst
  shopfloor/readme/CONTRIBUTORS.rst
  shopfloor/services/checkout.py
  shopfloor/services/cluster_picking.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/service.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_cluster_picking_unload.py
  shopfloor/tests/test_location_content_transfer_set_destination_all.py
  shopfloor/tests/test_location_content_transfer_set_destination_package_or_line.py
  shopfloor/tests/test_single_pack_transfer.py
  shopfloor/tests/test_single_pack_transfer_putaway.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
Labels: approved, bot is merging ⏳

#221 sf_mobile_base: show current running env
  shopfloor_mobile_base/controllers/main.py
  shopfloor_mobile_base/readme/USAGE.rst
  shopfloor_mobile_base/static/wms/src/components/misc.js
  shopfloor_mobile_base/static/wms/src/components/screen.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile_base/static/wms/src/loginpage.js
  shopfloor_mobile_base/static/wms/src/settings/settings.js
  shopfloor_mobile_base/templates/main.xml
Labels: bot is merging ⏳

#222 sf_rest_log: filter by collection, go beta
  shopfloor_rest_log/__manifest__.py
  shopfloor_rest_log/migrations/13.0.1.1.0/pre-migration.py
  shopfloor_rest_log/views/menus.xml
Labels: bot is merging ⏳

#224 s_reception_screen_measuring_device: fix device release
  stock_reception_screen_measuring_device/models/stock_reception_screen.py
  stock_reception_screen_measuring_device/views/stock_reception_screen_view.xml
Labels: approved, bot is merging ⏳

#227 [13.0] shopfloor: fix wrong message for zone_picking.set_destination
  shopfloor/services/zone_picking.py
Labels: approved, bot is merging ⏳

#235 [13.0] shopfloor_mobile: misc fixes for qty display
  shopfloor_mobile/static/wms/src/components/detail/detail_transfer.js
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.js
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_select.js
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_summary.js
  shopfloor_mobile/static/wms/src/demo/demo.checkout.js
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/wms_utils.js
  shopfloor_mobile_base/static/wms/src/demo/demo.core.js
Labels: bot is merging ⏳

#228 [13.0][ADD] s_r_screen_mrp_subcontracting: compatibility layer
  setup/stock_reception_screen_mrp_subcontracting/odoo/addons/stock_reception_screen_mrp_subcontracting
  setup/stock_reception_screen_mrp_subcontracting/setup.py
  stock_reception_screen/models/stock_reception_screen.py
  stock_reception_screen/tests/common.py
  stock_reception_screen/tests/test_reception_screen.py
  stock_reception_screen_mrp_subcontracting/__init__.py
  stock_reception_screen_mrp_subcontracting/__manifest__.py
  stock_reception_screen_mrp_subcontracting/models/__init__.py
  stock_reception_screen_mrp_subcontracting/models/stock_move_line.py
  stock_reception_screen_mrp_subcontracting/models/stock_reception_screen.py
  stock_reception_screen_mrp_subcontracting/readme/CONTRIBUTORS.rst
  stock_reception_screen_mrp_subcontracting/readme/DESCRIPTION.rst
  stock_reception_screen_mrp_subcontracting/tests/__init__.py
  stock_reception_screen_mrp_subcontracting/tests/test_reception_screen.py
  stock_reception_screen_mrp_subcontracting/wizards/__init__.py
  stock_reception_screen_mrp_subcontracting/wizards/mrp_product_produce.py
Labels: approved, bot is merging ⏳, ready to merge

#237 [13.0] Change sorting of locations in the pack putaway computation
  stock_storage_type/README.rst
  stock_storage_type/__manifest__.py
  stock_storage_type/demo/stock_location.xml
  stock_storage_type/models/stock_location.py
  stock_storage_type/readme/CONTRIBUTORS.rst
  stock_storage_type/readme/DESCRIPTION.rst
  stock_storage_type/tests/common.py
  stock_storage_type/tests/test_stock_location.py
  stock_storage_type/tests/test_storage_type.py
  stock_storage_type/views/stock_location.xml
  stock_storage_type_buffer/tests/test_storage_type_buffer.py
  stock_storage_type_putaway_abc/README.rst
  stock_storage_type_putaway_abc/__manifest__.py
  stock_storage_type_putaway_abc/models/stock_location.py
  stock_storage_type_putaway_abc/readme/CONTRIBUTORS.rst
  stock_storage_type_putaway_abc/readme/DESCRIPTION.rst
  stock_storage_type_putaway_abc/tests/test_abc_location.py
Labels: approved, bot is merging ⏳

#233 Add stock_reception_screen_qty_by_packaging
  setup/stock_reception_screen_qty_by_packaging/odoo/addons/stock_reception_screen_qty_by_packaging
  setup/stock_reception_screen_qty_by_packaging/setup.py
  stock_reception_screen_qty_by_packaging/README.rst
  stock_reception_screen_qty_by_packaging/__init__.py
  stock_reception_screen_qty_by_packaging/__manifest__.py
  stock_reception_screen_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_reception_screen_qty_by_packaging/readme/DESCRIPTION.rst
  stock_reception_screen_qty_by_packaging/views/stock_reception_screen.xml
Labels: approved, bot is merging ⏳

#240 13.0 Fix failing branch in stock-logistics-warehouse for stock_vertical_lift_storage_type
  stock_storage_type/models/stock_location.py
Labels: bot is merging ⏳
