Repository OCA/wms, pull requests merged in 2021-07, with the labels that each got.

#119 [14.0][MIG] stock_picking_consolidation_priority
  setup/stock_picking_consolidation_priority/odoo/addons/stock_picking_consolidation_priority
  setup/stock_picking_consolidation_priority/setup.py
  stock_picking_consolidation_priority/README.rst
  stock_picking_consolidation_priority/__init__.py
  stock_picking_consolidation_priority/__manifest__.py
  stock_picking_consolidation_priority/i18n/stock_picking_consolidation_priority.pot
  stock_picking_consolidation_priority/models/__init__.py
  stock_picking_consolidation_priority/models/stock_move.py
  stock_picking_consolidation_priority/models/stock_picking_type.py
  stock_picking_consolidation_priority/readme/CONFIGURATION.rst
  stock_picking_consolidation_priority/readme/CONTRIBUTORS.rst
  stock_picking_consolidation_priority/readme/DESCRIPTION.rst
  stock_picking_consolidation_priority/readme/ROADMAP.rst
  stock_picking_consolidation_priority/static/description/icon.png
  stock_picking_consolidation_priority/static/description/index.html
  stock_picking_consolidation_priority/tests/__init__.py
  stock_picking_consolidation_priority/tests/test_consolidation_priority.py
  stock_picking_consolidation_priority/views/stock_picking_type.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#123 [14.0][MIG] stock_storage_type
  .pre-commit-config.yaml
  setup/stock_storage_type/odoo/addons/stock_storage_type
  setup/stock_storage_type/setup.py
  stock_storage_type/__manifest__.py
  stock_storage_type/demo/product_packaging.xml
  stock_storage_type/models/stock_location.py
  stock_storage_type/models/stock_location_storage_type.py
  stock_storage_type/models/stock_quant.py
  stock_storage_type/models/stock_quant_package.py
  stock_storage_type/readme/CONTRIBUTORS.rst
  stock_storage_type/readme/ROADMAP.rst
  stock_storage_type/tests/test_storage_type_move.py
  stock_storage_type/tests/test_storage_type_putaway_strategy.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#238 [FIX] shopfloor: single pack transfer, handle backorders
  shopfloor/actions/stock.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/tests/test_single_pack_transfer.py
Labels: approved, bot is merging ⏳

#247 [14.0][MIG] shopfloor
  .pre-commit-config.yaml
  oca_dependencies.txt
  setup/shopfloor/odoo/addons/shopfloor
  setup/shopfloor/setup.py
  shopfloor/__manifest__.py
  shopfloor/actions/data_detail.py
  shopfloor/actions/move_line_search.py
  shopfloor/actions/packaging.py
  shopfloor/actions/stock.py
  shopfloor/components/scan_handler_location.py
  shopfloor/components/scan_handler_lot.py
  shopfloor/components/scan_handler_package.py
  shopfloor/components/scan_handler_product.py
  shopfloor/components/scan_handler_transfer.py
  shopfloor/migrations/13.0.1.1.0/pre-migration.py
  shopfloor/models/stock_move.py
  shopfloor/models/stock_quant_package.py
  shopfloor/readme/CONTRIBUTORS.rst
  shopfloor/services/checkout.py
  shopfloor/services/cluster_picking.py
  shopfloor/services/delivery.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/models.py
  shopfloor/tests/test_actions_change_package_lot.py
  shopfloor/tests/test_actions_data_base.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor/tests/test_checkout_change_packaging.py
  shopfloor/tests/test_checkout_scan.py
  shopfloor/tests/test_checkout_scan_package_action.py
  shopfloor/tests/test_checkout_select.py
  shopfloor/tests/test_checkout_select_package_base.py
  shopfloor/tests/test_checkout_set_qty.py
  shopfloor/tests/test_cluster_picking_batch.py
  shopfloor/tests/test_cluster_picking_select.py
  shopfloor/tests/test_cluster_picking_unload.py
  shopfloor/tests/test_delivery_scan_deliver.py
  shopfloor/tests/test_location_content_transfer_mix.py
  shopfloor/tests/test_location_content_transfer_set_destination_package_or_line.py
  shopfloor/tests/test_menu_base.py
  shopfloor/tests/test_menu_counters.py
  shopfloor/tests/test_single_pack_transfer.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor/tests/test_zone_picking_select_picking_type.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
  shopfloor/tests/test_zone_picking_set_line_destination_pick_pack.py
  shopfloor/tests/test_zone_picking_stock_issue.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_buffer_lines.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
  shopfloor/tests/test_zone_picking_unload_single.py
  shopfloor/tests/test_zone_picking_zero_check.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, ready to merge

#253 [13.0->14.0][oca-port-pr-#125] shopfloor: refine model and views
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
Labels: bot is merging ⏳

#255 [13.0->14.0][oca-port-pr-#130] shopfloor_batch_automatic_creation: Reactivate failing test
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
Labels: bot is merging ⏳

#203 [13.0] shopfloor_example: Fix validators
  shopfloor_example/actions/schema_detail.py
  shopfloor_example/services/partner_service.py
Labels: bot is merging ⏳

#256 [13.0->14.0][oca-port-pr-#206] shopfloor_batch_automatic_creation: take first picking at least
  shopfloor_batch_automatic_creation/actions/picking_batch_auto_create.py
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
Labels: bot is merging ⏳

#257 [13.0->14.0][oca-port-pr-#211] shopfloor_batch_automatic_creation: group by commercial entity
  shopfloor_batch_automatic_creation/actions/picking_batch_auto_create.py
  shopfloor_batch_automatic_creation/models/shopfloor_menu.py
  shopfloor_batch_automatic_creation/readme/DESCRIPTION.rst
  shopfloor_batch_automatic_creation/services/cluster_picking.py
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
  shopfloor_batch_automatic_creation/views/shopfloor_menu_views.xml
Labels: bot is merging ⏳
