Repository OCA/wms, pull requests merged in 2021-12, with the labels that each got.

#333 [14.0] stock_dynamic_routing_reserve_rule: fix ir.qweb call
  stock_dynamic_routing_reserve_rule/models/stock_routing.py
Labels: needs review, approved, bot is merging ⏳

#304 [14.0][MIG] sale_stock_available_to_promise_release_cutoff: Migration to 14.0
  sale_stock_available_to_promise_release_cutoff/README.rst
  sale_stock_available_to_promise_release_cutoff/__init__.py
  sale_stock_available_to_promise_release_cutoff/__manifest__.py
  sale_stock_available_to_promise_release_cutoff/i18n/sale_stock_available_to_promise_release_cutoff.pot
  sale_stock_available_to_promise_release_cutoff/models/__init__.py
  sale_stock_available_to_promise_release_cutoff/models/sale_order.py
  sale_stock_available_to_promise_release_cutoff/models/sale_order_line.py
  sale_stock_available_to_promise_release_cutoff/readme/CONTRIBUTORS.rst
  sale_stock_available_to_promise_release_cutoff/readme/CREDITS.rst
  sale_stock_available_to_promise_release_cutoff/readme/DESCRIPTION.rst
  sale_stock_available_to_promise_release_cutoff/static/description/icon.png
  sale_stock_available_to_promise_release_cutoff/static/description/index.html
  setup/sale_stock_available_to_promise_release_cutoff/odoo/addons/sale_stock_available_to_promise_release_cutoff
  setup/sale_stock_available_to_promise_release_cutoff/setup.py
Labels: migration, needs review, approved, bot is merging ⏳

#335 [14.0][IMP] delivery_carrier_preference: Extract test setup in common class
  delivery_carrier_preference/tests/common.py
  delivery_carrier_preference/tests/test_delivery_carrier_preference.py
Labels: needs review, approved, bot is merging ⏳

#337 [14.0][MIG] shopfloor_manual_product_transfer(_mobile)
  setup/shopfloor_manual_product_transfer/odoo/addons/shopfloor_manual_product_transfer
  setup/shopfloor_manual_product_transfer/setup.py
  setup/shopfloor_manual_product_transfer_mobile/odoo/addons/shopfloor_manual_product_transfer_mobile
  setup/shopfloor_manual_product_transfer_mobile/setup.py
  shopfloor/actions/message.py
  shopfloor/actions/stock.py
  shopfloor/migrations/14.0.1.0.0/pre-migration.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/models/stock_location.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_manual_product_transfer/README.rst
  shopfloor_manual_product_transfer/__init__.py
  shopfloor_manual_product_transfer/__manifest__.py
  shopfloor_manual_product_transfer/actions/__init__.py
  shopfloor_manual_product_transfer/actions/message.py
  shopfloor_manual_product_transfer/data/shopfloor_scenario.xml
  shopfloor_manual_product_transfer/demo/shopfloor_menu.xml
  shopfloor_manual_product_transfer/demo/stock_picking_type.xml
  shopfloor_manual_product_transfer/docs/manual_product_transfer_diag_seq.plantuml
  shopfloor_manual_product_transfer/docs/manual_product_transfer_diag_seq.png
  shopfloor_manual_product_transfer/readme/CONTRIBUTORS.rst
  shopfloor_manual_product_transfer/readme/CREDITS.rst
  shopfloor_manual_product_transfer/readme/DESCRIPTION.rst
  shopfloor_manual_product_transfer/services/__init__.py
  shopfloor_manual_product_transfer/services/manual_product_transfer.py
  shopfloor_manual_product_transfer/static/description/index.html
  shopfloor_manual_product_transfer/tests/__init__.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_base.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_confirm_quantity.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_misc.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_scan_destination_location.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_scan_product.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_start.py
  shopfloor_manual_product_transfer_mobile/README.rst
  shopfloor_manual_product_transfer_mobile/__init__.py
  shopfloor_manual_product_transfer_mobile/__manifest__.py
  shopfloor_manual_product_transfer_mobile/readme/CONTRIBUTORS.rst
  shopfloor_manual_product_transfer_mobile/readme/DESCRIPTION.rst
  shopfloor_manual_product_transfer_mobile/static/description/index.html
  shopfloor_manual_product_transfer_mobile/static/wms/src/demo/demo.manual_product_transfer.js
  shopfloor_manual_product_transfer_mobile/static/wms/src/scenario/manual_product_transfer.js
  shopfloor_manual_product_transfer_mobile/templates/assets.xml
Labels: migration, approved, bot is merging ⏳

#341 [14.0][FIX] Fix reception_screen next pack button
  stock_reception_screen/models/stock_reception_screen.py
Labels: bug, ready to merge, approved, bot is merging ⏳

#344 d_carrier_preference: add estimated_shipping_weight to tree view
  delivery_carrier_preference/models/stock_move.py
  delivery_carrier_preference/views/stock_move.xml
Labels: approved, bot is merging ⏳

#342 [14.0][FIX] shopfloor_mobile: Display location as TODO as long as the artic…
  shopfloor_mobile/static/wms/src/components/batch_picking_line_detail.js
Labels: ready to merge, approved, bot is merging ⏳
