Repository OCA/wms, pull requests merged in 2021-05, with the labels that each got.

#225 [13.0][FIX] Shopfloor, loc. content transfer: put lines in separate transfer
  shopfloor/models/stock_move_line.py
  shopfloor/models/stock_picking.py
  shopfloor/services/location_content_transfer.py
  shopfloor/tests/test_location_content_transfer_mix.py
Labels: approved, bot is merging ⏳

#229 shopfloor: get rid of shopfloor.log
  shopfloor/__manifest__.py
  shopfloor/migrations/13.0.1.2.0/post-migration.py
  shopfloor/models/__init__.py
  shopfloor/models/shopfloor_log.py
  shopfloor/security/ir.model.access.csv
Labels: bot is merging ⏳

#118 [14.0][MIG] stock_picking_completion_info
  setup/stock_picking_completion_info/odoo/addons/stock_picking_completion_info
  setup/stock_picking_completion_info/setup.py
  stock_picking_completion_info/README.rst
  stock_picking_completion_info/__init__.py
  stock_picking_completion_info/__manifest__.py
  stock_picking_completion_info/i18n/stock_picking_completion_info.pot
  stock_picking_completion_info/models/__init__.py
  stock_picking_completion_info/models/stock_picking.py
  stock_picking_completion_info/readme/CONTRIBUTORS.rst
  stock_picking_completion_info/readme/DESCRIPTION.rst
  stock_picking_completion_info/static/description/icon.png
  stock_picking_completion_info/static/description/index.html
  stock_picking_completion_info/tests/__init__.py
  stock_picking_completion_info/tests/test_stock_picking_completion_info.py
  stock_picking_completion_info/views/stock_picking.xml
Labels: migration, needs review
