Repository OCA/wms, pull requests merged in 2021-11, with the labels that each got.

#320 [14.0][FW] shopfloor: multiple ports from 13.0
  shopfloor/actions/data.py
  shopfloor/actions/schema.py
  shopfloor/models/priority_postpone_mixin.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/scenario/cluster_picking.js
Labels: approved, bot is merging ⏳, port

#323 [14.0][FW] [13.0] shopfloor_mobile: misc fixes for qty display
  shopfloor_mobile_base/static/wms/src/demo/demo.core.js
Labels: bug, bot is merging ⏳, port

#321 [14.0][FW] shopfloor_mobile_base: detail card improvement
  shopfloor_mobile_base/static/wms/src/components/detail/detail_card.js
Labels: approved, bot is merging ⏳, port

#322 [14.0][FW] stock_storage_type: multiple ports from 13.0
  stock_storage_type/models/stock_location.py
  stock_storage_type/models/stock_location_storage_type.py
  stock_storage_type/models/stock_storage_location_sequence.py
  stock_storage_type/tests/test_storage_type.py
  stock_storage_type/tests/test_storage_type_putaway_strategy.py
  stock_storage_type/views/stock_location_storage_type.xml
  stock_storage_type/views/stock_storage_location_sequence.xml
Labels: bug, approved, bot is merging ⏳, port

#244 [13.0][ADD] sale_stock_available_to_promise_release_dropshipping
  sale_stock_available_to_promise_release_dropshipping/README.rst
  sale_stock_available_to_promise_release_dropshipping/__init__.py
  sale_stock_available_to_promise_release_dropshipping/__manifest__.py
  sale_stock_available_to_promise_release_dropshipping/models/__init__.py
  sale_stock_available_to_promise_release_dropshipping/models/sale_order_line.py
  sale_stock_available_to_promise_release_dropshipping/readme/CONTRIBUTORS.rst
  sale_stock_available_to_promise_release_dropshipping/readme/DESCRIPTION.rst
  sale_stock_available_to_promise_release_dropshipping/static/description/index.html
  setup/sale_stock_available_to_promise_release_dropshipping/odoo/addons/sale_stock_available_to_promise_release_dropshipping
  setup/sale_stock_available_to_promise_release_dropshipping/setup.py
  stock_reception_screen/static/src/js/autofocus.js
Labels: bot is merging ⏳

#315 [14.0] Shopfloor mobile base - refactor auth
  setup/shopfloor_mobile_base_auth_api_key/odoo/addons/shopfloor_mobile_base_auth_api_key
  setup/shopfloor_mobile_base_auth_api_key/setup.py
  setup/shopfloor_mobile_base_auth_user/odoo/addons/shopfloor_mobile_base_auth_user
  setup/shopfloor_mobile_base_auth_user/setup.py
  shopfloor_example/services/partner_service.py
  shopfloor_mobile/__manifest__.py
  shopfloor_mobile/migrations/14.0.1.1.0/post-migrate.py
  shopfloor_mobile_base/readme/CONTRIBUTORS.rst
  shopfloor_mobile_base/static/wms/src/components/screen.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile_base/static/wms/src/loginpage.js
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/static/wms/src/router.js
  shopfloor_mobile_base/static/wms/src/services/auth_handler_registry.js
  shopfloor_mobile_base_auth_api_key/README.rst
  shopfloor_mobile_base_auth_api_key/__init__.py
  shopfloor_mobile_base_auth_api_key/__manifest__.py
  shopfloor_mobile_base_auth_api_key/controllers/__init__.py
  shopfloor_mobile_base_auth_api_key/controllers/main.py
  shopfloor_mobile_base_auth_api_key/readme/CONTRIBUTORS.rst
  shopfloor_mobile_base_auth_api_key/readme/CREDITS.rst
  shopfloor_mobile_base_auth_api_key/readme/DESCRIPTION.rst
  shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
  shopfloor_mobile_base_auth_api_key/templates/assets.xml
  shopfloor_mobile_base_auth_user/README.rst
  shopfloor_mobile_base_auth_user/__init__.py
  shopfloor_mobile_base_auth_user/__manifest__.py
  shopfloor_mobile_base_auth_user/controllers/__init__.py
  shopfloor_mobile_base_auth_user/controllers/main.py
  shopfloor_mobile_base_auth_user/readme/CONTRIBUTORS.rst
  shopfloor_mobile_base_auth_user/readme/CREDITS.rst
  shopfloor_mobile_base_auth_user/readme/DESCRIPTION.rst
  shopfloor_mobile_base_auth_user/static/wms/src/login.js
  shopfloor_mobile_base_auth_user/templates/assets.xml
Labels: bot is merging ⏳

#232 [13.0] stock_dynamic_routing: fix compatibility with stock_move_source_relocate module
  stock_dynamic_routing/README.rst
  stock_dynamic_routing/models/stock_move.py
  stock_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_dynamic_routing/tests/test_routing_pull.py
  stock_move_source_relocate_dynamic_routing/tests/__init__.py
  stock_move_source_relocate_dynamic_routing/tests/test_dynamic_destination.py
Labels: ready to merge, approved, bot is merging ⏳

#325 [14.0][MIG] sale_stock_available_to_promise_release_dropshipping
  sale_stock_available_to_promise_release/tests/common.py
  sale_stock_available_to_promise_release/tests/test_sale_line_availability_status.py
  sale_stock_available_to_promise_release_dropshipping/README.rst
  sale_stock_available_to_promise_release_dropshipping/__init__.py
  sale_stock_available_to_promise_release_dropshipping/__manifest__.py
  sale_stock_available_to_promise_release_dropshipping/i18n/sale_stock_available_to_promise_release_dropshipping.pot
  sale_stock_available_to_promise_release_dropshipping/models/__init__.py
  sale_stock_available_to_promise_release_dropshipping/models/sale_order_line.py
  sale_stock_available_to_promise_release_dropshipping/readme/CONTRIBUTORS.rst
  sale_stock_available_to_promise_release_dropshipping/readme/DESCRIPTION.rst
  sale_stock_available_to_promise_release_dropshipping/static/description/icon.png
  sale_stock_available_to_promise_release_dropshipping/static/description/index.html
  sale_stock_available_to_promise_release_dropshipping/tests/__init__.py
  sale_stock_available_to_promise_release_dropshipping/tests/test_dropshipping.py
  setup/sale_stock_available_to_promise_release_dropshipping/odoo/addons/sale_stock_available_to_promise_release_dropshipping
  setup/sale_stock_available_to_promise_release_dropshipping/setup.py
Labels: migration, needs review, approved, bot is merging ⏳

#326 [14.0][FW] [13.0] stock_dynamic_routing: fix compatibility with stock_move_source_relocate module
  stock_dynamic_routing/README.rst
  stock_dynamic_routing/models/stock_move.py
  stock_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_dynamic_routing/tests/test_routing_pull.py
  stock_move_source_relocate_dynamic_routing/tests/__init__.py
  stock_move_source_relocate_dynamic_routing/tests/test_dynamic_destination.py
Labels: bug, approved, bot is merging ⏳, port

#324 [14.0] Shopfloor ui tests - first Cypress tests
  .gitignore
  shopfloor_example/__init__.py
  shopfloor_example/__manifest__.py
  shopfloor_example/hooks.py
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base_auth_user/static/wms/src/login.js
  shopfloor_ui_tests/README.rst
  shopfloor_ui_tests/cypress.json
  shopfloor_ui_tests/cypress/fixtures/app_config.json
  shopfloor_ui_tests/cypress/fixtures/credentials_apikey.json
  shopfloor_ui_tests/cypress/fixtures/credentials_user.json
  shopfloor_ui_tests/cypress/integration/shopfloor_example/test_example.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base/test_navigation.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base/test_profile.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base_auth_api_key/test_authentication_apikey.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base_auth_user/test_authentication_user.js
  shopfloor_ui_tests/cypress/plugins/index.js
  shopfloor_ui_tests/cypress/support/commands.js
  shopfloor_ui_tests/cypress/support/index.js
  shopfloor_ui_tests/package-lock.json
  shopfloor_ui_tests/package.json
Labels: ready to merge, approved, bot is merging ⏳

#327 [14.0] shopfloor: fix test_user
  shopfloor/tests/__init__.py
  shopfloor/tests/test_menu_base.py
  shopfloor/tests/test_user.py
Labels: bot is merging ⏳

#328 [13.0] shopfloor: fix test_user
  shopfloor/tests/__init__.py
  shopfloor/tests/test_menu_base.py
  shopfloor/tests/test_user.py
Labels: bot is merging ⏳

#329 [14.0] shopfloor_base + shopfloor_mobile_base: misc fix/imp
  shopfloor_base/services/menu.py
  shopfloor_base/services/profile.py
  shopfloor_base/services/service.py
  shopfloor_mobile_base/static/wms/src/components/screen.js
  shopfloor_mobile_base/static/wms/src/homepage.js
  shopfloor_mobile_base/static/wms/src/loginpage.js
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/static/wms/src/scenario/mixins.js
  shopfloor_mobile_base/static/wms/src/services/auth_handler_registry.js
  shopfloor_mobile_base/static/wms/src/services/registry.js
Labels: needs review, bot is merging ⏳

#330 [14.0] shopfloor_mobile_base: misc imp/fix
  shopfloor_mobile_base/static/wms/src/loginpage.js
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/static/wms/src/scenario/mixins.js
  shopfloor_mobile_base/static/wms/src/services/auth_handler_registry.js
  shopfloor_mobile_base/templates/main.xml
  shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
  shopfloor_mobile_base_auth_user/static/wms/src/login.js
Labels: needs review, bot is merging ⏳

#331 [14.0] shopfloor_mobile_base: misc fix/imp for colors
  shopfloor_mobile_base/static/wms/src/components/misc.js
  shopfloor_mobile_base/static/wms/src/components/screen.js
  shopfloor_mobile_base/static/wms/src/services/color_registry.js
  shopfloor_mobile_base/static/wms/src/settings/settings.js
  shopfloor_mobile_base/static/wms/src/theme.js
  shopfloor_mobile_base/templates/assets.xml
Labels: bot is merging ⏳

#332 [14.0] shopfloor_mobile_base*: misc fixups
  shopfloor_mobile_base/static/wms/src/theme.js
  shopfloor_mobile_base/templates/assets.xml
  shopfloor_mobile_base_auth_user/static/wms/src/login.js
  shopfloor_ui_tests/package-lock.json
  shopfloor_ui_tests/package.json
Labels: bot is merging ⏳
