Repository OCA/wms, pull requests merged in 2021-10, with the labels that each got.

#299 [14.0][FIX] s_storage_type: allowed location storage types
  stock_storage_type/models/stock_location.py
Labels: needs review, approved, bot is merging ⏳

#292 [14.0][MIG] shopfloor_batch_automatic_creation
  .pre-commit-config.yaml
  setup/shopfloor_batch_automatic_creation/odoo/addons/shopfloor_batch_automatic_creation
  setup/shopfloor_batch_automatic_creation/setup.py
  shopfloor_batch_automatic_creation/README.rst
  shopfloor_batch_automatic_creation/__manifest__.py
  shopfloor_batch_automatic_creation/actions/picking_batch_auto_create.py
  shopfloor_batch_automatic_creation/readme/CONTRIBUTORS.rst
  shopfloor_batch_automatic_creation/readme/CREDITS.rst
  shopfloor_batch_automatic_creation/static/description/index.html
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
Labels: bot is merging ⏳

#246 Add shopfloor_delivery_shipment_mobile
  setup/shopfloor_delivery_shipment_mobile/odoo/addons/shopfloor_delivery_shipment_mobile
  setup/shopfloor_delivery_shipment_mobile/setup.py
  shopfloor_delivery_shipment_mobile/__init__.py
  shopfloor_delivery_shipment_mobile/__manifest__.py
  shopfloor_delivery_shipment_mobile/readme/CONTRIBUTORS.rst
  shopfloor_delivery_shipment_mobile/readme/DESCRIPTION.rst
  shopfloor_delivery_shipment_mobile/static/description/icon.png
  shopfloor_delivery_shipment_mobile/static/description/index.html
  shopfloor_delivery_shipment_mobile/static/wms/src/demo/demo.delivery_shipment.js
  shopfloor_delivery_shipment_mobile/static/wms/src/scenario/delivery_shipment.js
  shopfloor_delivery_shipment_mobile/templates/assets.xml
  shopfloor_mobile_base/static/wms/src/components/detail/detail_card.js
Labels: bot is merging ⏳

#303 [14.0][FIX] delivery_carrier_preference: Fix tests
  delivery_carrier_preference/README.rst
  delivery_carrier_preference/i18n/ca.po
  delivery_carrier_preference/readme/CONTRIBUTORS.rst
  delivery_carrier_preference/readme/CREDITS.rst
  delivery_carrier_preference/static/description/index.html
  delivery_carrier_preference/tests/__init__.py
  delivery_carrier_preference/tests/test_delivery_carrier_preference.py
Labels: bot is merging ⏳

#300 [14.0][MIG] delivery_preference_glue_stock_picking_group: Migration to 14.0
  delivery_preference_glue_stock_picking_group/README.rst
  delivery_preference_glue_stock_picking_group/__init__.py
  delivery_preference_glue_stock_picking_group/__manifest__.py
  delivery_preference_glue_stock_picking_group/i18n/ca.po
  delivery_preference_glue_stock_picking_group/i18n/delivery_preference_glue_stock_picking_group.pot
  delivery_preference_glue_stock_picking_group/i18n/es_AR.po
  delivery_preference_glue_stock_picking_group/models/__init__.py
  delivery_preference_glue_stock_picking_group/models/stock_move.py
  delivery_preference_glue_stock_picking_group/readme/CONTRIBUTORS.rst
  delivery_preference_glue_stock_picking_group/readme/CREDITS.rst
  delivery_preference_glue_stock_picking_group/readme/DESCRIPTION.rst
  delivery_preference_glue_stock_picking_group/readme/ROADMAP.rst
  delivery_preference_glue_stock_picking_group/static/description/icon.png
  delivery_preference_glue_stock_picking_group/static/description/index.html
  delivery_preference_glue_stock_picking_group/tests/__init__.py
  delivery_preference_glue_stock_picking_group/tests/test_delivery_carrier_preference.py
  setup/delivery_preference_glue_stock_picking_group/odoo/addons/delivery_preference_glue_stock_picking_group
  setup/delivery_preference_glue_stock_picking_group/setup.py
Labels: approved, bot is merging ⏳

#301 [MIG] shopfloor_delivery_shipment: Migration to 14.0
  setup/shopfloor_delivery_shipment/odoo/addons/shopfloor_delivery_shipment
  setup/shopfloor_delivery_shipment/setup.py
  shopfloor/actions/data.py
  shopfloor/actions/schema.py
  shopfloor/models/stock_picking.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_delivery_shipment/README.rst
  shopfloor_delivery_shipment/__init__.py
  shopfloor_delivery_shipment/__manifest__.py
  shopfloor_delivery_shipment/actions/__init__.py
  shopfloor_delivery_shipment/actions/data.py
  shopfloor_delivery_shipment/actions/message.py
  shopfloor_delivery_shipment/actions/schema.py
  shopfloor_delivery_shipment/actions/search.py
  shopfloor_delivery_shipment/data/shopfloor_scenario_data.xml
  shopfloor_delivery_shipment/demo/shopfloor_menu_demo.xml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.plantuml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.png
  shopfloor_delivery_shipment/docs/oca_logo.png
  shopfloor_delivery_shipment/i18n/shopfloor_delivery_shipment.pot
  shopfloor_delivery_shipment/models/__init__.py
  shopfloor_delivery_shipment/models/shopfloor_menu.py
  shopfloor_delivery_shipment/readme/CONTRIBUTORS.rst
  shopfloor_delivery_shipment/readme/CREDITS.rst
  shopfloor_delivery_shipment/readme/DESCRIPTION.rst
  shopfloor_delivery_shipment/services/__init__.py
  shopfloor_delivery_shipment/services/delivery_shipment.py
  shopfloor_delivery_shipment/static/description/icon.png
  shopfloor_delivery_shipment/static/description/index.html
  shopfloor_delivery_shipment/tests/__init__.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_base.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_loading_list.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_dock.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_lot.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_package.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_picking.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_product.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_unload.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_validate.py
  shopfloor_delivery_shipment/views/shopfloor_menu.xml
Labels: ready to merge, approved, bot is merging ⏳

#309 [14.0][MIG] shopfloor_delivery_shipment_mobile
  setup/shopfloor_delivery_shipment_mobile/odoo/addons/shopfloor_delivery_shipment_mobile
  setup/shopfloor_delivery_shipment_mobile/setup.py
  shopfloor_delivery_shipment_mobile/README.rst
  shopfloor_delivery_shipment_mobile/__init__.py
  shopfloor_delivery_shipment_mobile/__manifest__.py
  shopfloor_delivery_shipment_mobile/i18n/shopfloor_delivery_shipment_mobile.pot
  shopfloor_delivery_shipment_mobile/readme/CONTRIBUTORS.rst
  shopfloor_delivery_shipment_mobile/readme/DESCRIPTION.rst
  shopfloor_delivery_shipment_mobile/static/description/icon.png
  shopfloor_delivery_shipment_mobile/static/description/index.html
  shopfloor_delivery_shipment_mobile/static/wms/src/demo/demo.delivery_shipment.js
  shopfloor_delivery_shipment_mobile/static/wms/src/scenario/delivery_shipment.js
  shopfloor_delivery_shipment_mobile/templates/assets.xml
Labels: migration, approved, bot is merging ⏳
