Repository OCA/wms, pull requests merged in 2022-04, with the labels that each got.

#381 [14.0][FIX] s_a_t_p_release: fix computation of 'previous_promised_qty'
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/views/stock_move_views.xml
Labels: bug, bot is merging ⏳

#380 [14.0] sf_workstation_mobile: plug config and transl. via registry
  shopfloor_workstation_mobile/static/wms/src/settings/workstation.js
Labels: bot is merging ⏳

#370 [14.0][FIX] shopfloor: fetch lot related to current product(s)
  shopfloor/actions/search.py
  shopfloor/services/checkout.py
  shopfloor/services/cluster_picking.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_actions_search.py
  shopfloor_delivery_shipment/services/delivery_shipment.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_lot.py
  shopfloor_manual_product_transfer/services/manual_product_transfer.py
Labels: bug, ready to merge, approved, bot is merging ⏳

#369 [14.0][FIX] stock_available_to_promise_release: priority propagation on release
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: bug, approved, bot is merging ⏳

#317 [14.0] Add shopfloor_workstation_label_printer
  setup/shopfloor_workstation_label_printer/odoo/addons/shopfloor_workstation_label_printer
  setup/shopfloor_workstation_label_printer/setup.py
  shopfloor_workstation_label_printer/__init__.py
  shopfloor_workstation_label_printer/__manifest__.py
  shopfloor_workstation_label_printer/models/__init__.py
  shopfloor_workstation_label_printer/models/res_users.py
  shopfloor_workstation_label_printer/models/shopfloor_workstation.py
  shopfloor_workstation_label_printer/readme/CONTRIBUTORS.rst
  shopfloor_workstation_label_printer/readme/DESCRIPTION.rst
  shopfloor_workstation_label_printer/views/res_users.xml
  shopfloor_workstation_label_printer/views/shopfloor_workstation.xml
Labels: bot is merging ⏳

#387 shopfloor_mobile_base: make home customizable
  shopfloor_mobile_base/static/wms/src/components/misc.js
  shopfloor_mobile_base/static/wms/src/components/screen.js
  shopfloor_mobile_base/static/wms/src/loginpage.js
  shopfloor_mobile_base/static/wms/src/router.js
  shopfloor_mobile_base/static/wms/src/settings/language.js
  shopfloor_mobile_base/static/wms/src/settings/profile.js
Labels: bot is merging ⏳

#390 [14-0] shopfloor_mobile_base: fix load method in translation registry
  shopfloor_mobile_base/static/wms/src/services/translation_registry.js
Labels: bot is merging ⏳

#360 [14.0][FIX] shopfloor_mobile_base: Ensure the right menu id is initialized …
  shopfloor_mobile_base/static/wms/src/scenario/mixins.js
Labels: bot is merging ⏳

#392 [14.0] shopfloor_mobile_base: fix home routing
  shopfloor_mobile_base/static/wms/src/components/misc.js
  shopfloor_mobile_base/static/wms/src/router.js
Labels: bot is merging ⏳

#391 [14.0] shopfloor_mobile_base: persistent language in app
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/static/wms/src/settings/language.js
Labels: bot is merging ⏳

#393 [14.0] shopfloor*: replace base_jsonify dependency w/ jsonifier
  shopfloor/__manifest__.py
  shopfloor/actions/data.py
  shopfloor_base/__manifest__.py
Labels: approved, bot is merging ⏳

#287 [13.0] shopfloor: support barcode that do not send end of line + trim value
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
Labels: ready to merge, approved, bot is merging ⏳

#289 [13.0] shopfloor - single pack transfer: when pack is empty, raise same error as in zone picking
  shopfloor/services/single_pack_transfer.py
  shopfloor/tests/test_single_pack_transfer.py
Labels: ready to merge, approved, bot is merging ⏳

#400 sf_mobile_base_auth_user: fix demo data load
  shopfloor_mobile_base_auth_user/__manifest__.py
Labels: bot is merging ⏳

#402 shopfloor_base: move version and info to core
  shopfloor_base/models/shopfloor_app.py
  shopfloor_base/tests/test_shopfloor_app.py
  shopfloor_base/utils.py
  shopfloor_mobile_base/__init__.py
  shopfloor_mobile_base/controllers/main.py
  shopfloor_mobile_base/models/__init__.py
  shopfloor_mobile_base/models/shopfloor_app.py
  shopfloor_mobile_base/utils.py
Labels: bot is merging ⏳
