Repository OCA/wms, pull requests merged in 2022-09, with the labels that each got.

#436 [14.0] stock_dynamic_routing: fix rule find domain
  stock_dynamic_routing/models/stock_routing.py
Labels: bug, approved, bot is merging ⏳

#438 shopfloor: fix zone picking label
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: bot is merging ⏳

#437 shopfloor: zone picking scenario stay in zone
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: ready to merge, approved, bot is merging ⏳

#439 [14.0] shopfloor: zone picking add unloading on first screen
  shopfloor/docs/zone_picking_diag_seq.plantuml
  shopfloor/docs/zone_picking_diag_seq.png
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_start.py
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: bot is merging ⏳

#442 shopfloor_mobile: fix zone picking unloading on first screen
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: approved, bot is merging ⏳
