Repository OCA/wms, pull requests merged in 2022-12, with the labels that each got.

#505 shopfloor_mobile: imp zone picking screen title
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: ready to merge, approved, bot is merging ⏳

#514 [14.0][IMP] shopfloor, checkout: add a hook for lines packaged
  shopfloor/services/checkout.py
Labels: bot is merging ⏳

#501 [14.0] shopfloor: add get work option on location content transfer
  shopfloor/actions/message.py
  shopfloor/actions/stock.py
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/docs/location_content_transfer_diag_seq.plantuml
  shopfloor/docs/location_content_transfer_diag_seq.png
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/location_content_transfer.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_location_content_transfer_base.py
  shopfloor/tests/test_location_content_transfer_get_work.py
  shopfloor/tests/test_location_content_transfer_putaway.py
  shopfloor/tests/test_location_content_transfer_start.py
  shopfloor/views/shopfloor_menu.xml
Labels: approved, bot is merging ⏳

#511 [14.0] shopfloor: fix zone picking scenario
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: ready to merge, approved, bot is merging ⏳

#519 [14.0][IMP] shopfloor_mobile_base: create event to handle 401 error
  shopfloor_mobile_base/static/wms/src/fetch.js
  shopfloor_mobile_base/static/wms/src/main.js
Labels: approved, bot is merging ⏳

#522 [UPD] Copier update
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  requirements.txt
  sale_stock_available_to_promise_release/__manifest__.py
  stock_move_source_relocate_dynamic_routing/__manifest__.py
Labels: bot is merging ⏳
