Repository OCA/wms, pull requests merged in 2022-01, with the labels that each got.

#349 [13.0][IMP] shopfloor: performance improvement
  shopfloor/models/stock_package_level.py
Labels: enhancement, approved, bot is merging ⏳

#345 [13.0] Shopfloor: Control the display of the virtual keyboard (Gboard) + SECURITY FIX
  shopfloor_mobile_base/README.rst
  shopfloor_mobile_base/readme/CONTRIBUTORS.rst
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
  shopfloor_mobile_base/static/wms/src/css/main.css
  shopfloor_mobile_base/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile_base/static/wms/src/loginpage.js
Labels: enhancement, ready to merge, approved, bot is merging ⏳

#346 [13.0] shopfloor: fix computation of contained packagings
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.js
Labels: bug, bot is merging ⏳

#361 [14.0] Update dev statuses on some modules
  sale_stock_available_to_promise_release/__manifest__.py
  shopfloor/__manifest__.py
  shopfloor_base/__manifest__.py
  shopfloor_mobile_base/__manifest__.py
  stock_available_to_promise_release/__manifest__.py
  stock_checkout_sync/__manifest__.py
  stock_picking_type_shipping_policy/__manifest__.py
  stock_storage_type/__manifest__.py
Labels: bot is merging ⏳

#362 [14.0][FW] shopfloor_delivery_shipment: restrict dock to current WH
  shopfloor_delivery_shipment/services/delivery_shipment.py
Labels: bot is merging ⏳, port

#358 [14.0] Switch tests to GH actions
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .t2d.yml
  oca_dependencies.txt
  sale_stock_available_to_promise_release_cutoff/README.rst
  sale_stock_available_to_promise_release_cutoff/__manifest__.py
  sale_stock_available_to_promise_release_cutoff/static/description/index.html
  stock_picking_completion_info/__manifest__.py
  stock_reception_screen_qty_by_packaging/__manifest__.py
Labels: enhancement, approved

#351 [14.0] shopfloor: refactor design of packaging qty picker
  shopfloor_mobile/README.rst
  shopfloor_mobile/readme/CONTRIBUTORS.rst
  shopfloor_mobile/static/wms/src/components/batch_picking_line_detail.js
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.js
  shopfloor_mobile/static/wms/src/css/main.css
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: enhancement, ready to merge, approved, bot is merging ⏳

#365 [13.0] shopfloor: refactor the packaging quantity picker - fixup!
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.js
Labels: bug, approved, bot is merging ⏳

#352 [14.0] shopfloor: fix computation of contained packagings
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.js
Labels: bug, ready to merge, approved, bot is merging ⏳

#340 [14.0][FIX] shopfloor_delivery_shipment is not an application
  shopfloor_delivery_shipment/__manifest__.py
Labels: bug, bot is merging ⏳

#356 [14.0] apply product putaway for strategy none
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/test_storage_type_putaway_strategy.py
Labels: enhancement, approved, bot is merging ⏳

#354 [14.0][FW] [13.0][IMP] shopfloor: performance improvement
  shopfloor/models/stock_package_level.py
Labels: enhancement, ready to merge, approved, bot is merging ⏳, port

#348 [13.0][IMP] shopfloor_delivery_shipment: restrict dock to current WH
  shopfloor_delivery_shipment/services/delivery_shipment.py
Labels: enhancement, bot is merging ⏳

#367 [14.0] Fix access right issues when using actions
  sale_stock_available_to_promise_release/models/sale_order.py
  stock_available_to_promise_release/models/product_product.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_storage_type/models/stock_location_storage_type.py
  stock_storage_type/models/stock_storage_location_sequence.py
Labels: bug, bot is merging ⏳

#357 [14.0][[IMP] Add translations FR/EN to scenarii cluster_picking and location…
  shopfloor_mobile/static/wms/src/i18n/add_translations_to_registry.js
  shopfloor_mobile/static/wms/src/i18n/en.json
  shopfloor_mobile/static/wms/src/i18n/fr.json
  shopfloor_mobile/static/wms/src/scenario/cluster_picking.js
  shopfloor_mobile/static/wms/src/scenario/location_content_transfer.js
  shopfloor_mobile/templates/assets.xml
  shopfloor_mobile_base/static/wms/src/services/translation_registry.js
Labels: ready to merge, approved, bot is merging ⏳

#366 [14.0] shopfloor_mobile_base: add min.js files in lib
  shopfloor_mobile_base/static/wms/src/lib/lodash.js
  shopfloor_mobile_base/static/wms/src/lib/vue-router.js
  shopfloor_mobile_base/static/wms/src/lib/vue-router.min.js
  shopfloor_mobile_base/static/wms/src/lib/vue-super-call.js
  shopfloor_mobile_base/static/wms/src/lib/vue-super-call.min.js
  shopfloor_mobile_base/static/wms/src/lib/vuetify/vuetify.js
  shopfloor_mobile_base/static/wms/src/lib/vuetify/vuetify.min.js
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/templates/assets.xml
Labels: bot is merging ⏳
