Repository OCA/wms, pull requests merged in 2022-10, with the labels that each got.

#463 [14.0] shopfloor_mobile_base: display version in settings page too
  shopfloor_mobile_base/static/wms/src/components/screen.js
  shopfloor_mobile_base/static/wms/src/homepage.js
  shopfloor_mobile_base/static/wms/src/settings/settings.js
Labels: bot is merging ⏳

#462 [14.0] sf_mobile_base: add version and user header to requests
  shopfloor_mobile_base/static/wms/src/main.js
Labels: approved, bot is merging ⏳

#431 [14.0][ADD] stock_warehouse_flow[_release]: manage multiple delivery routes for a single warehouse
  delivery_carrier_preference/models/stock_move.py
  setup/stock_warehouse_flow/odoo/addons/stock_warehouse_flow
  setup/stock_warehouse_flow/setup.py
  setup/stock_warehouse_flow_release/odoo/addons/stock_warehouse_flow_release
  setup/stock_warehouse_flow_release/setup.py
  stock_available_to_promise_release/models/stock_move.py
  stock_warehouse_flow/README.rst
  stock_warehouse_flow/__init__.py
  stock_warehouse_flow/__manifest__.py
  stock_warehouse_flow/demo/stock_warehouse_flow.xml
  stock_warehouse_flow/migrations/14.0.1.0.1/pre-migrate.py
  stock_warehouse_flow/models/__init__.py
  stock_warehouse_flow/models/delivery_carrier.py
  stock_warehouse_flow/models/stock_location_route.py
  stock_warehouse_flow/models/stock_move.py
  stock_warehouse_flow/models/stock_warehouse.py
  stock_warehouse_flow/models/stock_warehouse_flow.py
  stock_warehouse_flow/readme/CONFIGURE.rst
  stock_warehouse_flow/readme/CONTRIBUTORS.rst
  stock_warehouse_flow/readme/DESCRIPTION.rst
  stock_warehouse_flow/readme/ROADMAP.rst
  stock_warehouse_flow/readme/USAGE.rst
  stock_warehouse_flow/security/ir.model.access.csv
  stock_warehouse_flow/static/description/config.png
  stock_warehouse_flow/static/description/flow.png
  stock_warehouse_flow/static/description/icon.png
  stock_warehouse_flow/static/description/index.html
  stock_warehouse_flow/tests/__init__.py
  stock_warehouse_flow/tests/common.py
  stock_warehouse_flow/tests/test_delivery_carrier.py
  stock_warehouse_flow/tests/test_warehouse.py
  stock_warehouse_flow/tests/test_warehouse_flow.py
  stock_warehouse_flow/views/delivery_carrier.xml
  stock_warehouse_flow/views/stock_location_route.xml
  stock_warehouse_flow/views/stock_warehouse.xml
  stock_warehouse_flow/views/stock_warehouse_flow.xml
  stock_warehouse_flow_release/README.rst
  stock_warehouse_flow_release/__init__.py
  stock_warehouse_flow_release/__manifest__.py
  stock_warehouse_flow_release/models/__init__.py
  stock_warehouse_flow_release/models/stock_move.py
  stock_warehouse_flow_release/readme/CONTRIBUTORS.rst
  stock_warehouse_flow_release/readme/DESCRIPTION.rst
  stock_warehouse_flow_release/static/description/icon.png
  stock_warehouse_flow_release/tests/__init__.py
  stock_warehouse_flow_release/tests/test_warehouse_flow_release.py
Labels: needs review, bot is merging ⏳

#467 [14.0][FIX] stock_warehouse_flow: fix dependencies
  stock_warehouse_flow/__manifest__.py
  stock_warehouse_flow/models/stock_warehouse_flow.py
  stock_warehouse_flow/views/stock_warehouse_flow.xml
Labels: bug, bot is merging ⏳

#464 [14.0][FW] [13.0] shopfloor_mobile: split core -> shopfloor_mobile_base
  .oca/oca-port/blacklist/shopfloor.json
Labels: needs review

#472 [14.0] sf_mobile_base: propagate root on login/logout events
  shopfloor_mobile_base/static/wms/src/main.js
Labels: bot is merging ⏳

#469 [14.0] sf_mobile_base: add report issue action
  shopfloor_mobile_base/static/wms/src/components/misc.js
  shopfloor_mobile_base/static/wms/src/components/report_issue.js
  shopfloor_mobile_base/static/wms/src/components/screen.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.de.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.fr.js
  shopfloor_mobile_base/static/wms/src/loginpage.js
  shopfloor_mobile_base/templates/assets.xml
Labels: bot is merging ⏳

#471 [14.0] shopfloor_rest_log: store app version and real user
  shopfloor_rest_log/__init__.py
  shopfloor_rest_log/__manifest__.py
  shopfloor_rest_log/components/__init__.py
  shopfloor_rest_log/components/service.py
  shopfloor_rest_log/migrations/14.0.1.1.0/post-migrate.py
  shopfloor_rest_log/migrations/14.0.1.2.0/post-migrate.py
  shopfloor_rest_log/models/__init__.py
  shopfloor_rest_log/models/rest_log.py
  shopfloor_rest_log/views/rest_log.xml
Labels: bot is merging ⏳

#473 sf_mobile_base: move manifest making to app model + minor fixes
  shopfloor_base/models/shopfloor_app.py
  shopfloor_base/tests/test_shopfloor_app.py
  shopfloor_mobile_base/controllers/main.py
  shopfloor_mobile_base/static/wms/src/main.js
Labels: bot is merging ⏳

#427 Add sublocation scan on shopfloor delivery scenario
  shopfloor/actions/message.py
  shopfloor/services/delivery.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_delivery_base.py
  shopfloor/tests/test_delivery_scan_deliver.py
  shopfloor/tests/test_delivery_sublocation.py
  shopfloor_mobile/static/wms/src/scenario/delivery.js
Labels: ready to merge, approved, bot is merging ⏳

#432 [14.0] shopfloor: change search location action
  shopfloor/actions/search.py
  shopfloor/tests/test_actions_search.py
Labels: approved, bot is merging ⏳

#474 [14.0][FIX] shopfloor, delivery: process lines of one delivery operation
  shopfloor/models/stock_move_line.py
  shopfloor/services/delivery.py
  shopfloor/tests/test_delivery_scan_deliver.py
Labels: bug, bot is merging ⏳
