Repository OCA/wms, pull requests merged in 2022-05, with the labels that each got.

#405 [14.0] shopfloor_base + mobile: configure languages via backend
  shopfloor_base/models/shopfloor_app.py
  shopfloor_base/services/user.py
  shopfloor_base/tests/test_shopfloor_app.py
  shopfloor_base/tests/test_user_config_service.py
  shopfloor_base/tests/test_user_service.py
  shopfloor_base/views/shopfloor_app.xml
  shopfloor_mobile_base/static/wms/src/components/misc.js
  shopfloor_mobile_base/static/wms/src/i18n.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.de.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.fr.js
  shopfloor_mobile_base/static/wms/src/loginpage.js
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/static/wms/src/mixin.js
  shopfloor_mobile_base/static/wms/src/services/translation_registry.js
  shopfloor_mobile_base/static/wms/src/settings/settings.js
Labels: bot is merging ⏳

#406 shopfloor*: fix datetime handling
  shopfloor/actions/data_detail.py
  shopfloor_base/actions/data.py
  shopfloor_base/services/menu.py
  shopfloor_mobile_base/static/wms/src/utils.js
Labels: bug, approved, bot is merging ⏳

#353 [14.0] shopfloor: support barcode that do not send end of line + trim value
  shopfloor_mobile_base/README.rst
  shopfloor_mobile_base/readme/CONTRIBUTORS.rst
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
Labels: ready to merge, approved, bot is merging ⏳

#411 [14.0] shopfloor_mobile_base: manifest & app info improvements
  shopfloor_base/models/shopfloor_app.py
  shopfloor_base/tests/test_shopfloor_app.py
  shopfloor_mobile_base/controllers/main.py
Labels: bot is merging ⏳

#407 [14.0] shopfloor_mobile_base: dynamic storage type
  shopfloor_mobile_base/static/wms/src/lib/vue2-storage.min.js
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/static/wms/src/services/config_registry.js
Labels: bot is merging ⏳

#408 [14.0] shopfloor_ui_tests: implement jest unit tests
  .github/workflows/ui-unit-tests.yml
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
  shopfloor_ui_tests/README.rst
  shopfloor_ui_tests/babel.config.js
  shopfloor_ui_tests/jest.config.js
  shopfloor_ui_tests/package-lock.json
  shopfloor_ui_tests/package.json
  shopfloor_ui_tests/unit_tests/components/searchbar.test.js
  shopfloor_ui_tests/unit_tests/methods/format_date.test.js
  shopfloor_ui_tests/unit_tests/mocks/root.js
Labels: bot is merging ⏳

#413 [14.0] shopfloor_ui_tests: improve e2e ui tests
  shopfloor_example/static/wms/src/demo/demo.example.js
  shopfloor_example/templates/assets.xml
  shopfloor_mobile_base/static/wms/src/demo/demo.core.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.de.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile_base/static/wms/src/i18n/i18n.fr.js
  shopfloor_ui_tests/README.rst
  shopfloor_ui_tests/cypress.json
  shopfloor_ui_tests/cypress/fixtures/demo_profiles.json
  shopfloor_ui_tests/cypress/fixtures/example_partners.json
  shopfloor_ui_tests/cypress/fixtures/translations.json
  shopfloor_ui_tests/cypress/integration/shopfloor_example/test_example.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base/test_language.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base/test_navigation.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base/test_profile.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base_auth_api_key/test_authentication_apikey.js
  shopfloor_ui_tests/cypress/integration/shopfloor_mobile_base_auth_user/test_authentication_user.js
  shopfloor_ui_tests/cypress/support/commands.js
  shopfloor_ui_tests/cypress/support/index.js
  shopfloor_ui_tests/package-lock.json
  shopfloor_ui_tests/package.json
Labels: bot is merging ⏳

#364 [14.0][FIX] fixing .gitignore lib
  .gitignore
Labels: stale
