Repository OCA/wms, pull requests merged in 2022-11, with the labels that each got.

#481 [14.0][FIX] Update from copier template
  .copier-answers.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
Labels: bug

#482 [14.0][FIX] shopfloor_manual_product_transfer: fix, unreserve moves having the same product
  shopfloor_manual_product_transfer/services/manual_product_transfer.py
Labels: bug, bot is merging ⏳

#475 [16.0] stock_available_to_promise_release: Migration to 16.0
  setup/stock_available_to_promise_release/odoo/addons/stock_available_to_promise_release
  setup/stock_available_to_promise_release/setup.py
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/__init__.py
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/i18n/es_AR.po
  stock_available_to_promise_release/i18n/stock_available_to_promise_release.pot
  stock_available_to_promise_release/models/__init__.py
  stock_available_to_promise_release/models/product_product.py
  stock_available_to_promise_release/models/res_company.py
  stock_available_to_promise_release/models/res_config_settings.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/models/stock_picking_type.py
  stock_available_to_promise_release/models/stock_route.py
  stock_available_to_promise_release/models/stock_rule.py
  stock_available_to_promise_release/readme/CONFIGURE.rst
  stock_available_to_promise_release/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release/readme/CREDITS.rst
  stock_available_to_promise_release/readme/DESCRIPTION.rst
  stock_available_to_promise_release/readme/USAGE.rst
  stock_available_to_promise_release/security/ir.model.access.csv
  stock_available_to_promise_release/static/description/icon.png
  stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/views/product_product_views.xml
  stock_available_to_promise_release/views/res_config_settings.xml
  stock_available_to_promise_release/views/stock_move_views.xml
  stock_available_to_promise_release/views/stock_picking_type_views.xml
  stock_available_to_promise_release/views/stock_picking_views.xml
  stock_available_to_promise_release/views/stock_route_views.xml
  stock_available_to_promise_release/wizards/__init__.py
  stock_available_to_promise_release/wizards/stock_release.py
  stock_available_to_promise_release/wizards/stock_release_views.xml
Labels: migration, bot is merging ⏳

#479 [14.0][IMP] shopfloor_base: improve profile
  shopfloor_base/models/shopfloor_profile.py
  shopfloor_base/views/shopfloor_profile_views.xml
Labels: approved, bot is merging ⏳

#418 [14.0] shopfloor, delivery: force qty to process to 1 when scanning a product or a lot
  shopfloor/actions/message.py
  shopfloor/services/delivery.py
  shopfloor/tests/test_delivery_base.py
  shopfloor/tests/test_delivery_scan_deliver.py
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#480 [14.0] sf_manual_product_transfer: cancel button now cancels the created move
  shopfloor_manual_product_transfer/actions/message.py
  shopfloor_manual_product_transfer/docs/manual_product_transfer_diag_seq.plantuml
  shopfloor_manual_product_transfer/docs/manual_product_transfer_diag_seq.png
  shopfloor_manual_product_transfer/services/manual_product_transfer.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_scan_destination_location.py
  shopfloor_manual_product_transfer_mobile/static/wms/src/scenario/manual_product_transfer.js
Labels: bug, bot is merging ⏳

#488 [14.0] Add stock_release_channel
  setup/stock_release_channel/odoo/addons/stock_release_channel
  setup/stock_release_channel/setup.py
  stock_release_channel/README.rst
  stock_release_channel/__init__.py
  stock_release_channel/__manifest__.py
  stock_release_channel/data/ir_cron_data.xml
  stock_release_channel/data/queue_job_data.xml
  stock_release_channel/data/stock_release_channel_data.xml
  stock_release_channel/models/__init__.py
  stock_release_channel/models/sale_order_line.py
  stock_release_channel/models/stock_move.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/readme/CONFIGURE.rst
  stock_release_channel/readme/CONTRIBUTORS.rst
  stock_release_channel/readme/CREDITS.rst
  stock_release_channel/readme/DESCRIPTION.rst
  stock_release_channel/readme/USAGE.rst
  stock_release_channel/security/stock_release_channel.xml
  stock_release_channel/static/description/index.html
  stock_release_channel/static/src/js/progressbar_fractional_widget.js
  stock_release_channel/static/src/scss/stock_release_channel.scss
  stock_release_channel/tests/__init__.py
  stock_release_channel/tests/common.py
  stock_release_channel/tests/test_channel_action.py
  stock_release_channel/tests/test_channel_computed_fields.py
  stock_release_channel/tests/test_channel_release_batch.py
  stock_release_channel/tests/test_release_channel.py
  stock_release_channel/views/assets.xml
  stock_release_channel/views/stock_picking_views.xml
  stock_release_channel/views/stock_release_channel_views.xml
Labels: approved, bot is merging ⏳

#484 [16.0] [MIG] stock_dynamic_routing
  setup/stock_dynamic_routing/odoo/addons/stock_dynamic_routing
  setup/stock_dynamic_routing/setup.py
  stock_dynamic_routing/README.rst
  stock_dynamic_routing/__init__.py
  stock_dynamic_routing/__manifest__.py
  stock_dynamic_routing/demo/stock_location_demo.xml
  stock_dynamic_routing/demo/stock_picking_type_demo.xml
  stock_dynamic_routing/demo/stock_routing_demo.xml
  stock_dynamic_routing/i18n/es_AR.po
  stock_dynamic_routing/i18n/stock_dynamic_routing.pot
  stock_dynamic_routing/models/__init__.py
  stock_dynamic_routing/models/stock_location.py
  stock_dynamic_routing/models/stock_move.py
  stock_dynamic_routing/models/stock_picking.py
  stock_dynamic_routing/models/stock_routing.py
  stock_dynamic_routing/models/stock_routing_rule.py
  stock_dynamic_routing/readme/CONFIGURE.rst
  stock_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_dynamic_routing/readme/DESCRIPTION.rst
  stock_dynamic_routing/readme/USAGE.rst
  stock_dynamic_routing/security/ir.model.access.csv
  stock_dynamic_routing/static/description/icon.png
  stock_dynamic_routing/static/description/index.html
  stock_dynamic_routing/tests/__init__.py
  stock_dynamic_routing/tests/test_routing_pull.py
  stock_dynamic_routing/tests/test_routing_push.py
  stock_dynamic_routing/tests/test_routing_rule.py
  stock_dynamic_routing/views/stock_routing_views.xml
Labels: migration, ready to merge, needs review, approved, bot is merging ⏳

#492 [14.0] shopfloor_mobile: checkout packaging list hide type
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: approved, bot is merging ⏳

#476 [14.0] shopfloor_manual_product_transfer: new warning about reserved qty
  shopfloor_manual_product_transfer/actions/message.py
  shopfloor_manual_product_transfer/services/manual_product_transfer.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_base.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_confirm_quantity.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_scan_product.py
  shopfloor_manual_product_transfer_mobile/static/wms/src/scenario/manual_product_transfer.js
Labels: ready to merge, approved, bot is merging ⏳

#495 [UPD] Copier update
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#489 [14.0][IMP] stock_warehouse_flow: fix is_valid_for_move return value
  stock_warehouse_flow/models/stock_warehouse_flow.py
  stock_warehouse_flow/tests/test_warehouse_flow.py
Labels: bug, approved, bot is merging ⏳

#350 [14.0] Shopfloor: Control the display of the virtual keyboard (Gboard) + SECURITY FIX
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
  shopfloor_mobile_base/static/wms/src/css/main.css
  shopfloor_mobile_base/static/wms/src/i18n/i18n.en.js
  shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
Labels: enhancement, ready to merge, approved, bot is merging ⏳

#503 [14.0][IMP] Shopfloor improvements prior to reception scenario
  shopfloor/actions/data.py
  shopfloor/actions/message.py
  shopfloor/actions/schema.py
  shopfloor/actions/search.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_summary.js
  shopfloor_mobile/static/wms/src/wms_utils.js
  shopfloor_mobile_base/static/wms/src/components/datepicker/date_picker.js
  shopfloor_mobile_base/static/wms/src/components/list.js
  shopfloor_mobile_base/static/wms/src/components/searchbar/list_filter.js
  shopfloor_mobile_base/static/wms/src/css/main.css
  shopfloor_mobile_base/templates/assets.xml
Labels: approved, bot is merging ⏳

#499 [14.0] shopfloor: checkout improve lines hooks
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_cancel_line.py
  shopfloor/tests/test_checkout_list_package.py
  shopfloor/tests/test_checkout_new_package.py
  shopfloor/tests/test_checkout_no_package.py
  shopfloor/tests/test_checkout_scan.py
  shopfloor/tests/test_checkout_scan_line.py
  shopfloor/tests/test_checkout_scan_package_action.py
  shopfloor/tests/test_checkout_select.py
  shopfloor/tests/test_checkout_select_line.py
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: bot is merging ⏳

#491 [14.0] shopfloor_manual_product_transfer & location_content_transfer: unreserve refactoring
  shopfloor/actions/__init__.py
  shopfloor/actions/stock_unreserve.py
  shopfloor/services/location_content_transfer.py
  shopfloor_manual_product_transfer/services/manual_product_transfer.py
  shopfloor_manual_product_transfer/tests/test_manual_product_transfer_confirm_quantity.py
Labels: approved, bot is merging ⏳
