Repository OCA/wms, pull requests merged in 2022-06, with the labels that each got.

#403 [14.0] shopfloor: Fix extract move lines
  shopfloor/actions/stock.py
  shopfloor/models/stock_move.py
  shopfloor/models/stock_move_line.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/service.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_location_content_transfer_base.py
  shopfloor/tests/test_location_content_transfer_mix.py
  shopfloor/tests/test_location_content_transfer_set_destination_package_or_line.py
  shopfloor/tests/test_location_content_transfer_start.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_buffer_lines.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
Labels: enhancement, approved, bot is merging ⏳

#398 [14.0] shopfloor, delivery: new option 'Process as pre-packaged' products
  shopfloor/__manifest__.py
  shopfloor/actions/search.py
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/migrations/14.0.2.3.0/pre-migration.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/models/stock_move_line.py
  shopfloor/services/delivery.py
  shopfloor/tests/test_delivery_scan_deliver.py
  shopfloor/views/shopfloor_menu.xml
Labels: approved, bot is merging ⏳

#419 [14.0][FIX] shopfloor: fix user comparison in 'mark_move_lines_as_picked'
  shopfloor/actions/stock.py
Labels: bug, approved, bot is merging ⏳

#404 [14.0] shopfloor: add options on cluster and zone picking
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/models/shopfloor_menu.py
  shopfloor/models/stock_quant_package.py
  shopfloor/services/cluster_picking.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_cluster_picking_scan_destination.py
  shopfloor/tests/test_cluster_picking_unload.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
  shopfloor/views/shopfloor_menu.xml
Labels: approved, bot is merging ⏳

#410 [14.0] Shopfloor, checkout: Allow to scan products
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_scan.py
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: enhancement, bot is merging ⏳

#422 [14.0] sale_stock_available_to_promise_release_cutoff: set to Alpha
  sale_stock_available_to_promise_release_cutoff/__manifest__.py
Labels: bug, bot is merging ⏳
