Repository OCA/wms, pull requests merged in 2022-03, with the labels that each got.

#377 [IMP] delivery_carrier_preference: access rights for stock user
  delivery_carrier_preference/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#378 [14.0][FIX] delivery_carrier_preference: fix dependency
  delivery_carrier_preference/__manifest__.py
  delivery_carrier_preference/views/stock_move.xml
Labels: bug, approved, bot is merging ⏳

#379 [14.0] Improve shopfloor line priority search
  shopfloor/actions/move_line_search.py
Labels: approved, bot is merging ⏳

#375 [14.0] shopfloor_base: add svg icon
  shopfloor_base/static/description/icon.png
  shopfloor_base/static/description/icon.svg
Labels: ready to merge, approved, bot is merging ⏳
