Repository OCA/wms, pull requests merged in 2023-10, with the labels that each got.

#710 [14.0][IMP] shopfloor_single_product_transfer improve confirmation
  shopfloor_single_product_transfer/services/single_product_transfer.py
  shopfloor_single_product_transfer/tests/test_scan_product.py
  shopfloor_single_product_transfer/tests/test_set_quantity.py
  shopfloor_single_product_transfer/tests/test_start.py
  shopfloor_single_product_transfer_force_package/services/single_product_transfer.py
  shopfloor_single_product_transfer_force_package/tests/test_force_package.py
  shopfloor_single_product_transfer_mobile/static/src/scenario/single_product_transfer.js
  shopfloor_single_product_transfer_unique_order_at_location/tests/test_set_quantity.py
Labels: bot is merging ⏳

#755 [14.0][IMP] stock_move_source_relocate: add return
  stock_move_source_relocate/models/stock_move.py
Labels: approved, bot is merging ⏳

#760 [FIX] stock_storage_type: fix max_weight references
  stock_storage_type/demo/product_packaging.xml
  stock_storage_type/i18n/it.po
Labels: bot is merging ⏳

#761 [16.0][ADD] stock_release_channel_shipment_advice
  setup/stock_release_channel_shipment_advice/odoo/addons/stock_release_channel_shipment_advice
  setup/stock_release_channel_shipment_advice/setup.py
  stock_release_channel_shipment_advice/README.rst
  stock_release_channel_shipment_advice/__init__.py
  stock_release_channel_shipment_advice/__manifest__.py
  stock_release_channel_shipment_advice/models/__init__.py
  stock_release_channel_shipment_advice/models/shipment_advice.py
  stock_release_channel_shipment_advice/models/stock_release_channel.py
  stock_release_channel_shipment_advice/readme/CONTRIBUTORS.rst
  stock_release_channel_shipment_advice/readme/DESCRIPTION.rst
  stock_release_channel_shipment_advice/readme/USAGE.rst
  stock_release_channel_shipment_advice/static/description/icon.png
  stock_release_channel_shipment_advice/static/description/index.html
  stock_release_channel_shipment_advice/tests/__init__.py
  stock_release_channel_shipment_advice/tests/test_stock_release_channel_shipment_advice.py
  stock_release_channel_shipment_advice/views/shipment_advice.xml
  stock_release_channel_shipment_advice/views/stock_release_channel.xml
  stock_release_channel_shipment_advice/wizards/__init__.py
  stock_release_channel_shipment_advice/wizards/shipment_advice_planner.py
  stock_release_channel_shipment_advice/wizards/shipment_advice_planner.xml
Labels: bot is merging ⏳

#750 [16.0] [ADD] stock_release_channel_shipment_lead_time
  setup/stock_release_channel_shipment_lead_time/odoo/addons/stock_release_channel_shipment_lead_time
  setup/stock_release_channel_shipment_lead_time/setup.py
  stock_release_channel_shipment_lead_time/README.rst
  stock_release_channel_shipment_lead_time/__init__.py
  stock_release_channel_shipment_lead_time/__manifest__.py
  stock_release_channel_shipment_lead_time/models/__init__.py
  stock_release_channel_shipment_lead_time/models/shipment_advice.py
  stock_release_channel_shipment_lead_time/models/stock_picking.py
  stock_release_channel_shipment_lead_time/models/stock_release_channel.py
  stock_release_channel_shipment_lead_time/readme/CONTRIBUTORS.rst
  stock_release_channel_shipment_lead_time/readme/CREDITS.rst
  stock_release_channel_shipment_lead_time/readme/DESCRIPTION.rst
  stock_release_channel_shipment_lead_time/static/description/index.html
  stock_release_channel_shipment_lead_time/tests/__init__.py
  stock_release_channel_shipment_lead_time/tests/test_assign_channel_shipment_date.py
  stock_release_channel_shipment_lead_time/tests/test_release_shipment_date.py
  stock_release_channel_shipment_lead_time/views/shipment_advice_views.xml
  stock_release_channel_shipment_lead_time/views/stock_release_channel_views.xml
  stock_release_channel_shipment_lead_time/wizards/__init__.py
  stock_release_channel_shipment_lead_time/wizards/shipment_advice_planner.py
Labels: ready to merge, approved, bot is merging ⏳

#751 [16.0][ADD] stock_release_channel_partner_public_holidays
  setup/stock_release_channel_partner_public_holidays/odoo/addons/stock_release_channel_partner_public_holidays
  setup/stock_release_channel_partner_public_holidays/setup.py
  stock_release_channel_partner_public_holidays/README.rst
  stock_release_channel_partner_public_holidays/__init__.py
  stock_release_channel_partner_public_holidays/__manifest__.py
  stock_release_channel_partner_public_holidays/models/__init__.py
  stock_release_channel_partner_public_holidays/models/stock_picking.py
  stock_release_channel_partner_public_holidays/models/stock_release_channel.py
  stock_release_channel_partner_public_holidays/readme/CONTRIBUTORS.rst
  stock_release_channel_partner_public_holidays/readme/CREDIT.rst
  stock_release_channel_partner_public_holidays/readme/DESCRIPTION.rst
  stock_release_channel_partner_public_holidays/readme/USAGE.rst
  stock_release_channel_partner_public_holidays/static/description/channel_form.png
  stock_release_channel_partner_public_holidays/static/description/icon.png
  stock_release_channel_partner_public_holidays/static/description/index.html
  stock_release_channel_partner_public_holidays/tests/__init__.py
  stock_release_channel_partner_public_holidays/tests/test_release_on_holiday.py
  stock_release_channel_partner_public_holidays/views/stock_release_channel.xml
Labels: ready to merge, approved, bot is merging ⏳

#740 [16.0][ADD] stock_release_channel_cutoff
  setup/stock_release_channel_cutoff/odoo/addons/stock_release_channel_cutoff
  setup/stock_release_channel_cutoff/setup.py
  stock_release_channel_cutoff/README.rst
  stock_release_channel_cutoff/__init__.py
  stock_release_channel_cutoff/__manifest__.py
  stock_release_channel_cutoff/models/__init__.py
  stock_release_channel_cutoff/models/stock_release_channel.py
  stock_release_channel_cutoff/readme/CONTRIBUTORS.rst
  stock_release_channel_cutoff/readme/CREDITS.rst
  stock_release_channel_cutoff/readme/DESCRIPTION.rst
  stock_release_channel_cutoff/static/description/icon.png
  stock_release_channel_cutoff/static/description/index.html
  stock_release_channel_cutoff/tests/__init__.py
  stock_release_channel_cutoff/tests/test_compute_cutoff_time.py
  stock_release_channel_cutoff/views/stock_release_channel_views.xml
Labels: approved, bot is merging ⏳

#673 [IMP] - stock_available_to_promise_release: Improve unrelease check message
  stock_available_to_promise_release/models/stock_move.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#763 [IMP] stock_available_to_promise_release: Add hook to retrieve locations domain
  stock_available_to_promise_release/models/__init__.py
  stock_available_to_promise_release/models/stock_location.py
  stock_available_to_promise_release/models/stock_move.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#689 [IMP] stock_release_channel: Move release channel data to demo
  stock_release_channel/__manifest__.py
  stock_release_channel/demo/stock_release_channel.xml
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#691 [16.0][FIX] stock_release_channel: fix form view
  stock_release_channel/views/stock_release_channel_views.xml
Labels: bot is merging ⏳

#667 [FIX] - don't copy release channel when duplicating a picking
  stock_release_channel/models/stock_picking.py
Labels: enhancement, needs review, bot is merging ⏳

#765 [14.0][FIX] sf_spt_force_package: fix after change on depending module
  shopfloor_single_product_transfer_force_package/services/single_product_transfer.py
  shopfloor_single_product_transfer_force_package/tests/test_force_package.py
Labels: bot is merging ⏳

#634 [16.0][ADD] stock_release_channel_propagate_channel_picking
  setup/stock_release_channel_propagate_channel_picking/odoo/addons/stock_release_channel_propagate_channel_picking
  setup/stock_release_channel_propagate_channel_picking/setup.py
  stock_release_channel/tests/common.py
  stock_release_channel_propagate_channel_picking/README.rst
  stock_release_channel_propagate_channel_picking/__init__.py
  stock_release_channel_propagate_channel_picking/__manifest__.py
  stock_release_channel_propagate_channel_picking/models/__init__.py
  stock_release_channel_propagate_channel_picking/models/stock_move.py
  stock_release_channel_propagate_channel_picking/models/stock_picking_type.py
  stock_release_channel_propagate_channel_picking/readme/CONFIGURE.rst
  stock_release_channel_propagate_channel_picking/readme/CONTRIBUTORS.rst
  stock_release_channel_propagate_channel_picking/readme/DESCRIPTION.rst
  stock_release_channel_propagate_channel_picking/readme/USAGE.rst
  stock_release_channel_propagate_channel_picking/static/description/icon.png
  stock_release_channel_propagate_channel_picking/static/description/index.html
  stock_release_channel_propagate_channel_picking/tests/__init__.py
  stock_release_channel_propagate_channel_picking/tests/test_procurement.py
  stock_release_channel_propagate_channel_picking/views/stock_picking_type.xml
Labels: ready to merge, approved, bot is merging ⏳

#772 [14.0] dotfiles update with manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  shopfloor/i18n/it.po
  stock_dynamic_routing/views/stock_routing_views.xml
  stock_move_source_relocate/views/stock_source_relocate_views.xml
  stock_release_channel/i18n/it.po
  stock_storage_type/views/stock_storage_location_sequence.xml
Labels: bot is merging ⏳
