Repository OCA/wms, pull requests merged in 2023-01, with the labels that each got.

#526 [14.0][IMP] stock_release_channel only call assign_release_channel on released moves
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release/static/description/index.html
  stock_release_channel/models/stock_move.py
Labels: approved, bot is merging ⏳

#502 [14.0] shopfloor_mobile: location_content_transfer get work (frontend)
  shopfloor_mobile/static/wms/src/scenario/location_content_transfer.js
Labels: ready to merge, approved, bot is merging ⏳

#516 [14.0] stock_release_channel: multi warehouse & non SO deliveries
  stock_release_channel/README.rst
  stock_release_channel/models/__init__.py
  stock_release_channel/models/sale_order_line.py
  stock_release_channel/models/stock_move.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/readme/CONTRIBUTORS.rst
  stock_release_channel/views/stock_release_channel_views.xml
Labels: approved, bot is merging ⏳

#530 shopfloor: zp use pack location as sublocation
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: ready to merge, approved, bot is merging ⏳

#538 [14.0] [FIX] shopfloor_rest_log: fix wrong xmlid
  shopfloor_rest_log/views/shopfloor_app.xml
Labels: bot is merging ⏳

#532 shopfloor: do not propagate user_id to backorder
  shopfloor/actions/stock.py
  shopfloor/tests/test_location_content_transfer_set_destination_all.py
Labels: ready to merge, approved, bot is merging ⏳

#531 shopfloor: fix message wrong package scanned
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: approved, bot is merging ⏳

#539 [14.0][FIX] shopfloor: delivery fix sublocation domain
  shopfloor/services/delivery.py
  shopfloor/tests/test_delivery_sublocation.py
Labels: bot is merging ⏳

#441 [14.0] stock_available_to_promise_release: multi-stages of release
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_rule.py
Labels: enhancement, ready to merge, approved, bot is merging ⏳

#546 [14.0][FIX] shopfloor: fix flappy test
  shopfloor/tests/test_delivery_sublocation.py
Labels: bug, approved, bot is merging ⏳

#500 [14.0][ADD] shopfloor_reception
  setup/shopfloor_reception/odoo/addons/shopfloor_reception
  setup/shopfloor_reception/setup.py
  setup/shopfloor_reception_mobile/odoo/addons/shopfloor_reception_mobile
  setup/shopfloor_reception_mobile/setup.py
  shopfloor/__manifest__.py
  shopfloor/actions/data.py
  shopfloor/actions/data_detail.py
  shopfloor/actions/message.py
  shopfloor/actions/schema.py
  shopfloor/tests/common.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor/tests/test_cluster_picking_base.py
  shopfloor/tests/test_cluster_picking_scan_destination_no_prefill_qty.py
  shopfloor/tests/test_cluster_picking_scan_line.py
  shopfloor/tests/test_zone_picking_set_line_destination_pick_pack.py
  shopfloor/views/stock_move_line.xml
  shopfloor_mobile/__manifest__.py
  shopfloor_mobile/static/wms/src/components/misc.js
  shopfloor_mobile/static/wms/src/wms_utils.js
  shopfloor_reception/README.rst
  shopfloor_reception/__init__.py
  shopfloor_reception/__manifest__.py
  shopfloor_reception/data/shopfloor_scenario_data.xml
  shopfloor_reception/demo/shopfloor_menu_demo.xml
  shopfloor_reception/demo/stock_picking_type_demo.xml
  shopfloor_reception/docs/reception_sequence_graph.mermaid
  shopfloor_reception/docs/reception_sequence_graph.png
  shopfloor_reception/models/__init__.py
  shopfloor_reception/models/shopfloor_menu.py
  shopfloor_reception/readme/CONTRIBUTORS.rst
  shopfloor_reception/readme/DESCRIPTION.rst
  shopfloor_reception/readme/ROADMAP.rst
  shopfloor_reception/services/__init__.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/__init__.py
  shopfloor_reception/tests/common.py
  shopfloor_reception/tests/test_manual_selection.py
  shopfloor_reception/tests/test_reception_done.py
  shopfloor_reception/tests/test_select_dest_package.py
  shopfloor_reception/tests/test_select_document.py
  shopfloor_reception/tests/test_select_move.py
  shopfloor_reception/tests/test_set_destination.py
  shopfloor_reception/tests/test_set_lot.py
  shopfloor_reception/tests/test_set_lot_confirm.py
  shopfloor_reception/tests/test_set_quantity.py
  shopfloor_reception/tests/test_set_quantity_action.py
  shopfloor_reception/tests/test_start.py
  shopfloor_reception/views/shopfloor_menu.xml
  shopfloor_reception_mobile/__init__.py
  shopfloor_reception_mobile/__manifest__.py
  shopfloor_reception_mobile/readme/CONTRIBUTORS.rst
  shopfloor_reception_mobile/readme/DESCRIPTION.rst
  shopfloor_reception_mobile/static/src/demo/demo.reception.js
  shopfloor_reception_mobile/static/src/scenario/reception.js
  shopfloor_reception_mobile/templates/assets.xml
Labels: bot is merging ⏳
