Repository OCA/wms, pull requests merged in 2023-04, with the labels that each got.

#507 [14.0][BUG] shopfloor_mobile: fix highlights reactivity in checkout
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/scenario/checkout_states.js
  shopfloor_mobile_base/static/wms/src/components/manual_select.js
  shopfloor_mobile_base/templates/assets.xml
Labels: bug, ready to merge, approved, bot is merging ⏳

#613 [14.0] shopfloor_mobile_base: fix searchbar autofocus pt2
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
Labels: bug, bot is merging ⏳

#619 [14.0][FIX] shopfloor_dangerous_goods_mobile: fix logo
  shopfloor_dangerous_goods_mobile/static/wms/src/css/dangerous_goods.css
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_select.js
Labels: bot is merging ⏳

#616 [IMP] stock_move_source_relocate: Code Refactor
  stock_move_source_relocate/models/stock_move.py
  stock_move_source_relocate/tests/common.py
  stock_move_source_relocate/tests/test_source_relocate.py
Labels: ready to merge, approved, bot is merging ⏳
