Repository OCA/wms, pull requests merged in 2023-03, with the labels that each got.

#576 [14.0] shopfloor_reception: auto post fixes
  shopfloor_reception/README.rst
  shopfloor_reception/readme/CONTRIBUTORS.rst
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_set_destination.py
  shopfloor_reception/tests/test_set_quantity.py
  shopfloor_reception_mobile/static/src/scenario/reception.js
Labels: ready to merge, approved, bot is merging ⏳

#581 [14.0][IMP] shopfloor_reception_mobile: Make states hookable
  shopfloor_reception_mobile/README.rst
  shopfloor_reception_mobile/readme/CONTRIBUTORS.rst
  shopfloor_reception_mobile/static/description/index.html
  shopfloor_reception_mobile/static/src/scenario/reception.js
  shopfloor_reception_mobile/static/src/scenario/reception_states.js
  shopfloor_reception_mobile/templates/assets.xml
Labels: ready to merge, approved, bot is merging ⏳

#558 shopfloor: Add first scan location option on zp
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor/tests/test_zone_picking_select_line_first_scan_location.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: bot is merging ⏳

#556 [14][BACKPORT] stock_available_to_promise add unrelease
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/migrations/14.0.2.0.0/post-migrate.py
  stock_available_to_promise_release/models/stock_location_route.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/models/stock_picking_type.py
  stock_available_to_promise_release/models/stock_rule.py
  stock_available_to_promise_release/readme/USAGE.rst
  stock_available_to_promise_release/security/ir.model.access.csv
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/tests/test_unrelease.py
  stock_available_to_promise_release/tests/test_unrelease_2steps.py
  stock_available_to_promise_release/tests/test_unrelease_3steps.py
  stock_available_to_promise_release/views/stock_location_route_views.xml
  stock_available_to_promise_release/views/stock_picking_type_views.xml
  stock_available_to_promise_release/views/stock_picking_views.xml
  stock_available_to_promise_release/wizards/__init__.py
  stock_available_to_promise_release/wizards/stock_unrelease.py
  stock_available_to_promise_release/wizards/stock_unrelease_views.xml
  stock_available_to_promise_release_dynamic_routing/tests/test_release_dynamic_routing.py
Labels: ready to merge, approved, bot is merging ⏳

#555 [14.0] shopfloor_reception: allow to scan lots
  shopfloor/actions/message.py
  shopfloor/readme/CONTRIBUTORS.rst
  shopfloor/static/description/index.html
  shopfloor_reception/README.rst
  shopfloor_reception/readme/CONTRIBUTORS.rst
  shopfloor_reception/services/reception.py
  shopfloor_reception/static/description/index.html
  shopfloor_reception/tests/test_select_move.py
Labels: bot is merging ⏳

#571 shopfloor_reception: fix picking state after auto-posting
  shopfloor/models/stock_move.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_set_destination.py
Labels: bot is merging ⏳

#544 [14.0] shopfloor_checkout_package_measurement_mobile: change fields order
  shopfloor_checkout_package_measurement_mobile/static/src/scenario/checkout_package_measurement.js
Labels: approved, bot is merging ⏳

#541 [14.0] Add shopfloor_base_multicompany
  setup/shopfloor_base_multicompany/odoo/addons/shopfloor_base_multicompany
  setup/shopfloor_base_multicompany/setup.py
  shopfloor_base_multicompany/README.rst
  shopfloor_base_multicompany/__init__.py
  shopfloor_base_multicompany/__manifest__.py
  shopfloor_base_multicompany/models/__init__.py
  shopfloor_base_multicompany/models/shopfloor_app.py
  shopfloor_base_multicompany/readme/CONTRIBUTORS.rst
  shopfloor_base_multicompany/readme/DESCRIPTION.rst
  shopfloor_base_multicompany/services/__init__.py
  shopfloor_base_multicompany/services/service.py
  shopfloor_base_multicompany/tests/__init__.py
  shopfloor_base_multicompany/tests/test_company_validation.py
  shopfloor_base_multicompany/views/shopfloor_app.xml
Labels: bot is merging ⏳

#545 shopfloor: fix zp set destination qty zero
  shopfloor/actions/message.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
  shopfloor/tests/test_zone_picking_set_line_destination_no_prefill_qty.py
Labels: bot is merging ⏳

#493 [16.0][MIG] stock_release_channel: Migration to 16.0
  .pre-commit-config.yaml
  setup/stock_release_channel/odoo/addons/stock_release_channel
  setup/stock_release_channel/setup.py
  stock_release_channel/README.rst
  stock_release_channel/__manifest__.py
  stock_release_channel/models/__init__.py
  stock_release_channel/models/sale_order_line.py
  stock_release_channel/models/stock_move.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/readme/CONTRIBUTORS.rst
  stock_release_channel/static/description/index.html
  stock_release_channel/static/src/js/progressbar_fractional_widget.js
  stock_release_channel/tests/common.py
  stock_release_channel/tests/test_channel_action.py
  stock_release_channel/tests/test_channel_computed_fields.py
  stock_release_channel/tests/test_channel_release_batch.py
  stock_release_channel/views/assets.xml
  stock_release_channel/views/stock_release_channel_views.xml
Labels: migration, needs review, approved, bot is merging ⏳

#587 [14.0][FIX] shopfloor_checkout_package_measure: validate on done click
  shopfloor_checkout_package_measurement_mobile/static/src/scenario/checkout_package_measurement.js
Labels: bot is merging ⏳

#604 [14.0][FIX] s_a_to_promise_release: fix 14.0.2.0.0 migrate script
  stock_available_to_promise_release/migrations/14.0.2.0.0/post-migrate.py
Labels: bug, bot is merging ⏳

#602 [14.0] shopfloor mobile: misc searchbar fixes
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
  shopfloor_mobile_base/static/wms/src/css/main.css
Labels: ready to merge, approved, bot is merging ⏳

#535 [16.0][MIG] stock_picking_type_shipping_policy
  setup/stock_picking_type_shipping_policy/odoo/addons/stock_picking_type_shipping_policy
  setup/stock_picking_type_shipping_policy/setup.py
  stock_picking_type_shipping_policy/README.rst
  stock_picking_type_shipping_policy/__init__.py
  stock_picking_type_shipping_policy/__manifest__.py
  stock_picking_type_shipping_policy/i18n/es_AR.po
  stock_picking_type_shipping_policy/i18n/es_MX.po
  stock_picking_type_shipping_policy/i18n/stock_picking_type_shipping_policy.pot
  stock_picking_type_shipping_policy/models/__init__.py
  stock_picking_type_shipping_policy/models/stock_move.py
  stock_picking_type_shipping_policy/models/stock_picking_type.py
  stock_picking_type_shipping_policy/readme/CONTRIBUTORS.rst
  stock_picking_type_shipping_policy/readme/CREDITS.rst
  stock_picking_type_shipping_policy/readme/DESCRIPTION.rst
  stock_picking_type_shipping_policy/static/description/icon.png
  stock_picking_type_shipping_policy/static/description/index.html
  stock_picking_type_shipping_policy/tests/__init__.py
  stock_picking_type_shipping_policy/tests/test_stock_picking_type_shipping_policy.py
  stock_picking_type_shipping_policy/views/stock_picking_type.xml
Labels: ready to merge, approved, bot is merging ⏳

#607 shopfloor_mobile: improve qty picker calculation
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.js
Labels: ready to merge, approved, bot is merging ⏳
