Repository OCA/wms, pull requests merged in 2023-09, with the labels that each got.

#736 [16.0][FIX] stock_release_channel: rule domain can be empty
  stock_release_channel/models/stock_release_channel.py
Labels: approved, bot is merging ⏳

#707 [16.0][FIX] stock_available_to_promise_release: add tagged to test
  stock_available_to_promise_release/tests/common.py
Labels: ready to merge, approved, bot is merging ⏳

#704 [16.0][MIG] stock_warehouse_flow: Migration to 16.0
  setup/stock_warehouse_flow/odoo/addons/stock_warehouse_flow
  setup/stock_warehouse_flow/setup.py
  stock_warehouse_flow/README.rst
  stock_warehouse_flow/__init__.py
  stock_warehouse_flow/__manifest__.py
  stock_warehouse_flow/demo/stock_warehouse_flow.xml
  stock_warehouse_flow/i18n/stock_warehouse_flow.pot
  stock_warehouse_flow/models/__init__.py
  stock_warehouse_flow/models/delivery_carrier.py
  stock_warehouse_flow/models/stock_move.py
  stock_warehouse_flow/models/stock_route.py
  stock_warehouse_flow/models/stock_warehouse.py
  stock_warehouse_flow/models/stock_warehouse_flow.py
  stock_warehouse_flow/readme/CONFIGURE.rst
  stock_warehouse_flow/readme/CONTRIBUTORS.rst
  stock_warehouse_flow/readme/DESCRIPTION.rst
  stock_warehouse_flow/readme/ROADMAP.rst
  stock_warehouse_flow/readme/USAGE.rst
  stock_warehouse_flow/security/ir.model.access.csv
  stock_warehouse_flow/static/description/config.png
  stock_warehouse_flow/static/description/flow.png
  stock_warehouse_flow/static/description/icon.png
  stock_warehouse_flow/static/description/index.html
  stock_warehouse_flow/tests/__init__.py
  stock_warehouse_flow/tests/common.py
  stock_warehouse_flow/tests/test_delivery_carrier.py
  stock_warehouse_flow/tests/test_warehouse.py
  stock_warehouse_flow/tests/test_warehouse_flow.py
  stock_warehouse_flow/views/delivery_carrier.xml
  stock_warehouse_flow/views/stock_route.xml
  stock_warehouse_flow/views/stock_warehouse.xml
  stock_warehouse_flow/views/stock_warehouse_flow.xml
Labels: approved, bot is merging ⏳

#737 [16.0][FIX] stock_available_to_promise_release
  stock_available_to_promise_release/models/stock_move.py
Labels: approved, bot is merging ⏳

#741 [FIX] stock_storage_type: fix es translation
  stock_storage_type/i18n/es.po
Labels: bot is merging ⏳

#743 [14.0][FIX] shopfloor, checkout: always select the first picking from scanned package
  shopfloor/services/checkout.py
Labels: bug, approved, bot is merging ⏳

#744 [14.0][FIX] shopfloor_single_product_transfer - set destination before posting
  shopfloor_single_product_transfer/services/single_product_transfer.py
  shopfloor_single_product_transfer/tests/test_set_quantity.py
Labels: approved, bot is merging ⏳

#747 [14.0][FIX] shopfloor: fix scan anything for packaging
  shopfloor/components/scan_handler_product.py
  shopfloor/tests/test_scan_anything.py
Labels: approved, bot is merging ⏳

#496 [MIG][16.0] stock_storage_type_putaway_abc
  .pre-commit-config.yaml
  setup/stock_storage_type_putaway_abc/odoo/addons/stock_storage_type_putaway_abc
  setup/stock_storage_type_putaway_abc/setup.py
  stock_storage_type_putaway_abc/README.rst
  stock_storage_type_putaway_abc/__init__.py
  stock_storage_type_putaway_abc/__manifest__.py
  stock_storage_type_putaway_abc/i18n/es_AR.po
  stock_storage_type_putaway_abc/i18n/stock_storage_type_putaway_abc.pot
  stock_storage_type_putaway_abc/models/__init__.py
  stock_storage_type_putaway_abc/models/product_template.py
  stock_storage_type_putaway_abc/models/stock_location.py
  stock_storage_type_putaway_abc/readme/CONTRIBUTORS.rst
  stock_storage_type_putaway_abc/readme/DESCRIPTION.rst
  stock_storage_type_putaway_abc/static/description/icon.png
  stock_storage_type_putaway_abc/static/description/index.html
  stock_storage_type_putaway_abc/tests/__init__.py
  stock_storage_type_putaway_abc/tests/test_abc_location.py
  stock_storage_type_putaway_abc/views/product.xml
  stock_storage_type_putaway_abc/views/stock_location.xml
Labels: migration, work in progress, ready to merge, approved, bot is merging ⏳, stale

#734 [14.0][FIX] shopfloor: fix bug in checkout if there are two lines with the same article
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_scan_package_action_no_prefill_qty.py
Labels: approved, bot is merging ⏳

#756 [14.0] shopfloor: update checkout sequence diagram
  shopfloor/docs/checkout_diag_seq.plantuml
  shopfloor/docs/checkout_diag_seq.png
Labels: bot is merging ⏳
