Repository OCA/wms, pull requests merged in 2023-06, with the labels that each got.

#639 [14.0][IMP] shopfloor: scenario location content transfer
  shopfloor/services/location_content_transfer.py
Labels: bot is merging ⏳

#525 [14.0] shopfloor: checkout prevent to take more than planned
  shopfloor/actions/message.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_list_package.py
  shopfloor/tests/test_checkout_new_package.py
  shopfloor/tests/test_checkout_no_package.py
  shopfloor/tests/test_checkout_set_qty.py
Labels: approved, bot is merging ⏳

#644 [16.0][IMP] stock_release_channel
  stock_release_channel/views/stock_picking_views.xml
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#651 [16.0][IMP] - stock_release_channel: add partners as selection criteria
  stock_release_channel/__manifest__.py
  stock_release_channel/models/__init__.py
  stock_release_channel/models/res_partner.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/__init__.py
  stock_release_channel/tests/test_release_channel_partner.py
  stock_release_channel/views/res_partner.xml
  stock_release_channel/views/stock_release_channel_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#640 [14.0] shopfloor_single_product_transfer 2.0
  setup/shopfloor_single_product_transfer_force_package/odoo/addons/shopfloor_single_product_transfer_force_package
  setup/shopfloor_single_product_transfer_force_package/setup.py
  shopfloor/actions/message.py
  shopfloor_single_product_transfer/services/single_product_transfer.py
  shopfloor_single_product_transfer/tests/__init__.py
  shopfloor_single_product_transfer/tests/common.py
  shopfloor_single_product_transfer/tests/test_scan_location.py
  shopfloor_single_product_transfer/tests/test_scan_location_or_package.py
  shopfloor_single_product_transfer/tests/test_scan_product.py
  shopfloor_single_product_transfer/tests/test_set_location.py
  shopfloor_single_product_transfer/tests/test_set_quantity.py
  shopfloor_single_product_transfer/tests/test_start.py
  shopfloor_single_product_transfer_force_package/README.rst
  shopfloor_single_product_transfer_force_package/__init__.py
  shopfloor_single_product_transfer_force_package/__manifest__.py
  shopfloor_single_product_transfer_force_package/readme/CONTRIBUTORS.rst
  shopfloor_single_product_transfer_force_package/readme/DESCRIPTION.rst
  shopfloor_single_product_transfer_force_package/services/__init__.py
  shopfloor_single_product_transfer_force_package/services/single_product_transfer.py
  shopfloor_single_product_transfer_force_package/tests/__init__.py
  shopfloor_single_product_transfer_force_package/tests/test_force_package.py
  shopfloor_single_product_transfer_mobile/static/src/scenario/single_product_transfer.js
Labels: ready to merge, approved, bot is merging ⏳

#536 [14.0][IMP] Shopfloor zone picking minimize concurent work problem
  shopfloor/actions/stock.py
  shopfloor/exceptions.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
Labels: bot is merging ⏳

#653 [16.0][FIX] stock_release_channel: Fix test
  stock_release_channel/tests/test_assign_job.py
Labels: bot is merging ⏳

#623 [14.0][IMP] shopfloor: zone_picking scan location or pack first
  shopfloor/actions/message.py
  shopfloor/actions/move_line_search.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor/tests/test_zone_picking_select_line_first_scan_location.py
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: approved, bot is merging ⏳

#637 [14.0] shopfloor_single_pack_transfer: display all products in pack
  shopfloor/services/single_pack_transfer.py
  shopfloor/tests/test_single_pack_transfer.py
  shopfloor_mobile/static/wms/src/scenario/single_pack_transfer.js
Labels: bot is merging ⏳

#650 [14.0] stock_picking_consolidation_priority: prioritize moves
  stock_picking_consolidation_priority/models/stock_move.py
Labels: bot is merging ⏳

#609 [16.0][IMP] stock_available_to_promise_release: Remove unused fields
  stock_available_to_promise_release/__init__.py
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/hooks.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/views/stock_move_views.xml
  stock_available_to_promise_release/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#646 [14.0][IMP] shopfloor: change zone picking option restriction
  shopfloor/models/shopfloor_menu.py
Labels: bot is merging ⏳

#656 [14.0][FIX] shopfloor_checkout: fix bugs in checkout scenario
  shopfloor/actions/message.py
  shopfloor/services/checkout.py
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: bot is merging ⏳

#649 [14.0] shopfloor_delivery_shipment: some improvements to load trucks
  shopfloor_delivery_shipment/actions/data.py
  shopfloor_delivery_shipment/actions/schema.py
  shopfloor_delivery_shipment/services/delivery_shipment.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_base.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_dock.py
  shopfloor_delivery_shipment_mobile/static/wms/src/scenario/delivery_shipment.js
Labels: approved, bot is merging ⏳

#595 [14.0][IMP] stock_release_channel with lifecycle
  stock_release_channel/__manifest__.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/readme/CONTRIBUTORS.rst
  stock_release_channel/readme/USAGE.rst
  stock_release_channel/tests/__init__.py
  stock_release_channel/tests/common.py
  stock_release_channel/tests/test_release_channel_lifecycle.py
  stock_release_channel/views/stock_release_channel_views.xml
Labels: approved
