Repository OCA/wms, pull requests merged in 2023-11, with the labels that each got.

#647 [14.0][ADD] shopfloor_reception_packaging_dimension
  setup/shopfloor_reception_packaging_dimension/odoo/addons/shopfloor_reception_packaging_dimension
  setup/shopfloor_reception_packaging_dimension/setup.py
  setup/shopfloor_reception_packaging_dimension_mobile/odoo/addons/shopfloor_reception_packaging_dimension_mobile
  setup/shopfloor_reception_packaging_dimension_mobile/setup.py
  shopfloor/actions/data_detail.py
  shopfloor/actions/message.py
  shopfloor/actions/schema_detail.py
  shopfloor/tests/test_actions_data_base.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_reception/docs/reception_sequence_graph.mermaid
  shopfloor_reception/services/reception.py
  shopfloor_reception_packaging_dimension/__init__.py
  shopfloor_reception_packaging_dimension/__manifest__.py
  shopfloor_reception_packaging_dimension/hooks.py
  shopfloor_reception_packaging_dimension/models/__init__.py
  shopfloor_reception_packaging_dimension/models/shopfloor_menu.py
  shopfloor_reception_packaging_dimension/readme/CONTRIBUTORS.rst
  shopfloor_reception_packaging_dimension/readme/DESCRIPTION.rst
  shopfloor_reception_packaging_dimension/services/__init__.py
  shopfloor_reception_packaging_dimension/services/reception.py
  shopfloor_reception_packaging_dimension/tests/__init__.py
  shopfloor_reception_packaging_dimension/tests/test_set_package_dimension.py
  shopfloor_reception_packaging_dimension/views/shopfloor_menu.xml
  shopfloor_reception_packaging_dimension_mobile/README.rst
  shopfloor_reception_packaging_dimension_mobile/__init__.py
  shopfloor_reception_packaging_dimension_mobile/__manifest__.py
  shopfloor_reception_packaging_dimension_mobile/readme/CONTRIBUTORS.rst
  shopfloor_reception_packaging_dimension_mobile/readme/DESCRIPTION.rst
  shopfloor_reception_packaging_dimension_mobile/static/src/scenario/reception_packaging_dimension.js
  shopfloor_reception_packaging_dimension_mobile/templates/assets.xml
Labels: approved, bot is merging ⏳

#699 [14.0][IMP] stock_release_channel: refactor compute count
  stock_release_channel/README.rst
  stock_release_channel/__manifest__.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/readme/CONTRIBUTORS.rst
  stock_release_channel/static/description/index.html
Labels: ready to merge, approved, bot is merging ⏳

#769 [IMP] stock_available_to_promise_release: Make previous sql hookable
  stock_available_to_promise_release/models/stock_move.py
Labels: bot is merging ⏳

#774 [16.0][IMP] stock_release_channel_cutoff: Release channel cutoff warn…
  stock_release_channel_cutoff/models/stock_release_channel.py
Labels: ready to merge, approved, bot is merging ⏳

#766 [16.0][FIX] stock_release_channel: Allow to see inactive partners
  stock_release_channel/models/stock_release_channel.py
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#779 [16.0][FIX] stock_release_channel: Ensure moves still exist after release
  stock_release_channel/models/stock_move.py
Labels: bot is merging ⏳

#776 [14.0][FIX] shopfloor: checkout fix line done with zero qty
  shopfloor/services/checkout.py
Labels: bot is merging ⏳

#745 [14.0][FIX] stock_dynamic_routing: merge moves
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/test_unrelease_merged_moves.py
  stock_available_to_promise_release_dynamic_routing/__init__.py
  stock_available_to_promise_release_dynamic_routing/__manifest__.py
  stock_available_to_promise_release_dynamic_routing/models/__init__.py
  stock_available_to_promise_release_dynamic_routing/models/stock_move.py
  stock_available_to_promise_release_dynamic_routing/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#731 [16.0][FIX] stock_storage_type: Now quants (recordset) is passed to conditions
  stock_storage_type/models/stock_storage_location_sequence_cond.py
  stock_storage_type/tests/test_storage_type_putaway_strategy.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#784 [16.0][FIX] stock_storage_type: v16 migration - fix quants for product put-away
  stock_storage_type/__manifest__.py
  stock_storage_type/models/stock_location.py
Labels: enhancement, bot is merging ⏳

#781 [14.0][FIX] Disable unit tests from shopfloor_ui_tests
  .github/workflows_disabled/ui-unit-tests.yml
  shopfloor_ui_tests/README.rst
Labels: bot is merging ⏳

#767 [14.0][FIX] shopfloor_mobile_base: fix searchbar focus
  shopfloor_mobile/static/wms/src/scenario/cluster_picking.js
  shopfloor_mobile/static/wms/src/scenario/location_content_transfer.js
  shopfloor_mobile/static/wms/src/scenario/single_pack_transfer.js
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
  shopfloor_mobile_base/static/wms/src/components/searchbar/searchbar.js
Labels: bot is merging ⏳

#780 [14.0][FIX] shopfloor: checkout fix asking destination location
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_done.py
Labels: approved, bot is merging ⏳

#773 [16.0][FW] [14.0][IMP] stock_warehouse_flow: assign_picking only if needed
  stock_warehouse_flow/models/stock_move.py
  stock_warehouse_flow/models/stock_warehouse_flow.py
Labels: bot is merging ⏳

#758 [14.0][FIX] shopfloor_single_product_transfer: check package
  shopfloor_single_product_transfer/README.rst
  shopfloor_single_product_transfer/readme/CONTRIBUTORS.rst
  shopfloor_single_product_transfer/services/single_product_transfer.py
  shopfloor_single_product_transfer/static/description/index.html
  shopfloor_single_product_transfer/tests/common.py
  shopfloor_single_product_transfer/tests/test_scan_location_or_package.py
  shopfloor_single_product_transfer/tests/test_set_location.py
  shopfloor_single_product_transfer/tests/test_set_quantity.py
  shopfloor_single_product_transfer_force_package/README.rst
  shopfloor_single_product_transfer_force_package/readme/CONTRIBUTORS.rst
  shopfloor_single_product_transfer_force_package/services/single_product_transfer.py
  shopfloor_single_product_transfer_force_package/static/description/index.html
  shopfloor_single_product_transfer_force_package/tests/test_force_package.py
  shopfloor_single_product_transfer_unique_order_at_location/README.rst
  shopfloor_single_product_transfer_unique_order_at_location/readme/CONTRIBUTORS.rst
  shopfloor_single_product_transfer_unique_order_at_location/services/single_product_transfer.py
  shopfloor_single_product_transfer_unique_order_at_location/static/description/index.html
Labels: ready to merge, approved, bot is merging ⏳

#764 [16.0][FIX] stock_release_channel_process_end_time: exclude the done & cancel pickings for release expected date
  stock_release_channel_process_end_time/models/stock_picking.py
Labels: bot is merging ⏳

#754 [14.0][FIX] shopfloor_delivery: Disallow selecting done/cancel pickings
  shopfloor/services/delivery.py
  shopfloor/tests/test_delivery_list_stock_picking.py
Labels: approved, bot is merging ⏳

#753 [16.0][ADD] stock_release_channel_partner_delivery_window
  setup/stock_release_channel_partner_delivery_window/odoo/addons/stock_release_channel_partner_delivery_window
  setup/stock_release_channel_partner_delivery_window/setup.py
  stock_release_channel_partner_delivery_window/README.rst
  stock_release_channel_partner_delivery_window/__init__.py
  stock_release_channel_partner_delivery_window/__manifest__.py
  stock_release_channel_partner_delivery_window/models/__init__.py
  stock_release_channel_partner_delivery_window/models/stock_picking.py
  stock_release_channel_partner_delivery_window/models/stock_release_channel.py
  stock_release_channel_partner_delivery_window/readme/CONTRIBUTORS.rst
  stock_release_channel_partner_delivery_window/readme/CREDITS.rst
  stock_release_channel_partner_delivery_window/readme/DESCRIPTION.rst
  stock_release_channel_partner_delivery_window/readme/USAGE.rst
  stock_release_channel_partner_delivery_window/static/description/icon.png
  stock_release_channel_partner_delivery_window/static/description/index.html
  stock_release_channel_partner_delivery_window/tests/__init__.py
  stock_release_channel_partner_delivery_window/tests/test_release_window.py
  stock_release_channel_partner_delivery_window/views/stock_release_channel_view.xml
Labels: approved, bot is merging ⏳

#778 [14.0] shopfloor: fix progress computation
  shopfloor/actions/data.py
  shopfloor/tests/test_actions_data.py
Labels: approved, bot is merging ⏳

#688 [14.0][IMP] shopfloor_delivery_shipment_mobile: have long package name fit on one line
  shopfloor_delivery_shipment_mobile/static/wms/src/scenario/delivery_shipment.js
  shopfloor_mobile_base/static/wms/src/components/detail/detail_card.js
  shopfloor_mobile_base/static/wms/src/css/main.css
Labels: ready to merge, approved, bot is merging ⏳

#717 [14.0][IMP] shopfloor_reception improve confirmation
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_return_scan_line.py
  shopfloor_reception/tests/test_return_set_quantity.py
  shopfloor_reception/tests/test_select_move.py
  shopfloor_reception/tests/test_set_lot_confirm.py
  shopfloor_reception/tests/test_set_quantity.py
  shopfloor_reception_mobile/static/src/scenario/reception_states.js
  shopfloor_reception_packaging_dimension/tests/test_set_package_dimension.py
Labels: ready to merge, approved, bot is merging ⏳

#716 [14.0][IMP] shopfloor improve confirmation
  shopfloor/docs/single_pack_transfer_diag_seq.plantuml
  shopfloor/docs/single_pack_transfer_diag_seq.png
  shopfloor/services/cluster_picking.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/single_pack_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/common.py
  shopfloor/tests/test_cluster_picking_unload.py
  shopfloor/tests/test_location_content_transfer_base.py
  shopfloor/tests/test_location_content_transfer_set_destination_all.py
  shopfloor/tests/test_location_content_transfer_set_destination_package_or_line.py
  shopfloor/tests/test_single_pack_transfer.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_complete_mix_pack_flux.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
  shopfloor/tests/test_zone_picking_set_line_destination_package_not_allowed.py
  shopfloor/tests/test_zone_picking_set_line_destination_pick_pack.py
  shopfloor/tests/test_zone_picking_unload_all.py
  shopfloor/tests/test_zone_picking_unload_set_destination.py
  shopfloor_checkout_sync/tests/test_shopfloor_zone_picking_sync.py
  shopfloor_mobile/static/wms/src/scenario/cluster_picking.js
  shopfloor_mobile/static/wms/src/scenario/location_content_transfer.js
  shopfloor_mobile/static/wms/src/scenario/single_pack_transfer.js
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: bot is merging ⏳

#725 [14.0][IMP] shopfloor checkout scan delivery package
  shopfloor/actions/message.py
  shopfloor/docs/checkout_diag_seq.plantuml
  shopfloor/docs/checkout_diag_seq.png
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_scan_line.py
  shopfloor/tests/test_checkout_scan_line_no_prefill_qty.py
  shopfloor_mobile/static/wms/src/scenario/checkout_states.js
Labels: ready to merge, approved, bot is merging ⏳

#748 [14.0][IMP] shopfloor: imp cancel line/package in location content transfer
  shopfloor/services/location_content_transfer.py
  shopfloor/tests/test_location_content_transfer_single.py
Labels: bot is merging ⏳

#742 [14.0][FIX] sf_single_product_transfer: fix backorder responsible
  shopfloor_single_product_transfer/services/single_product_transfer.py
  shopfloor_single_product_transfer/tests/test_set_quantity.py
Labels: bot is merging ⏳
