Repository OCA/wms, pull requests merged in 2023-08, with the labels that each got.

#708 [14.0] shopfloor_mobile: display only qty reserved for picking in picking-detail
  shopfloor_mobile/static/wms/src/components/detail/detail_transfer.js
Labels: approved, bot is merging ⏳

#705 [14.0][FIX] stock_warehouse_flow: fix RollbackException on write
  stock_warehouse_flow/models/stock_warehouse_flow.py
Labels: approved, bot is merging ⏳

#685 [14.0] sf_dangerous_goods_mobile: fix icon display w/ mixed packages
  shopfloor_dangerous_goods_mobile/static/wms/src/components/picking_select.js
  shopfloor_dangerous_goods_mobile/static/wms/src/js/demo/demo.checkout.js
  shopfloor_mobile/static/wms/src/wms_utils.js
Labels: ready to merge, approved, bot is merging ⏳

#537 [16.0][FIX] stock_dynamic_routing: Fix stock routing view
  stock_dynamic_routing/models/stock_routing.py
  stock_dynamic_routing/views/stock_routing_views.xml
Labels: bug, bot is merging ⏳, stale

#729 [14.0][FIX] shopfloor fix zone picking scan empty package
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: approved, bot is merging ⏳

#724 [14.0][FIX] shopfloor zone picking set destination package concurent update
  shopfloor/services/zone_picking.py
Labels: bot is merging ⏳

#722 [14.0][PERF] dynamic routing
  stock_dynamic_routing/__manifest__.py
  stock_dynamic_routing/models/stock_move.py
  stock_dynamic_routing/models/stock_picking.py
  stock_dynamic_routing/tests/test_routing_pull.py
  stock_move_source_relocate/__manifest__.py
  stock_move_source_relocate/models/stock_move.py
  stock_move_source_relocate/readme/CONTRIBUTORS.rst
  stock_move_source_relocate_dynamic_routing/__manifest__.py
  stock_move_source_relocate_dynamic_routing/models/stock_move.py
  stock_move_source_relocate_dynamic_routing/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#723 [14.0][FIX] stock_storage_type: debug log
  stock_storage_type/__manifest__.py
  stock_storage_type/models/stock_location.py
Labels: bot is merging ⏳

#682 [14.0][IMP] stock_warehouse_flow: assign_picking only if needed
  stock_warehouse_flow/README.rst
  stock_warehouse_flow/models/stock_move.py
  stock_warehouse_flow/models/stock_warehouse_flow.py
  stock_warehouse_flow/static/description/index.html
  stock_warehouse_flow_release/README.rst
  stock_warehouse_flow_release/static/description/index.html
  stock_warehouse_flow_release/tests/test_warehouse_flow_release.py
Labels: bot is merging ⏳

#719 [14.0][IMP] shopfloor: do not compute move_line_count by default for package data
  shopfloor/actions/data.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_list_package.py
  shopfloor_dangerous_goods/tests/test_actions_data.py
Labels: ready to merge, approved, bot is merging ⏳

#690 [14.0] shopfloor_reception: prevent creating lines with negative demand
  shopfloor/models/stock_move_line.py
  shopfloor_reception/services/reception.py
Labels: approved, bot is merging ⏳

#664 [14.0][IMP] shopfloor delivery shipment filter by location
  shopfloor/actions/message.py
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.plantuml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.png
  shopfloor_delivery_shipment/services/delivery_shipment.py
  shopfloor_delivery_shipment/tests/__init__.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_base.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_location.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_product.py
  shopfloor_delivery_shipment_mobile/static/wms/src/scenario/delivery_shipment.js
Labels: bot is merging ⏳

#605 [14.0][ADD] shopfloor_reception_purchase_partner_ref
  setup/shopfloor_purchase_base/odoo/addons/shopfloor_purchase_base
  setup/shopfloor_purchase_base/setup.py
  setup/shopfloor_reception_purchase_partner_ref/odoo/addons/shopfloor_reception_purchase_partner_ref
  setup/shopfloor_reception_purchase_partner_ref/setup.py
  setup/shopfloor_reception_purchase_partner_ref_mobile/odoo/addons/shopfloor_reception_purchase_partner_ref_mobile
  setup/shopfloor_reception_purchase_partner_ref_mobile/setup.py
  shopfloor/actions/data.py
  shopfloor_purchase_base/README.rst
  shopfloor_purchase_base/__init__.py
  shopfloor_purchase_base/__manifest__.py
  shopfloor_purchase_base/actions/__init__.py
  shopfloor_purchase_base/actions/data.py
  shopfloor_purchase_base/actions/schema.py
  shopfloor_purchase_base/readme/CONTRIBUTORS.rst
  shopfloor_purchase_base/readme/DESCRIPTION.rst
  shopfloor_purchase_base/static/description/icon.png
  shopfloor_purchase_base/static/description/index.html
  shopfloor_purchase_base/tests/__init__.py
  shopfloor_purchase_base/tests/test_actions_data.py
  shopfloor_reception/services/reception.py
  shopfloor_reception_purchase_partner_ref/README.rst
  shopfloor_reception_purchase_partner_ref/__init__.py
  shopfloor_reception_purchase_partner_ref/__manifest__.py
  shopfloor_reception_purchase_partner_ref/readme/CONTRIBUTORS.rst
  shopfloor_reception_purchase_partner_ref/readme/DESCRIPTION.rst
  shopfloor_reception_purchase_partner_ref/services/__init__.py
  shopfloor_reception_purchase_partner_ref/services/reception.py
  shopfloor_reception_purchase_partner_ref/static/description/index.html
  shopfloor_reception_purchase_partner_ref/tests/__init__.py
  shopfloor_reception_purchase_partner_ref/tests/test_data.py
  shopfloor_reception_purchase_partner_ref_mobile/README.rst
  shopfloor_reception_purchase_partner_ref_mobile/__init__.py
  shopfloor_reception_purchase_partner_ref_mobile/__manifest__.py
  shopfloor_reception_purchase_partner_ref_mobile/readme/CONTRIBUTORS.rst
  shopfloor_reception_purchase_partner_ref_mobile/readme/DESCRIPTION.rst
  shopfloor_reception_purchase_partner_ref_mobile/static/description/index.html
  shopfloor_reception_purchase_partner_ref_mobile/static/src/scenario/reception.js
  shopfloor_reception_purchase_partner_ref_mobile/templates/assets.xml
Labels: ready to merge, approved, bot is merging ⏳

#720 [14.0][IMP] shopfloor: zone picking is package not valid
  shopfloor/actions/message.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
Labels: ready to merge, approved, bot is merging ⏳

#622 [14.0] shopfloor_checkout: show full list of products after select_line
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_scan_line.py
  shopfloor/tests/test_checkout_select_package_base.py
  shopfloor_packing_info/tests/test_checkout_scan_line.py
Labels: bot is merging ⏳

#661 [14.0] shopfloor zone_picking: block scanning of destination packages
  shopfloor/__manifest__.py
  shopfloor/actions/message.py
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/migrations/14.0.4.0.0/post-migration.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_base.py
  shopfloor/tests/test_zone_picking_set_line_destination_package_not_allowed.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: bot is merging ⏳

#730 [14.0][FIX] stock_available_to_promise_release: fix schedule date change
  stock_available_to_promise_release/models/stock_picking.py
Labels: bot is merging ⏳

#709 [14][IMP] shopfloor_delivery_shipment improve confirmation of shipment creation
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.plantuml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.png
  shopfloor_delivery_shipment/services/delivery_shipment.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_base.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_dock.py
  shopfloor_delivery_shipment_mobile/static/wms/src/scenario/delivery_shipment.js
Labels: bot is merging ⏳

#727 [14.0][IMP] shopfloor zone picking improve select_line endpoint/state
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_select_line_no_prefill_qty.py
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: ready to merge, approved, bot is merging ⏳

#733 [14.0][FIX] shopfloor_delivery_shipment: fix bug in move lines domain
  shopfloor_delivery_shipment/services/delivery_shipment.py
Labels: approved, bot is merging ⏳
