Repository OCA/wms, pull requests merged in 2023-02, with the labels that each got.

#553 [14.0] Update pre-commit conf
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
Labels: needs review

#554 [14.0] shopfloor_reception: exclude view locations from scan
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_set_quantity.py
Labels: approved, bot is merging ⏳

#562 [14.0] shopfloor: checkout use search.find
  shopfloor/services/checkout.py
Labels: bot is merging ⏳

#557 [14.0] shopfloor_reception: fix test_done_action
  shopfloor_reception/tests/test_select_move.py
Labels: bug, approved, bot is merging ⏳

#565 [UPD] Copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#510 [MIG][16.0] stock_picking_completion_info
  setup/stock_picking_completion_info/odoo/addons/stock_picking_completion_info
  setup/stock_picking_completion_info/setup.py
  stock_picking_completion_info/README.rst
  stock_picking_completion_info/__init__.py
  stock_picking_completion_info/__manifest__.py
  stock_picking_completion_info/i18n/stock_picking_completion_info.pot
  stock_picking_completion_info/models/__init__.py
  stock_picking_completion_info/models/stock_picking.py
  stock_picking_completion_info/readme/CONTRIBUTORS.rst
  stock_picking_completion_info/readme/DESCRIPTION.rst
  stock_picking_completion_info/static/description/icon.png
  stock_picking_completion_info/static/description/index.html
  stock_picking_completion_info/tests/__init__.py
  stock_picking_completion_info/tests/test_stock_picking_completion_info.py
  stock_picking_completion_info/views/stock_picking.xml
Labels: migration, needs review, bot is merging ⏳

#548 [FIX] - stock_dynamic_routing: fix method params
  stock_dynamic_routing/models/stock_move.py
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#561 shopfloor: fix location content transfer lines selected
  shopfloor/services/location_content_transfer.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_location_content_transfer_scan_location.py
Labels: bug, approved, bot is merging ⏳

#549 [14.0] shopfloor: checkout allow pack all lines at once
  shopfloor/actions/message.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_cancel_line.py
  shopfloor/tests/test_checkout_list_package.py
  shopfloor/tests/test_checkout_new_package.py
  shopfloor/tests/test_checkout_no_package.py
  shopfloor/tests/test_checkout_scan.py
  shopfloor/tests/test_checkout_scan_line.py
  shopfloor/tests/test_checkout_scan_package_action.py
  shopfloor/tests/test_checkout_select.py
  shopfloor/tests/test_checkout_select_line.py
  shopfloor_mobile/static/wms/src/scenario/checkout_states.js
Labels: bot is merging ⏳

#568 [14.0] shopfloor: use search.find for scan handlers
  shopfloor/actions/search.py
  shopfloor/components/scan_handler_location.py
  shopfloor/components/scan_handler_lot.py
  shopfloor/components/scan_handler_package.py
  shopfloor/components/scan_handler_product.py
  shopfloor/components/scan_handler_transfer.py
Labels: approved, bot is merging ⏳

#570 [14.0] shopfloor, checkout: use 'validate_moves' helper in 'done' endpoint
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_done.py
Labels: approved, bot is merging ⏳

#529 [14.0] shopfloor: cluster_picking full bin action opt-out
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/cluster_picking.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_mobile/static/wms/src/demo/demo.cluster_picking.js
  shopfloor_mobile/static/wms/src/scenario/cluster_picking.js
Labels: bot is merging ⏳

#563 [14.0][FIX] shopfloor: fix zone picking package as substitue on lines
  shopfloor/services/zone_picking.py
Labels: approved, bot is merging ⏳

#575 [14.0][IMP] shopfloor: location content transfer find_work multiple user
  shopfloor/README.rst
  shopfloor/readme/CONTRIBUTORS.rst
  shopfloor/services/cluster_picking.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/zone_picking.py
  shopfloor/static/description/index.html
  shopfloor_base/README.rst
  shopfloor_base/actions/__init__.py
  shopfloor_base/actions/lock.py
  shopfloor_base/readme/CONTRIBUTORS.rst
  shopfloor_base/static/description/index.html
  shopfloor_batch_automatic_creation/actions/picking_batch_auto_create.py
Labels: approved, bot is merging ⏳

#578 [14.0] shopfloor: cluster picking fix action done
  shopfloor/services/cluster_picking.py
Labels: bot is merging ⏳

#542 [14.0] shopfloor_mobile_base_auth_user: fix login keyboard bug
  shopfloor_mobile_base/static/wms/src/css/main.css
  shopfloor_mobile_base_auth_user/static/wms/src/login.js
Labels: bot is merging ⏳

#579 [14.0] shopfloor: fix search
  shopfloor/actions/search.py
  shopfloor/tests/test_actions_search.py
  shopfloor/tests/test_scan_anything.py
Labels: bug, bot is merging ⏳

#580 [14.0] shopfloor_mobile: Add hooks in picking detail scenarios
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_select.js
Labels: bot is merging ⏳

#582 [14.0] shopfloor_mobile: improve list-item action handling
  shopfloor_mobile_base/static/wms/src/components/list.js
Labels: bot is merging ⏳

#583 [14.0] shopfloor: checkout add show_oneline_package_content option
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_select.js
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: approved, bot is merging ⏳

#334 [14.0][MIG] shopfloor_dangerous_goods
  setup/shopfloor_dangerous_goods/odoo/addons/shopfloor_dangerous_goods
  setup/shopfloor_dangerous_goods/setup.py
  setup/shopfloor_dangerous_goods_mobile/odoo/addons/shopfloor_dangerous_goods_mobile
  setup/shopfloor_dangerous_goods_mobile/setup.py
  shopfloor_dangerous_goods/README.rst
  shopfloor_dangerous_goods/__init__.py
  shopfloor_dangerous_goods/__manifest__.py
  shopfloor_dangerous_goods/actions/__init__.py
  shopfloor_dangerous_goods/actions/data.py
  shopfloor_dangerous_goods/actions/schema.py
  shopfloor_dangerous_goods/readme/CONTRIBUTORS.rst
  shopfloor_dangerous_goods/readme/DESCRIPTION.rst
  shopfloor_dangerous_goods/static/description/index.html
  shopfloor_dangerous_goods/tests/__init__.py
  shopfloor_dangerous_goods/tests/test_actions_data.py
  shopfloor_dangerous_goods_mobile/README.rst
  shopfloor_dangerous_goods_mobile/__init__.py
  shopfloor_dangerous_goods_mobile/__manifest__.py
  shopfloor_dangerous_goods_mobile/readme/CONTRIBUTORS.rst
  shopfloor_dangerous_goods_mobile/readme/DESCRIPTION.rst
  shopfloor_dangerous_goods_mobile/static/description/icon.png
  shopfloor_dangerous_goods_mobile/static/description/index.html
  shopfloor_dangerous_goods_mobile/static/wms/src/components/picking_select.js
  shopfloor_dangerous_goods_mobile/static/wms/src/css/dangerous_goods.css
  shopfloor_dangerous_goods_mobile/static/wms/src/css/limited_quantity_label.png
  shopfloor_dangerous_goods_mobile/templates/assets.xml
Labels: migration, ready to merge, approved, bot is merging ⏳, no stale

#584 [14.0][IMP] shopfloor: find_work
  shopfloor/services/location_content_transfer.py
Labels: approved, bot is merging ⏳

#585 [14.0][FIX] shopfloor: fix zone picking package as substitue on lines
  shopfloor/services/zone_picking.py
Labels: bug, bot is merging ⏳
