Repository OCA/wms, pull requests merged in 2023-07, with the labels that each got.

#663 [14.0] shopfloor_single_product_transfer: show message if line already done
  shopfloor_single_product_transfer/services/single_product_transfer.py
  shopfloor_single_product_transfer/tests/test_set_quantity.py
Labels: ready to merge, approved, bot is merging ⏳

#612 [14.0][FIX] shopfoor_mobile: fix checkout line selection
  shopfloor_mobile/static/wms/src/components/scenario_picking_detail/picking_select.js
Labels: bug, approved, bot is merging ⏳

#652 [14.0] shopfloor_delivery_shipment: some improvements to load trucks frontend
  shopfloor_delivery_shipment_mobile/static/wms/src/scenario/delivery_shipment.js
Labels: bot is merging ⏳

#670 [14.0] shopfloor single_pack_transfer: display weight in package info card
  shopfloor/services/single_pack_transfer.py
  shopfloor/tests/test_single_pack_transfer.py
  shopfloor_mobile/static/wms/src/scenario/single_pack_transfer.js
Labels: ready to merge, approved, bot is merging ⏳

#671 [IMP] shopfloor_reception_mobile: Make display values hookable
  shopfloor_reception_mobile/static/src/scenario/reception.js
Labels: ready to merge, approved, bot is merging ⏳

#617 [14.0][FIX] stock_release_channel: _pickings_sort_key
  stock_release_channel/models/stock_release_channel.py
Labels: ready to merge, approved, bot is merging ⏳

#633 [14.0] shopfloor_mobile_base: fix headers extension
  shopfloor_mobile_base/static/wms/src/main.js
Labels: bot is merging ⏳

#686 [14.0][FIX] stock_available_to_promise_release 16 backport
  stock_available_to_promise_release/views/stock_picking_type_views.xml
Labels: bot is merging ⏳

#675 [14.0][IMP] shopfloor checkout add restrict scan barcode option
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_done.py
  shopfloor/tests/test_checkout_scan.py
  shopfloor/tests/test_checkout_summary.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_base/models/shopfloor_menu.py
  shopfloor_base/views/shopfloor_menu.xml
  shopfloor_mobile/static/wms/src/scenario/checkout_states.js
Labels: ready to merge, approved, bot is merging ⏳

#603 [ADD][14.0] stock_unique_order_per_location + shopfloor_single_product_transfer_unique_order_at_location
  setup/shopfloor_single_product_transfer_unique_order_at_location/odoo/addons/shopfloor_single_product_transfer_unique_order_at_location
  setup/shopfloor_single_product_transfer_unique_order_at_location/setup.py
  setup/stock_unique_order_per_location/odoo/addons/stock_unique_order_per_location
  setup/stock_unique_order_per_location/setup.py
  shopfloor_single_product_transfer_unique_order_at_location/__init__.py
  shopfloor_single_product_transfer_unique_order_at_location/__manifest__.py
  shopfloor_single_product_transfer_unique_order_at_location/readme/CONTRIBUTORS.rst
  shopfloor_single_product_transfer_unique_order_at_location/readme/DESCRIPTION.rst
  shopfloor_single_product_transfer_unique_order_at_location/services/__init__.py
  shopfloor_single_product_transfer_unique_order_at_location/services/single_product_transfer.py
  shopfloor_single_product_transfer_unique_order_at_location/tests/__init__.py
  shopfloor_single_product_transfer_unique_order_at_location/tests/test_set_quantity.py
  stock_unique_order_per_location/__init__.py
  stock_unique_order_per_location/__manifest__.py
  stock_unique_order_per_location/models/__init__.py
  stock_unique_order_per_location/models/stock_move_line.py
  stock_unique_order_per_location/models/stock_picking_type.py
  stock_unique_order_per_location/readme/CONTRIBUTORS.rst
  stock_unique_order_per_location/readme/DESCRIPTION.rst
  stock_unique_order_per_location/tests/__init__.py
  stock_unique_order_per_location/tests/test_stock_uique_order_per_location.py
  stock_unique_order_per_location/views/stock_picking_type_views.xml
Labels: bot is merging ⏳

#677 [14.0][IMP] shopfloor_reception: Refactor test for select_move
  shopfloor_reception/tests/common.py
  shopfloor_reception/tests/test_reception_done.py
  shopfloor_reception/tests/test_select_dest_package.py
  shopfloor_reception/tests/test_select_document.py
  shopfloor_reception/tests/test_select_move.py
  shopfloor_reception/tests/test_set_destination.py
  shopfloor_reception/tests/test_set_quantity.py
Labels: ready to merge, approved, bot is merging ⏳

#668 [14.0] shopfloor_reception: Fixes
  shopfloor/actions/data.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_dangerous_goods/tests/test_actions_data.py
  shopfloor_reception/services/reception.py
Labels: approved, bot is merging ⏳

#672 [14.0][IMP] shopfloor_reception: Allow users to work concurrently
  shopfloor/actions/message.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_set_quantity.py
  shopfloor_reception_mobile/static/src/scenario/reception.js
  shopfloor_reception_mobile/static/src/scenario/reception_states.js
Labels: ready to merge, approved, bot is merging ⏳

#684 [14.0][IMP] shopfloor_reception: Change select_move screen use manual-select
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_select_move.py
  shopfloor_reception_mobile/static/src/scenario/reception.js
  shopfloor_reception_mobile/static/src/scenario/reception_states.js
Labels: approved, bot is merging ⏳

#681 [14.] shopfloor checkout: always update qty done after selecting line
  shopfloor/services/checkout.py
Labels: bot is merging ⏳

#618 [14.0] shopfloor_checkout: ask to select child destination when marking as done
  shopfloor/actions/data.py
  shopfloor/actions/schema.py
  shopfloor/services/checkout.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_done.py
  shopfloor/tests/test_checkout_scan_dest_location.py
  shopfloor_mobile/static/wms/src/scenario/checkout.js
  shopfloor_mobile/static/wms/src/scenario/checkout_states.js
Labels: bot is merging ⏳

#678 [14.0][FIX] shopfloor reception: fix select destination package with location
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_select_dest_package.py
Labels: bot is merging ⏳
