Repository OCA/wms, pull requests merged in 2023-12, with the labels that each got.

#726 [14.0][FIX] shopfloor_reception: Fix qty todo computation
  shopfloor_base/actions/lock.py
  shopfloor_base/tests/__init__.py
  shopfloor_base/tests/test_actions_lock.py
  shopfloor_reception/data/shopfloor_scenario_data.xml
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/common.py
  shopfloor_reception/tests/test_return_scan_line.py
  shopfloor_reception/tests/test_select_move.py
  shopfloor_reception/tests/test_set_destination.py
  shopfloor_reception/tests/test_set_quantity.py
  shopfloor_reception/tests/test_set_quantity_action.py
  shopfloor_reception_mobile/static/src/scenario/reception.js
  shopfloor_reception_mobile/static/src/scenario/reception_states.js
Labels: approved, bot is merging ⏳

#787 [14.0] shopfloor checkout update diagram (doc)
  shopfloor/docs/checkout_diag_seq.plantuml
  shopfloor/docs/checkout_diag_seq.png
Labels: bot is merging ⏳

#454 [15.0][MIG] delivery_carrier_warehouse
  delivery_carrier_warehouse/README.rst
  delivery_carrier_warehouse/__init__.py
  delivery_carrier_warehouse/__manifest__.py
  delivery_carrier_warehouse/i18n/delivery_carrier_warehouse.pot
  delivery_carrier_warehouse/i18n/es_AR.po
  delivery_carrier_warehouse/models/__init__.py
  delivery_carrier_warehouse/models/sale_order.py
  delivery_carrier_warehouse/models/stock_warehouse.py
  delivery_carrier_warehouse/readme/CONTRIBUTORS.rst
  delivery_carrier_warehouse/readme/CREDITS.rst
  delivery_carrier_warehouse/readme/DESCRIPTION.rst
  delivery_carrier_warehouse/static/description/icon.png
  delivery_carrier_warehouse/static/description/index.html
  delivery_carrier_warehouse/tests/__init__.py
  delivery_carrier_warehouse/tests/test_delivery_carrier_warehouse.py
  delivery_carrier_warehouse/views/stock_warehouse.xml
  setup/delivery_carrier_warehouse/odoo/addons/delivery_carrier_warehouse
  setup/delivery_carrier_warehouse/setup.py
Labels: migration, needs fixing, needs review, bot is merging ⏳, stale

#797 [FIX] stock_release_channel: Fix enqueued jobs tests / stock_release_channel_process_end_time: Freeze
  stock_release_channel/tests/test_assign_job.py
  stock_release_channel_partner_delivery_window/tests/test_release_window.py
Labels: enhancement, bot is merging ⏳

#795 [UPD] Copier update
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#783 [14.0][ADD] shopfloor_checkout_putinpack_restriction
  setup/shopfloor_checkout_putinpack_restriction/odoo/addons/shopfloor_checkout_putinpack_restriction
  setup/shopfloor_checkout_putinpack_restriction/setup.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_list_delivery_packaging.py
  shopfloor/tests/test_checkout_scan_package_action.py
  shopfloor/tests/test_checkout_select_package_base.py
  shopfloor_checkout_putinpack_restriction/README.rst
  shopfloor_checkout_putinpack_restriction/__init__.py
  shopfloor_checkout_putinpack_restriction/__manifest__.py
  shopfloor_checkout_putinpack_restriction/actions/__init__.py
  shopfloor_checkout_putinpack_restriction/actions/message.py
  shopfloor_checkout_putinpack_restriction/readme/CONTRIBUTORS.rst
  shopfloor_checkout_putinpack_restriction/readme/DESCRIPTION.rst
  shopfloor_checkout_putinpack_restriction/services/__init__.py
  shopfloor_checkout_putinpack_restriction/services/checkout.py
  shopfloor_checkout_putinpack_restriction/static/description/index.html
  shopfloor_checkout_putinpack_restriction/tests/__init__.py
  shopfloor_checkout_putinpack_restriction/tests/test_checkout_putinpack_restriction.py
  shopfloor_mobile/static/wms/src/scenario/checkout.js
Labels: ready to merge, approved, bot is merging ⏳

#800 [16.0] [MIG] delivery_carrier_warehouse
  delivery_carrier_warehouse/README.rst
  delivery_carrier_warehouse/__init__.py
  delivery_carrier_warehouse/__manifest__.py
  delivery_carrier_warehouse/i18n/delivery_carrier_warehouse.pot
  delivery_carrier_warehouse/i18n/es_AR.po
  delivery_carrier_warehouse/models/__init__.py
  delivery_carrier_warehouse/models/sale_order.py
  delivery_carrier_warehouse/models/stock_warehouse.py
  delivery_carrier_warehouse/readme/CONTRIBUTORS.rst
  delivery_carrier_warehouse/readme/CREDITS.rst
  delivery_carrier_warehouse/readme/DESCRIPTION.rst
  delivery_carrier_warehouse/static/description/icon.png
  delivery_carrier_warehouse/static/description/index.html
  delivery_carrier_warehouse/tests/__init__.py
  delivery_carrier_warehouse/tests/test_delivery_carrier_warehouse.py
  delivery_carrier_warehouse/views/stock_warehouse.xml
  setup/delivery_carrier_warehouse/odoo/addons/delivery_carrier_warehouse
  setup/delivery_carrier_warehouse/setup.py
Labels: approved, bot is merging ⏳

#788 [IMP] stock_storage_type: improve location_is_empty compute performance
  stock_storage_type/models/stock_location.py
Labels: approved, bot is merging ⏳

#804 [IMP] improve logging
  delivery_carrier_warehouse/tests/test_delivery_carrier_warehouse.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel_process_end_time/tests/test_release_end_date.py
Labels: approved, bot is merging ⏳

#805 [14.0][FIX] stock_dynamic_routing: routing moves has to be MTO
  stock_dynamic_routing/models/stock_move.py
Labels: bug, bot is merging ⏳
