Repository OCA/wms, pull requests merged in 2023-05, with the labels that each got.

#508 [16.0] [ADD] stock_release_channel_auto_release
  setup/stock_release_channel_auto_release/odoo/addons/stock_release_channel_auto_release
  setup/stock_release_channel_auto_release/setup.py
  setup/stock_release_channel_batch_mode_commercial_partner/odoo/addons/stock_release_channel_batch_mode_commercial_partner
  setup/stock_release_channel_batch_mode_commercial_partner/setup.py
  stock_release_channel/i18n/stock_release_channel.pot
  stock_release_channel/migrations/16.0.1.0.1/pre-migrate.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/common.py
  stock_release_channel/tests/test_channel_release_batch.py
  stock_release_channel/views/stock_picking_views.xml
  stock_release_channel/views/stock_release_channel_views.xml
  stock_release_channel_auto_release/README.rst
  stock_release_channel_auto_release/__init__.py
  stock_release_channel_auto_release/__manifest__.py
  stock_release_channel_auto_release/data/queue_job_data.xml
  stock_release_channel_auto_release/models/__init__.py
  stock_release_channel_auto_release/models/stock_picking.py
  stock_release_channel_auto_release/models/stock_release_channel.py
  stock_release_channel_auto_release/readme/CONTRIBUTORS.rst
  stock_release_channel_auto_release/readme/DESCRIPTION.rst
  stock_release_channel_auto_release/readme/USAGE.rst
  stock_release_channel_auto_release/static/description/icon.png
  stock_release_channel_auto_release/static/description/index.html
  stock_release_channel_auto_release/tests/__init__.py
  stock_release_channel_auto_release/tests/test_channel_release_auto.py
  stock_release_channel_auto_release/views/stock_release_channel.xml
  stock_release_channel_batch_mode_commercial_partner/README.rst
  stock_release_channel_batch_mode_commercial_partner/__init__.py
  stock_release_channel_batch_mode_commercial_partner/__manifest__.py
  stock_release_channel_batch_mode_commercial_partner/models/__init__.py
  stock_release_channel_batch_mode_commercial_partner/models/stock_release_channel.py
  stock_release_channel_batch_mode_commercial_partner/readme/CONTRIBUTORS.rst
  stock_release_channel_batch_mode_commercial_partner/readme/DESCRIPTION.rst
  stock_release_channel_batch_mode_commercial_partner/readme/USAGE.rst
  stock_release_channel_batch_mode_commercial_partner/static/description/icon.png
  stock_release_channel_batch_mode_commercial_partner/static/description/index.html
  stock_release_channel_batch_mode_commercial_partner/tests/__init__.py
  stock_release_channel_batch_mode_commercial_partner/tests/test_channel_release_batch.py
Labels: ready to merge, needs review, approved, bot is merging ⏳

#574 [14.0] shopfloor_base: cross worker fix
  shopfloor_base/__manifest__.py
  shopfloor_base/controllers/main.py
  shopfloor_base/data/server_action.xml
  shopfloor_base/migrations/14.0.2.9.0/post-migrate.py
  shopfloor_base/models/shopfloor_app.py
  shopfloor_base/readme/ROADMAP.rst
  shopfloor_base/tests/common_http.py
  shopfloor_base/tests/test_shopfloor_app.py
  shopfloor_base/views/shopfloor_app.xml
Labels: bot is merging ⏳

#543 shopfloor: imp unmark_move_line_as_picked function
  shopfloor/actions/stock.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_actions_stock.py
Labels: bot is merging ⏳

#625 [14.0][IMP] shopfloor: checkout auto post lines
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/checkout.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_checkout_auto_post.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_checkout_package_measurement/services/checkout.py
  shopfloor_reception/__init__.py
  shopfloor_reception/__manifest__.py
  shopfloor_reception/models/__init__.py
  shopfloor_reception/models/shopfloor_menu.py
  shopfloor_reception/views/shopfloor_menu.xml
Labels: approved, bot is merging ⏳

#641 [14.0] shopfloor: update README
  shopfloor/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#513 [14.0][ADD] shopfloor_single_product_transfer
  setup/shopfloor_single_product_transfer/odoo/addons/shopfloor_single_product_transfer
  setup/shopfloor_single_product_transfer/setup.py
  shopfloor/actions/message.py
  shopfloor/actions/stock_unreserve.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/views/shopfloor_menu.xml
  shopfloor_single_product_transfer/README.rst
  shopfloor_single_product_transfer/__init__.py
  shopfloor_single_product_transfer/__manifest__.py
  shopfloor_single_product_transfer/data/shopfloor_scenario_data.xml
  shopfloor_single_product_transfer/demo/shopfloor_menu_demo.xml
  shopfloor_single_product_transfer/demo/stock_picking_type_demo.xml
  shopfloor_single_product_transfer/docs/diagram.plantuml
  shopfloor_single_product_transfer/docs/diagram.png
  shopfloor_single_product_transfer/docs/oca_logo.png
  shopfloor_single_product_transfer/readme/CONTRIBUTORS.rst
  shopfloor_single_product_transfer/readme/DESCRIPTION.rst
  shopfloor_single_product_transfer/readme/USAGE.rst
  shopfloor_single_product_transfer/services/__init__.py
  shopfloor_single_product_transfer/services/single_product_transfer.py
  shopfloor_single_product_transfer/tests/__init__.py
  shopfloor_single_product_transfer/tests/common.py
  shopfloor_single_product_transfer/tests/test_scan_location.py
  shopfloor_single_product_transfer/tests/test_scan_product.py
  shopfloor_single_product_transfer/tests/test_set_quantity.py
  shopfloor_single_product_transfer/tests/test_set_quantity_checkout_sync.py
  shopfloor_single_product_transfer/tests/test_start.py
Labels: ready to merge, approved, bot is merging ⏳

#614 [14.0] shopfloor: display location operations progress in delivery scenario
  shopfloor/actions/data.py
  shopfloor/actions/schema.py
  shopfloor/services/delivery.py
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_delivery_base.py
  shopfloor_mobile/static/wms/src/scenario/delivery.js
Labels: approved, bot is merging ⏳

#608 shopfloor_mobile: zone_picking always refresh list of lines
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: bot is merging ⏳

#629 [16.0][IMP] stock_release_channel: Add message in queue job if no channel was found
  stock_release_channel/models/stock_picking.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/__init__.py
  stock_release_channel/tests/test_assign_job.py
Labels: approved, bot is merging ⏳

#610 [14.0][FIX] shopfloor_reception: improve scenario
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_select_document.py
  shopfloor_reception/tests/test_select_move.py
  shopfloor_reception/tests/test_set_destination.py
  shopfloor_reception/tests/test_set_lot_confirm.py
  shopfloor_reception/tests/test_set_quantity.py
  shopfloor_reception_mobile/static/src/scenario/reception.js
  shopfloor_reception_mobile/static/src/scenario/reception_states.js
Labels: approved, bot is merging ⏳

#533 [14.0] stock_available_to_promise_release & stock_release_channel: refactor releasing
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_release_channel/models/stock_move.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel/tests/test_channel_action.py
Labels: approved, bot is merging ⏳

#630 [14.0] shopfloor: cluster picking add option first scan location or pack
  shopfloor/actions/message.py
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/services/cluster_picking.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_cluster_picking_base.py
  shopfloor/tests/test_cluster_picking_scan_line.py
  shopfloor/tests/test_cluster_picking_scan_line_location_or_pack_first.py
  shopfloor/tests/test_cluster_picking_select.py
  shopfloor/tests/test_zone_picking_select_line_first_scan_location.py.bak
  shopfloor_mobile/static/wms/src/i18n/en.json
  shopfloor_mobile/static/wms/src/scenario/cluster_picking.js
Labels: approved, bot is merging ⏳

#632 [14.0] shopfloor_workstation: add name and barcode constraints
  shopfloor_workstation/models/shopfloor_workstation.py
  shopfloor_workstation/tests/test_shopfloor_workstation.py
Labels: ready to merge, approved, bot is merging ⏳

#606 [14.0][FIX] shopfloor: Fix product/lot not found message
  shopfloor/actions/message.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_select_line.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_select_document.py
Labels: approved, bot is merging ⏳

#631 [14.0] shopfloor zone_picking: block move selection
  shopfloor_mobile/static/wms/src/scenario/zone_picking.js
Labels: approved, bot is merging ⏳
