Repository OCA/wms, pull requests merged in 2024-04, with the labels that each got.

#881 [16.0][IMP] stock_release_channel_plan: Add widget many2many_tags to preparation_weekday_ids
  stock_release_channel_plan/views/stock_release_channel_preparation_plan.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#696 [16.0][ADD] stock_release_channel_plan_process_end_time
  setup/stock_release_channel_plan_process_end_time/odoo/addons/stock_release_channel_plan_process_end_time
  setup/stock_release_channel_plan_process_end_time/setup.py
  stock_release_channel_plan/tests/common.py
  stock_release_channel_plan/tests/test_stock_release_channel_plan.py
  stock_release_channel_plan_process_end_time/README.rst
  stock_release_channel_plan_process_end_time/__init__.py
  stock_release_channel_plan_process_end_time/__manifest__.py
  stock_release_channel_plan_process_end_time/demo/stock_release_channel.xml
  stock_release_channel_plan_process_end_time/readme/CONTRIBUTORS.rst
  stock_release_channel_plan_process_end_time/readme/CREDITS.rst
  stock_release_channel_plan_process_end_time/readme/DESCRIPTION.rst
  stock_release_channel_plan_process_end_time/static/description/index.html
  stock_release_channel_plan_process_end_time/tests/__init__.py
  stock_release_channel_plan_process_end_time/tests/test_stock_release_channel_plan.py
  stock_release_channel_plan_process_end_time/wizards/__init__.py
  stock_release_channel_plan_process_end_time/wizards/launch_plan.py
  stock_release_channel_plan_process_end_time/wizards/launch_plan.xml
Labels: ready to merge, approved, bot is merging ⏳

#859 [16.0][IMP] stock_release_channel_process_end_time: tests
  stock_release_channel_process_end_time/tests/test_release_end_date.py
Labels: enhancement, bot is merging ⏳

#831 [IMP] stock_storage_type: Don't consider quant with quantities <= 0
  stock_storage_type/models/stock_location.py
  stock_storage_type/tests/test_stock_location.py
Labels: enhancement, needs review, bot is merging ⏳

#825 [16.0][FW][IMP] stock_available_to_promise_release: Own field for release policy
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/migrations/16.0.3.1.0/post-migrate.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/views/stock_picking_views.xml
Labels: bot is merging ⏳

#836 [16.0][IMP] stock_release_channel_process_end_time: date_deadline
  stock_release_channel_process_end_time/README.rst
  stock_release_channel_process_end_time/models/__init__.py
  stock_release_channel_process_end_time/models/stock_move.py
  stock_release_channel_process_end_time/readme/DESCRIPTION.rst
  stock_release_channel_process_end_time/readme/USAGE.rst
  stock_release_channel_process_end_time/static/description/index.html
  stock_release_channel_process_end_time/tests/test_release_end_date.py
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#884 [IMP] stock_release_channel: add a field to define the channel state at wakeup
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/test_release_channel_lifecycle.py
  stock_release_channel/views/stock_release_channel_views.xml
  stock_release_channel_plan/tests/test_stock_release_channel_plan.py
  stock_release_channel_plan/wizards/launch_plan.py
Labels: approved, bot is merging ⏳

#572 [16.0][ADD] stock_release_channel_shipment_advice_process_end_time
  setup/stock_release_channel_shipment_advice_process_end_time/odoo/addons/stock_release_channel_shipment_advice_process_end_time
  setup/stock_release_channel_shipment_advice_process_end_time/setup.py
  stock_release_channel_shipment_advice_process_end_time/README.rst
  stock_release_channel_shipment_advice_process_end_time/__init__.py
  stock_release_channel_shipment_advice_process_end_time/__manifest__.py
  stock_release_channel_shipment_advice_process_end_time/i18n/fr_BE.po
  stock_release_channel_shipment_advice_process_end_time/models/__init__.py
  stock_release_channel_shipment_advice_process_end_time/models/stock_release_channel.py
  stock_release_channel_shipment_advice_process_end_time/models/stock_warehouse.py
  stock_release_channel_shipment_advice_process_end_time/readme/CONTRIBUTORS.rst
  stock_release_channel_shipment_advice_process_end_time/readme/DESCRIPTION.rst
  stock_release_channel_shipment_advice_process_end_time/readme/USAGE.rst
  stock_release_channel_shipment_advice_process_end_time/static/description/icon.png
  stock_release_channel_shipment_advice_process_end_time/static/description/index.html
  stock_release_channel_shipment_advice_process_end_time/tests/__init__.py
  stock_release_channel_shipment_advice_process_end_time/tests/test_stock_release_channel_shipment_advice_process_end_time.py
  stock_release_channel_shipment_advice_process_end_time/views/stock_release_channel.xml
  stock_release_channel_shipment_advice_process_end_time/views/stock_warehouse.xml
  stock_release_channel_shipment_advice_process_end_time/wizards/__init__.py
  stock_release_channel_shipment_advice_process_end_time/wizards/shipment_advice_planner.py
Labels: approved, bot is merging ⏳

#865 [16.0][ADD] stock_available_to_promise_release_block: block release of operations
  setup/stock_available_to_promise_release_block/odoo/addons/stock_available_to_promise_release_block
  setup/stock_available_to_promise_release_block/setup.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release_block/README.rst
  stock_available_to_promise_release_block/__init__.py
  stock_available_to_promise_release_block/__manifest__.py
  stock_available_to_promise_release_block/models/__init__.py
  stock_available_to_promise_release_block/models/stock_move.py
  stock_available_to_promise_release_block/models/stock_picking.py
  stock_available_to_promise_release_block/models/stock_route.py
  stock_available_to_promise_release_block/models/stock_rule.py
  stock_available_to_promise_release_block/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release_block/readme/DESCRIPTION.rst
  stock_available_to_promise_release_block/readme/USAGE.rst
  stock_available_to_promise_release_block/static/description/index.html
  stock_available_to_promise_release_block/tests/__init__.py
  stock_available_to_promise_release_block/tests/common.py
  stock_available_to_promise_release_block/tests/test_block_release.py
  stock_available_to_promise_release_block/views/stock_move.xml
  stock_available_to_promise_release_block/views/stock_picking.xml
  stock_available_to_promise_release_block/views/stock_route.xml
Labels: ready to merge, approved, bot is merging ⏳

#885 [16.0][ADD] stock_available_to_promise_release_exclude_location
  setup/stock_available_to_promise_release_exclude_location/odoo/addons/stock_available_to_promise_release_exclude_location
  setup/stock_available_to_promise_release_exclude_location/setup.py
  stock_available_to_promise_release_exclude_location/README.rst
  stock_available_to_promise_release_exclude_location/__init__.py
  stock_available_to_promise_release_exclude_location/__manifest__.py
  stock_available_to_promise_release_exclude_location/models/__init__.py
  stock_available_to_promise_release_exclude_location/models/stock_location.py
  stock_available_to_promise_release_exclude_location/readme/DESCRIPTION.rst
  stock_available_to_promise_release_exclude_location/static/description/index.html
  stock_available_to_promise_release_exclude_location/tests/__init__.py
  stock_available_to_promise_release_exclude_location/tests/test_exclude_location.py
Labels: needs review, approved, bot is merging ⏳

#867 [16.0][ADD] sale_stock_available_to_promise_release_block: block release of operations directly from sales
  sale_stock_available_to_promise_release_block/README.rst
  sale_stock_available_to_promise_release_block/__init__.py
  sale_stock_available_to_promise_release_block/__manifest__.py
  sale_stock_available_to_promise_release_block/models/__init__.py
  sale_stock_available_to_promise_release_block/models/sale_order.py
  sale_stock_available_to_promise_release_block/models/sale_order_line.py
  sale_stock_available_to_promise_release_block/models/stock_rule.py
  sale_stock_available_to_promise_release_block/readme/CONTRIBUTORS.rst
  sale_stock_available_to_promise_release_block/readme/DESCRIPTION.rst
  sale_stock_available_to_promise_release_block/readme/USAGE.rst
  sale_stock_available_to_promise_release_block/static/description/index.html
  sale_stock_available_to_promise_release_block/tests/__init__.py
  sale_stock_available_to_promise_release_block/tests/test_sale_block_release.py
  sale_stock_available_to_promise_release_block/views/sale_order.xml
  sale_stock_available_to_promise_release_block/views/sale_order_line.xml
  setup/sale_stock_available_to_promise_release_block/odoo/addons/sale_stock_available_to_promise_release_block
  setup/sale_stock_available_to_promise_release_block/setup.py
Labels: ready to merge, needs review, approved, bot is merging ⏳

#887 [16.0][IMP] stock_available_to_promise_release_block: Tracking release_blocked
  stock_available_to_promise_release_block/models/stock_picking.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#577 [16.0][ADD] - add stock_release_channel_shipment_advice_toursolver
  setup/stock_release_channel_shipment_advice_toursolver/odoo/addons/stock_release_channel_shipment_advice_toursolver
  setup/stock_release_channel_shipment_advice_toursolver/setup.py
  stock_release_channel_shipment_advice_toursolver/README.rst
  stock_release_channel_shipment_advice_toursolver/__init__.py
  stock_release_channel_shipment_advice_toursolver/__manifest__.py
  stock_release_channel_shipment_advice_toursolver/models/__init__.py
  stock_release_channel_shipment_advice_toursolver/models/stock_release_channel.py
  stock_release_channel_shipment_advice_toursolver/models/toursolver_task.py
  stock_release_channel_shipment_advice_toursolver/readme/CONTRIBUTORS.rst
  stock_release_channel_shipment_advice_toursolver/readme/DESCRIPTION.rst
  stock_release_channel_shipment_advice_toursolver/static/description/icon.png
  stock_release_channel_shipment_advice_toursolver/static/description/index.html
  stock_release_channel_shipment_advice_toursolver/tests/__init__.py
  stock_release_channel_shipment_advice_toursolver/tests/cassettes/TestShipmentAdvicePlannerToursolver.test_plan_shipment_toursolver.yaml
  stock_release_channel_shipment_advice_toursolver/tests/test_shipment_advice_planner_toursolver.py
  stock_release_channel_shipment_advice_toursolver/views/stock_release_channel.xml
  stock_release_channel_shipment_advice_toursolver/views/toursolver_task.xml
  stock_release_channel_shipment_advice_toursolver/wizards/__init__.py
  stock_release_channel_shipment_advice_toursolver/wizards/shipment_advice_planner.py
  test-requirements.txt
Labels: ready to merge, approved, bot is merging ⏳, no stale
