Repository OCA/wms, pull requests merged in 2024-07, with the labels that each got.

#853 [16.0][IMP] stock_release_channel: assign picking after channel sleep if possible
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/test_release_channel_lifecycle.py
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#914 [16.0][IMP] stock_available_to_promise_release reset last_release_date on backorder
  stock_available_to_promise_release/models/stock_picking.py
Labels: ready to merge, approved, bot is merging ⏳

#913 [IMP] stock_available_to_promise_release: Improve migration script
  stock_available_to_promise_release/migrations/16.0.3.1.0/post-migrate.py
  stock_available_to_promise_release/migrations/16.0.3.1.0/pre-migrate.py
Labels: ready to merge, needs review, approved, bot is merging ⏳
