Repository OCA/wms, pull requests merged in 2024-01, with the labels that each got.

#811 [14.0[FIX] shopfloor, zone_picking: get right qty when pack/lot is changed
  shopfloor/services/zone_picking.py
  shopfloor/tests/test_zone_picking_change_pack_lot.py
  shopfloor/tests/test_zone_picking_select_line.py
Labels: bug, approved, bot is merging ⏳

#807 [16.0][FIX] stock_available_to_promise_release: unrelease
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease.py
  stock_available_to_promise_release/tests/test_unrelease_2steps.py
  stock_available_to_promise_release/tests/test_unrelease_3steps.py
Labels: approved, bot is merging ⏳

#810 [14.0][FIX] stock_available_to_promise_release: unrelease
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease.py
  stock_available_to_promise_release/tests/test_unrelease_2steps.py
  stock_available_to_promise_release/tests/test_unrelease_3steps.py
Labels: ready to merge, approved, bot is merging ⏳

#812 [14.0][IMP] stock_available_to_promise_release: Refactor release_ready compute
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_release_channel/tests/test_channel_release_batch.py
Labels: approved, bot is merging ⏳

#808 [16.0][PORT] stock_available_to_promise_release : fw-port changes from 14.0
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/models/stock_rule.py
  stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/tests/test_unrelease_merged_moves.py
  stock_release_channel/tests/test_channel_release_batch.py
Labels: ready to merge, approved, bot is merging ⏳

#796 [14.0] shopfloor_mobile_base: force nav item counter update
  shopfloor_mobile_base/static/wms/src/main.js
  shopfloor_mobile_base/static/wms/src/scenario/mixins.js
Labels: approved, bot is merging ⏳

#816 [14.0][FIX] stock_available_to_promise_release: release_ready for stock.picking
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: ready to merge, approved, bot is merging ⏳

#793 [14.0][IMP] stock_available_to_promise_release: Own field for release policy
  sale_stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/migrations/14.0.2.5.0/post-migrate.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/views/stock_picking_views.xml
Labels: ready to merge, approved, bot is merging ⏳

#817 [16.0][FW][FIX] stock_available_to_promise_release: release_ready for stock.picking
  stock_available_to_promise_release/models/stock_picking.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: bot is merging ⏳

#814 [14.0][IMP] shopfloor add index on result_package_id
  shopfloor/models/stock_move_line.py
Labels: ready to merge, approved, bot is merging ⏳

#830 [16.0][FW][FIX] shopfloor_base: commen test get_service
  shopfloor_base/tests/common.py
Labels: bot is merging ⏳

#822 [14.0][FIX] shopfloor_base: Test without menu on actions
  shopfloor_base/tests/common.py
Labels: bot is merging ⏳
