Repository OCA/wms, pull requests merged in 2024-05, with the labels that each got.

#693 [16.0][MIG] - shopfloor_workstation
  setup/shopfloor_workstation/odoo/addons/shopfloor_workstation
  setup/shopfloor_workstation/setup.py
  shopfloor_workstation/README.rst
  shopfloor_workstation/__init__.py
  shopfloor_workstation/__manifest__.py
  shopfloor_workstation/demo/shopfloor_workstation_demo.xml
  shopfloor_workstation/i18n/es_AR.po
  shopfloor_workstation/i18n/shopfloor_workstation.pot
  shopfloor_workstation/models/__init__.py
  shopfloor_workstation/models/shopfloor_workstation.py
  shopfloor_workstation/readme/CONFIGURE.rst
  shopfloor_workstation/readme/CONTRIBUTORS.rst
  shopfloor_workstation/readme/DESCRIPTION.rst
  shopfloor_workstation/security/ir.model.access.csv
  shopfloor_workstation/services/__init__.py
  shopfloor_workstation/services/workstation.py
  shopfloor_workstation/static/description/icon.png
  shopfloor_workstation/static/description/index.html
  shopfloor_workstation/tests/__init__.py
  shopfloor_workstation/tests/test_shopfloor_workstation.py
  shopfloor_workstation/views/shopfloor_workstation.xml
Labels: migration, ready to merge, needs review, approved, bot is merging ⏳, no stale

#898 [FIX] stock_available_to_promise_release_block multi block
  stock_available_to_promise_release_block/models/stock_move.py
Labels: bot is merging ⏳

#697 [16.0][MIG] - shopfloor_workstation_mobile
  .pre-commit-config.yaml
  setup/shopfloor_workstation_mobile/odoo/addons/shopfloor_workstation_mobile
  setup/shopfloor_workstation_mobile/setup.py
  shopfloor_workstation_mobile/README.rst
  shopfloor_workstation_mobile/__init__.py
  shopfloor_workstation_mobile/__manifest__.py
  shopfloor_workstation_mobile/i18n/es_AR.po
  shopfloor_workstation_mobile/i18n/pt_BR.po
  shopfloor_workstation_mobile/i18n/shopfloor_workstation_mobile.pot
  shopfloor_workstation_mobile/static/description/icon.png
  shopfloor_workstation_mobile/static/description/index.html
  shopfloor_workstation_mobile/static/wms/src/settings/workstation.js
  shopfloor_workstation_mobile/templates/assets.xml
Labels: ready to merge, approved, bot is merging ⏳

#895 [14.0][IMP] shopfloor_reception: Allow return even if not fully delivered
  shopfloor/actions/search.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/reception_return_common.py
  shopfloor_reception/tests/test_return_scan_document.py
Labels: ready to merge, approved, bot is merging ⏳

#845 [FIX] shopfloor_base: Manage correctly parameters to the next call stack
  shopfloor_base/README.rst
  shopfloor_base/controllers/main.py
  shopfloor_base/readme/CONTRIBUTORS.rst
  shopfloor_base/static/description/index.html
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#713 [16.0][MIG] - shopfloor_rest_log
  setup/shopfloor_rest_log/odoo/addons/shopfloor_rest_log
  setup/shopfloor_rest_log/setup.py
  shopfloor_rest_log/README.rst
  shopfloor_rest_log/__init__.py
  shopfloor_rest_log/__manifest__.py
  shopfloor_rest_log/components/__init__.py
  shopfloor_rest_log/components/service.py
  shopfloor_rest_log/hooks.py
  shopfloor_rest_log/i18n/es_AR.po
  shopfloor_rest_log/i18n/shopfloor_rest_log.pot
  shopfloor_rest_log/models/__init__.py
  shopfloor_rest_log/models/rest_log.py
  shopfloor_rest_log/models/shopfloor_app.py
  shopfloor_rest_log/readme/CONTRIBUTORS.rst
  shopfloor_rest_log/readme/DESCRIPTION.rst
  shopfloor_rest_log/readme/HISTORY.rst
  shopfloor_rest_log/readme/USAGE.rst
  shopfloor_rest_log/security/groups.xml
  shopfloor_rest_log/static/description/icon.png
  shopfloor_rest_log/static/description/index.html
  shopfloor_rest_log/views/menus.xml
  shopfloor_rest_log/views/rest_log.xml
  shopfloor_rest_log/views/shopfloor_app.xml
Labels: approved, bot is merging ⏳, no stale

#703 [16.0][MIG] - shopfloor_batch_automatic_creation
  setup/shopfloor_batch_automatic_creation/odoo/addons/shopfloor_batch_automatic_creation
  setup/shopfloor_batch_automatic_creation/setup.py
  shopfloor_batch_automatic_creation/README.rst
  shopfloor_batch_automatic_creation/__init__.py
  shopfloor_batch_automatic_creation/__manifest__.py
  shopfloor_batch_automatic_creation/actions/__init__.py
  shopfloor_batch_automatic_creation/actions/picking_batch_auto_create.py
  shopfloor_batch_automatic_creation/i18n/es_AR.po
  shopfloor_batch_automatic_creation/i18n/shopfloor_batch_automatic_creation.pot
  shopfloor_batch_automatic_creation/models/__init__.py
  shopfloor_batch_automatic_creation/models/shopfloor_menu.py
  shopfloor_batch_automatic_creation/readme/CONTRIBUTORS.rst
  shopfloor_batch_automatic_creation/readme/CREDITS.rst
  shopfloor_batch_automatic_creation/readme/DESCRIPTION.rst
  shopfloor_batch_automatic_creation/services/__init__.py
  shopfloor_batch_automatic_creation/services/cluster_picking.py
  shopfloor_batch_automatic_creation/static/description/icon.png
  shopfloor_batch_automatic_creation/static/description/index.html
  shopfloor_batch_automatic_creation/tests/__init__.py
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
  shopfloor_batch_automatic_creation/views/shopfloor_menu_views.xml
Labels: migration, ready to merge, needs review, approved, bot is merging ⏳, no stale

#701 [16.0][MIG] - shopfloor_mobile_base_auth_api_key
  setup/shopfloor_mobile_base_auth_api_key/odoo/addons/shopfloor_mobile_base_auth_api_key
  setup/shopfloor_mobile_base_auth_api_key/setup.py
  shopfloor_mobile_base_auth_api_key/README.rst
  shopfloor_mobile_base_auth_api_key/__init__.py
  shopfloor_mobile_base_auth_api_key/__manifest__.py
  shopfloor_mobile_base_auth_api_key/demo/auth_api_key_demo.xml
  shopfloor_mobile_base_auth_api_key/demo/auth_api_key_group_demo.xml
  shopfloor_mobile_base_auth_api_key/demo/shopfloor_app_demo.xml
  shopfloor_mobile_base_auth_api_key/i18n/pt_BR.po
  shopfloor_mobile_base_auth_api_key/i18n/shopfloor_mobile_base_auth_api_key.pot
  shopfloor_mobile_base_auth_api_key/models/__init__.py
  shopfloor_mobile_base_auth_api_key/models/shopfloor_app.py
  shopfloor_mobile_base_auth_api_key/readme/CONTRIBUTORS.rst
  shopfloor_mobile_base_auth_api_key/readme/CREDITS.rst
  shopfloor_mobile_base_auth_api_key/readme/DESCRIPTION.rst
  shopfloor_mobile_base_auth_api_key/services/__init__.py
  shopfloor_mobile_base_auth_api_key/services/service.py
  shopfloor_mobile_base_auth_api_key/static/description/icon.png
  shopfloor_mobile_base_auth_api_key/static/description/index.html
  shopfloor_mobile_base_auth_api_key/static/wms/src/login.js
  shopfloor_mobile_base_auth_api_key/templates/assets.xml
  shopfloor_mobile_base_auth_api_key/views/shopfloor_app.xml
Labels: approved, bot is merging ⏳, stale, no stale

#861 [16.0][IMP] stock_release_channel: Add a company setting to enable/disable recomputation of channel on release
  stock_release_channel/models/res_company.py
  stock_release_channel/models/res_config_settings.py
  stock_release_channel/models/stock_move.py
  stock_release_channel/tests/test_release_channel.py
  stock_release_channel/views/res_config_settings.xml
Labels: ready to merge, approved, bot is merging ⏳
