Repository OCA/wms, pull requests merged in 2024-03, with the labels that each got.

#837 [14.0][IMP] shopfloor: mark lines as sf_checkout_done when handled in backend
  shopfloor/models/stock_picking.py
  shopfloor/tests/test_checkout_scan_package_action.py
Labels: ready to merge, approved, bot is merging ⏳

#846 [14.0][FIX] shopfloor_manual_product_transfer_mobile: fix wrong qty_done
  shopfloor_manual_product_transfer_mobile/static/wms/src/scenario/manual_product_transfer.js
Labels: bot is merging ⏳

#843 [14.0][IMP] shopfloor: apply zero_check only if product is not a consumable
  shopfloor/services/cluster_picking.py
  shopfloor/services/zone_picking.py
Labels: bot is merging ⏳

#851 [16.0][FIX] stock_release_channel_process_end_time: releasable picking computation
  stock_release_channel_process_end_time/__manifest__.py
  stock_release_channel_process_end_time/models/stock_picking.py
  stock_release_channel_process_end_time/models/stock_release_channel.py
  stock_release_channel_process_end_time/readme/CONTRIBUTORS.rst
  stock_release_channel_process_end_time/tests/test_release_end_date.py
Labels: approved, bot is merging ⏳

#858 [16.0][FIX] stock_release_channel_process_end_time: end date compute
  stock_release_channel_process_end_time/models/stock_release_channel.py
Labels: bot is merging ⏳

#860 stock_release_channel: Add missing Copyright MT Software
  stock_release_channel/models/stock_release_channel.py
Labels: bot is merging ⏳

#856 [16.0][IMP] Release : set expected date
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_release_channel/models/stock_move.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel_process_end_time/models/stock_picking.py
  stock_release_channel_process_end_time/models/stock_release_channel.py
  stock_release_channel_process_end_time/tests/test_release_end_date.py
Labels: bot is merging ⏳

#823 [16.0][PORT] stock_available_to_promise_release: Multi warehouse capability
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/readme/DESCRIPTION.rst
  stock_available_to_promise_release/tests/test_reservation.py
Labels: approved, bot is merging ⏳

#855 [16.0][FIX] stock_release_channel_process_end_time: time zone datetime computation
  stock_release_channel_cutoff/models/stock_release_channel.py
  stock_release_channel_cutoff/tests/test_compute_cutoff_time.py
  stock_release_channel_process_end_time/models/stock_release_channel.py
  stock_release_channel_process_end_time/tests/test_release_end_date.py
  stock_release_channel_process_end_time/utils.py
Labels: ready to merge, approved, bot is merging ⏳

#857 [16.0][IMP] stock_release_channel_shipment_lead_time
  stock_release_channel_process_end_time/models/stock_picking.py
  stock_release_channel_process_end_time/models/stock_release_channel.py
  stock_release_channel_shipment_lead_time/__manifest__.py
  stock_release_channel_shipment_lead_time/models/stock_picking.py
  stock_release_channel_shipment_lead_time/readme/CONTRIBUTORS.rst
  stock_release_channel_shipment_lead_time/readme/DESCRIPTION.rst
  stock_release_channel_shipment_lead_time/tests/__init__.py
  stock_release_channel_shipment_lead_time/tests/test_release_end_date.py
Labels: approved, bot is merging ⏳

#876 [14.0] stock_reception_screen: fix perf issue when move are created
  stock_reception_screen/models/stock_reception_screen.py
Labels: bug, approved, bot is merging ⏳

#871 [14.0] sale_stock_available_to_promise_release: improve '_get_next_replenishment_date' perf
  sale_stock_available_to_promise_release/models/product_product.py
Labels: ready to merge, approved, bot is merging ⏳

#599 [16.0][ADD] Add stock_release_channel_geoengine
  .github/workflows/test.yml
  setup/stock_release_channel_geoengine/odoo/addons/stock_release_channel_geoengine
  setup/stock_release_channel_geoengine/setup.py
  stock_release_channel_geoengine/README.rst
  stock_release_channel_geoengine/__init__.py
  stock_release_channel_geoengine/__manifest__.py
  stock_release_channel_geoengine/models/__init__.py
  stock_release_channel_geoengine/models/res_partner.py
  stock_release_channel_geoengine/models/stock_picking.py
  stock_release_channel_geoengine/models/stock_release_channel.py
  stock_release_channel_geoengine/readme/CONFIGURE.rst
  stock_release_channel_geoengine/readme/CONTRIBUTORS.rst
  stock_release_channel_geoengine/readme/DESCRIPTION.rst
  stock_release_channel_geoengine/readme/INSTALL.rst
  stock_release_channel_geoengine/static/description/icon.png
  stock_release_channel_geoengine/static/description/index.html
  stock_release_channel_geoengine/tests/__init__.py
  stock_release_channel_geoengine/tests/common.py
  stock_release_channel_geoengine/tests/test_stock_release_channel_geoengine.py
  stock_release_channel_geoengine/views/res_partner.xml
  stock_release_channel_geoengine/views/stock_release_channel.xml
Labels: needs review, approved, bot is merging ⏳, no stale

#840 [16.0][ADD] stock_release_channel_delivery
  setup/stock_release_channel_delivery/odoo/addons/stock_release_channel_delivery
  setup/stock_release_channel_delivery/setup.py
  stock_release_channel_delivery/README.rst
  stock_release_channel_delivery/__init__.py
  stock_release_channel_delivery/__manifest__.py
  stock_release_channel_delivery/i18n/fr.po
  stock_release_channel_delivery/i18n/stock_release_channel_delivery.pot
  stock_release_channel_delivery/migrations/16.0.2.0.0/post-migration.py
  stock_release_channel_delivery/migrations/16.0.2.0.0/pre-migration.py
  stock_release_channel_delivery/models/__init__.py
  stock_release_channel_delivery/models/stock_picking.py
  stock_release_channel_delivery/models/stock_release_channel.py
  stock_release_channel_delivery/readme/CONTRIBUTORS.rst
  stock_release_channel_delivery/readme/DESCRIPTION.rst
  stock_release_channel_delivery/static/description/icon.png
  stock_release_channel_delivery/static/description/index.html
  stock_release_channel_delivery/tests/__init__.py
  stock_release_channel_delivery/tests/test_release_channel_delivery.py
  stock_release_channel_delivery/views/stock_release_channel_views.xml
Labels: bot is merging ⏳

#874 [16.0][MIG] sale_stock_available_to_promise_release: Migration to 16.0
  sale_stock_available_to_promise_release/README.rst
  sale_stock_available_to_promise_release/__init__.py
  sale_stock_available_to_promise_release/__manifest__.py
  sale_stock_available_to_promise_release/i18n/de.po
  sale_stock_available_to_promise_release/i18n/es_AR.po
  sale_stock_available_to_promise_release/i18n/fr.po
  sale_stock_available_to_promise_release/i18n/fr_CH.po
  sale_stock_available_to_promise_release/i18n/it.po
  sale_stock_available_to_promise_release/i18n/sale_stock_available_to_promise_release.pot
  sale_stock_available_to_promise_release/models/__init__.py
  sale_stock_available_to_promise_release/models/procurement_group.py
  sale_stock_available_to_promise_release/models/product_product.py
  sale_stock_available_to_promise_release/models/sale_order.py
  sale_stock_available_to_promise_release/models/sale_order_line.py
  sale_stock_available_to_promise_release/models/stock_move.py
  sale_stock_available_to_promise_release/models/stock_picking.py
  sale_stock_available_to_promise_release/readme/CONTRIBUTORS.rst
  sale_stock_available_to_promise_release/readme/CREDITS.rst
  sale_stock_available_to_promise_release/readme/DESCRIPTION.rst
  sale_stock_available_to_promise_release/reports/sale_order.xml
  sale_stock_available_to_promise_release/static/description/icon.png
  sale_stock_available_to_promise_release/static/description/index.html
  sale_stock_available_to_promise_release/tests/__init__.py
  sale_stock_available_to_promise_release/tests/common.py
  sale_stock_available_to_promise_release/tests/test_sale_line_availability_status.py
  sale_stock_available_to_promise_release/views/product_product_views.xml
  sale_stock_available_to_promise_release/views/sale_order_views.xml
  sale_stock_available_to_promise_release/views/stock_move_views.xml
  sale_stock_available_to_promise_release/views/stock_picking_views.xml
  setup/sale_stock_available_to_promise_release/odoo/addons/sale_stock_available_to_promise_release
  setup/sale_stock_available_to_promise_release/setup.py
Labels: approved, bot is merging ⏳

#866 [14.0][IMP] sale_stock_available_to_promise_release: Add delayed_qty on SO line
  sale_stock_available_to_promise_release/models/sale_order_line.py
  sale_stock_available_to_promise_release/tests/test_sale_line_availability_status.py
Labels: ready to merge, approved, bot is merging ⏳

#878 [16.0][IMP] stock_release_channel: Set default state to asleep and add new criteria to disable pickings from being automatically assigned
  stock_release_channel/demo/stock_release_channel.xml
  stock_release_channel/models/stock_picking.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/common.py
  stock_release_channel/tests/test_release_channel.py
  stock_release_channel/views/stock_release_channel_views.xml
  stock_release_channel_process_end_time/tests/test_release_end_date.py
  stock_release_channel_propagate_channel_picking/tests/test_procurement.py
Labels: approved, bot is merging ⏳
