Repository OCA/wms, pull requests merged in 2024-08, with the labels that each got.

#923 [16.0][IMP] stock_release_channel_auto_release: Remove move delay methods
  stock_release_channel_auto_release/__manifest__.py
  stock_release_channel_auto_release/data/queue_job_data.xml
  stock_release_channel_auto_release/models/stock_picking.py
  stock_release_channel_auto_release/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#924 [14.0][IMP] stock_reception_screen: Add index to last_move_line_lot_id
  stock_reception_screen/models/stock_move.py
Labels: approved, bot is merging ⏳

#835 [14.0][IMP] shopfloor: add option to exclude package types in product info
  setup/shopfloor_reception_vendor_packaging/odoo/addons/shopfloor_reception_vendor_packaging
  setup/shopfloor_reception_vendor_packaging/setup.py
  setup/shopfloor_vendor_packaging/odoo/addons/shopfloor_vendor_packaging
  setup/shopfloor_vendor_packaging/setup.py
  shopfloor_reception_vendor_packaging/README.rst
  shopfloor_reception_vendor_packaging/__init__.py
  shopfloor_reception_vendor_packaging/__manifest__.py
  shopfloor_reception_vendor_packaging/post_init_hook.py
  shopfloor_reception_vendor_packaging/readme/CONTRIBUTORS.rst
  shopfloor_reception_vendor_packaging/readme/DESCRIPTION.rst
  shopfloor_reception_vendor_packaging/services/__init__.py
  shopfloor_reception_vendor_packaging/services/reception.py
  shopfloor_vendor_packaging/README.rst
  shopfloor_vendor_packaging/__init__.py
  shopfloor_vendor_packaging/__manifest__.py
  shopfloor_vendor_packaging/actions/__init__.py
  shopfloor_vendor_packaging/actions/data.py
  shopfloor_vendor_packaging/models/__init__.py
  shopfloor_vendor_packaging/models/shopfloor_menu.py
  shopfloor_vendor_packaging/readme/CONTRIBUTORS.rst
  shopfloor_vendor_packaging/readme/DESCRIPTION.rst
  shopfloor_vendor_packaging/tests/__init__.py
  shopfloor_vendor_packaging/tests/test_shopfloor_vendor_packaging.py
  shopfloor_vendor_packaging/views/shopfloor_menu.xml
Labels: bot is merging ⏳, stale

#919 [FIX] shopfloor: fix location content transfer complete message
  shopfloor/actions/message.py
Labels: ready to merge, approved, bot is merging ⏳

#918 [IMP] shopfloor: search product by default code if barcode is null
  shopfloor_mobile/static/wms/src/wms_utils.js
Labels: bot is merging ⏳
