Repository OCA/wms, pull requests merged in 2024-12, with the labels that each got.

#903 [16.0][IMP] sale_stock_available_to_promise_release mto availability_status
  sale_stock_available_to_promise_release/models/sale_order_line.py
Labels: ready to merge, approved, bot is merging ⏳

#961 [14.0][FIX] delivery_carrier_preference: fix perf issue when editing packaging from product form
  delivery_carrier_preference/models/stock_move.py
Labels: approved, bot is merging ⏳

#937 [16.0][FIX] stock_available_to_promise_release: normal outgoing moves are mergeable
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_merge_moves.py
Labels: enhancement, ready to merge, approved, bot is merging ⏳

#953 [16.0][FIX] shopfloor: fix create return move and move lines sort
  shopfloor/actions/move_line_search.py
  shopfloor/actions/stock.py
Labels: approved, bot is merging ⏳

#963 [18.0][MIG] delivery_carrier_warehouse: Migration to 18.0
  delivery_carrier_warehouse/README.rst
  delivery_carrier_warehouse/__init__.py
  delivery_carrier_warehouse/__manifest__.py
  delivery_carrier_warehouse/i18n/delivery_carrier_warehouse.pot
  delivery_carrier_warehouse/i18n/es_AR.po
  delivery_carrier_warehouse/i18n/it.po
  delivery_carrier_warehouse/models/__init__.py
  delivery_carrier_warehouse/models/sale_order.py
  delivery_carrier_warehouse/models/stock_warehouse.py
  delivery_carrier_warehouse/pyproject.toml
  delivery_carrier_warehouse/readme/CONTRIBUTORS.md
  delivery_carrier_warehouse/readme/CREDITS.md
  delivery_carrier_warehouse/readme/DESCRIPTION.md
  delivery_carrier_warehouse/static/description/icon.png
  delivery_carrier_warehouse/static/description/index.html
  delivery_carrier_warehouse/tests/__init__.py
  delivery_carrier_warehouse/tests/test_delivery_carrier_warehouse.py
  delivery_carrier_warehouse/views/stock_warehouse.xml
Labels: approved, bot is merging ⏳
