Repository OCA/wms, pull requests merged in 2024-06, with the labels that each got.

#905 [16.0][FIX] stock_available_to_promise_release : unrelease when no pick left
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease.py
Labels: ready to merge, approved, bot is merging ⏳

#904 [16.0][FIX] stock_available_to_promise_release : cancellation must unrelease
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease.py
  stock_available_to_promise_release/tests/test_unrelease_2steps.py
Labels: ready to merge, approved, bot is merging ⏳

#712 [14.0] shopfloor: checkout scan change lot (rebased)
  shopfloor/actions/change_package_lot.py
  shopfloor/actions/message.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_scan_line.py
  shopfloor_mobile/static/wms/src/scenario/checkout_states.js
Labels: bot is merging ⏳

#894 [16.0][IMP] stock_available_to_promise_release: Improves perfs
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
Labels: approved, bot is merging ⏳

#879 [14.0][IMP] shopfloor: Zone picking - set destination location check into own method
  shopfloor/services/zone_picking.py
Labels: approved, bot is merging ⏳

#896 [16.0][IMP] sale_stock_available_to_promise_release: show/hide availability on SO reports
  sale_stock_available_to_promise_release/__manifest__.py
  sale_stock_available_to_promise_release/models/__init__.py
  sale_stock_available_to_promise_release/models/res_company.py
  sale_stock_available_to_promise_release/models/res_config_settings.py
  sale_stock_available_to_promise_release/reports/sale_order.xml
  sale_stock_available_to_promise_release/views/res_config_settings.xml
Labels: ready to merge, approved, bot is merging ⏳

#883 [16.0][IMP] stock_release_channel: add smart buttons on channel form view
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/test_channel_action.py
  stock_release_channel/views/stock_release_channel_views.xml
Labels: ready to merge, approved, bot is merging ⏳

#832 [FIX] stock_available_to_promise_release: Fix priority
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_reservation.py
Labels: needs review, bot is merging ⏳

#910 [IMP] stock_release_channel: picking form view, no quick create
  stock_release_channel/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#893 [17.0][MIG] stock_warehouse_flow: Migration to 17.0
  stock_warehouse_flow/README.rst
  stock_warehouse_flow/__init__.py
  stock_warehouse_flow/__manifest__.py
  stock_warehouse_flow/demo/stock_warehouse_flow.xml
  stock_warehouse_flow/i18n/es.po
  stock_warehouse_flow/i18n/it.po
  stock_warehouse_flow/i18n/stock_warehouse_flow.pot
  stock_warehouse_flow/models/__init__.py
  stock_warehouse_flow/models/delivery_carrier.py
  stock_warehouse_flow/models/stock_move.py
  stock_warehouse_flow/models/stock_route.py
  stock_warehouse_flow/models/stock_warehouse.py
  stock_warehouse_flow/models/stock_warehouse_flow.py
  stock_warehouse_flow/pyproject.toml
  stock_warehouse_flow/readme/CONFIGURE.md
  stock_warehouse_flow/readme/CONTRIBUTORS.md
  stock_warehouse_flow/readme/DESCRIPTION.md
  stock_warehouse_flow/readme/ROADMAP.md
  stock_warehouse_flow/readme/USAGE.md
  stock_warehouse_flow/security/ir.model.access.csv
  stock_warehouse_flow/static/description/config.png
  stock_warehouse_flow/static/description/flow.png
  stock_warehouse_flow/static/description/icon.png
  stock_warehouse_flow/static/description/index.html
  stock_warehouse_flow/tests/__init__.py
  stock_warehouse_flow/tests/common.py
  stock_warehouse_flow/tests/test_delivery_carrier.py
  stock_warehouse_flow/tests/test_warehouse.py
  stock_warehouse_flow/tests/test_warehouse_flow.py
  stock_warehouse_flow/views/delivery_carrier.xml
  stock_warehouse_flow/views/stock_route.xml
  stock_warehouse_flow/views/stock_warehouse.xml
  stock_warehouse_flow/views/stock_warehouse_flow.xml
Labels: ready to merge, approved, bot is merging ⏳

#833 [FIX] stock_release_channel: Don't assign first a release channel if it will be filtered
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/test_release_channel.py
Labels: needs review, approved, bot is merging ⏳
