Repository OCA/wms, pull requests merged in 2024-02, with the labels that each got.

#818 [14.0][IMP] stock_available_to_promise_release: Multi warehouse capability
  stock_available_to_promise_release/README.rst
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/readme/DESCRIPTION.rst
  stock_available_to_promise_release/static/description/index.html
  stock_available_to_promise_release/tests/test_reservation.py
Labels: approved, bot is merging ⏳

#813 [16.0][IMP] stock_release_channel: track `release_channel_id` on `stock.picking`
  stock_release_channel/models/stock_picking.py
Labels: approved, bot is merging ⏳

#799 [IMP] add process_end_date to release channel order
  stock_release_channel_process_end_time/models/stock_release_channel.py
Labels: ready to merge, approved, bot is merging ⏳

#849 [16.0] stock_warehouse_flow: enable auto-created locations
  stock_warehouse_flow/models/stock_warehouse_flow.py
Labels: bug, approved, bot is merging ⏳

#850 [16.0][FIX] stock_available_to_promise_release: fix cache and failing tests
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_picking.py
  stock_release_channel_auto_release/tests/test_channel_release_auto.py
Labels: approved, merged 🎉
