Repository OCA/wms, pull requests merged in 2024-11, with the labels that each got.

#942 [IMP] shopfloor: Give user better information about the problematic line
  shopfloor/actions/message.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#945 [14.0][IMP] shopfloor: change_package_lot action, add after assign hook
  shopfloor/actions/change_package_lot.py
Labels: approved, bot is merging ⏳

#940 [14.0][BACKPORT] stock_available_to_promise_release_exclude_location
  setup/stock_available_to_promise_release_exclude_location/odoo/addons/stock_available_to_promise_release_exclude_location
  setup/stock_available_to_promise_release_exclude_location/setup.py
  stock_available_to_promise_release_exclude_location/README.rst
  stock_available_to_promise_release_exclude_location/__init__.py
  stock_available_to_promise_release_exclude_location/__manifest__.py
  stock_available_to_promise_release_exclude_location/i18n/it.po
  stock_available_to_promise_release_exclude_location/i18n/stock_available_to_promise_release_exclude_location.pot
  stock_available_to_promise_release_exclude_location/models/__init__.py
  stock_available_to_promise_release_exclude_location/models/stock_location.py
  stock_available_to_promise_release_exclude_location/readme/DESCRIPTION.rst
  stock_available_to_promise_release_exclude_location/static/description/icon.png
  stock_available_to_promise_release_exclude_location/static/description/index.html
  stock_available_to_promise_release_exclude_location/tests/__init__.py
  stock_available_to_promise_release_exclude_location/tests/test_exclude_location.py
Labels: ready to merge, approved, bot is merging ⏳

#950 [14.0][FIX] shopfloor: cluster_picking do not create a new move line
  shopfloor/services/cluster_picking.py
  shopfloor/tests/test_cluster_picking_scan_destination_no_prefill_qty.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#946 [16.0][FW] shopfloor_base: Blacklist of some PRs from 14.0
  .oca/oca-port/blacklist/shopfloor_base.json
Labels: ready to merge, approved

#948 [16.0][FW] stock_storage_type: port changes from 14
  .oca/oca-port/blacklist/stock_storage_type.json
Labels: bot is merging ⏳
