Repository OCA/wms, pull requests merged in 2024-09, with the labels that each got.

#838 [16.0] [sale_]stock_release_channel_partner_by_date: set a release channel for a specific delivery address and date
  sale_stock_release_channel_partner_by_date/README.rst
  sale_stock_release_channel_partner_by_date/__init__.py
  sale_stock_release_channel_partner_by_date/__manifest__.py
  sale_stock_release_channel_partner_by_date/models/__init__.py
  sale_stock_release_channel_partner_by_date/models/sale_order.py
  sale_stock_release_channel_partner_by_date/readme/CONTRIBUTORS.rst
  sale_stock_release_channel_partner_by_date/readme/DESCRIPTION.rst
  sale_stock_release_channel_partner_by_date/readme/USAGE.rst
  sale_stock_release_channel_partner_by_date/security/ir_model_access.xml
  sale_stock_release_channel_partner_by_date/static/description/index.html
  sale_stock_release_channel_partner_by_date/tests/__init__.py
  sale_stock_release_channel_partner_by_date/tests/common.py
  sale_stock_release_channel_partner_by_date/tests/test_sale_release_channel.py
  sale_stock_release_channel_partner_by_date/views/sale_order.xml
  sale_stock_release_channel_partner_by_date_delivery/README.rst
  sale_stock_release_channel_partner_by_date_delivery/__init__.py
  sale_stock_release_channel_partner_by_date_delivery/__manifest__.py
  sale_stock_release_channel_partner_by_date_delivery/models/__init__.py
  sale_stock_release_channel_partner_by_date_delivery/models/sale_order.py
  sale_stock_release_channel_partner_by_date_delivery/readme/CONTRIBUTORS.rst
  sale_stock_release_channel_partner_by_date_delivery/readme/DESCRIPTION.rst
  sale_stock_release_channel_partner_by_date_delivery/static/description/index.html
  sale_stock_release_channel_partner_by_date_delivery/tests/__init__.py
  sale_stock_release_channel_partner_by_date_delivery/tests/test_sale_release_channel.py
  sale_stock_release_channel_partner_by_date_delivery/views/sale_order.xml
  setup/sale_stock_release_channel_partner_by_date/odoo/addons/sale_stock_release_channel_partner_by_date
  setup/sale_stock_release_channel_partner_by_date/setup.py
  setup/sale_stock_release_channel_partner_by_date_delivery/odoo/addons/sale_stock_release_channel_partner_by_date_delivery
  setup/sale_stock_release_channel_partner_by_date_delivery/setup.py
  setup/stock_release_channel_partner_by_date/odoo/addons/stock_release_channel_partner_by_date
  setup/stock_release_channel_partner_by_date/setup.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel/tests/test_release_channel_partner.py
  stock_release_channel_delivery/models/stock_picking.py
  stock_release_channel_geoengine/models/stock_picking.py
  stock_release_channel_partner_by_date/README.rst
  stock_release_channel_partner_by_date/__init__.py
  stock_release_channel_partner_by_date/__manifest__.py
  stock_release_channel_partner_by_date/models/__init__.py
  stock_release_channel_partner_by_date/models/res_partner.py
  stock_release_channel_partner_by_date/models/stock_picking.py
  stock_release_channel_partner_by_date/models/stock_release_channel.py
  stock_release_channel_partner_by_date/models/stock_release_channel_partner_date.py
  stock_release_channel_partner_by_date/readme/CONTRIBUTORS.rst
  stock_release_channel_partner_by_date/readme/DESCRIPTION.rst
  stock_release_channel_partner_by_date/security/stock_release_channel_partner_date.xml
  stock_release_channel_partner_by_date/static/description/index.html
  stock_release_channel_partner_by_date/tests/__init__.py
  stock_release_channel_partner_by_date/tests/test_release_channel_partner_date.py
  stock_release_channel_partner_by_date/views/res_partner.xml
  stock_release_channel_shipment_lead_time/models/stock_picking.py
  stock_storage_type/tests/test_storage_type_move.py
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳

#841 [14.0][ADD] stock_service_level
  setup/stock_service_level/odoo/addons/stock_service_level
  setup/stock_service_level/setup.py
  stock_service_level/README.rst
  stock_service_level/__init__.py
  stock_service_level/__manifest__.py
  stock_service_level/i18n/fr.po
  stock_service_level/i18n/stock_service_level.pot
  stock_service_level/models/__init__.py
  stock_service_level/models/stock_move.py
  stock_service_level/models/stock_rule.py
  stock_service_level/models/stock_service_level.py
  stock_service_level/readme/CONTRIBUTORS.rst
  stock_service_level/readme/DESCRIPTION.rst
  stock_service_level/security/ir.model.access.csv
  stock_service_level/static/description/index.html
  stock_service_level/tests/__init__.py
  stock_service_level/tests/common.py
  stock_service_level/tests/test_stock_service_level.py
  stock_service_level/views/stock_picking_views.xml
  stock_service_level/views/stock_service_level.xml
Labels: ready to merge, approved, bot is merging ⏳

#928 [FIX] stock_release_channel_shipment_advice_toursolver: Tests
  stock_release_channel_shipment_advice_toursolver/tests/cassettes/TestShipmentAdvicePlannerToursolver.test_plan_shipment_toursolver.yaml
Labels: bot is merging ⏳

#929 [ADD] stock_service_level_route: restrict route by service level
  setup/stock_service_level_route/odoo/addons/stock_service_level_route
  setup/stock_service_level_route/setup.py
  stock_service_level_route/README.rst
  stock_service_level_route/__init__.py
  stock_service_level_route/__manifest__.py
  stock_service_level_route/i18n/fr.po
  stock_service_level_route/i18n/stock_service_level_route.pot
  stock_service_level_route/models/__init__.py
  stock_service_level_route/models/procurement_group.py
  stock_service_level_route/models/stock_location_route.py
  stock_service_level_route/models/stock_service_level.py
  stock_service_level_route/readme/CONFIGURATION.rst
  stock_service_level_route/readme/CONTRIBUTORS.rst
  stock_service_level_route/readme/DESCRIPTION.rst
  stock_service_level_route/static/description/index.html
  stock_service_level_route/tests/__init__.py
  stock_service_level_route/tests/test_stock_service_level_route.py
  stock_service_level_route/views/stock_location_route_views.xml
  stock_service_level_route/views/stock_service_level_views.xml
Labels: ready to merge, approved, bot is merging ⏳
