Repository OCA/wms, pull requests merged in 2024-10, with the labels that each got.

#921 [IMP] stock_available_to_promise_release: Extract method to check pickings in progress
  stock_available_to_promise_release/models/stock_move.py
Labels: approved, bot is merging ⏳

#920 [FIX] stock_available_to_promise_release: avoid infinite loop at chained moves iterator
  stock_available_to_promise_release/models/stock_move.py
Labels: enhancement, ready to merge, approved, bot is merging ⏳

#911 [16.0][FIX] shopfloor: Don't embed postponed line quantity
  shopfloor/models/stock_move_line.py
  shopfloor/tests/test_location_content_transfer_base.py
  shopfloor/tests/test_location_content_transfer_single.py
Labels: enhancement, needs review, bot is merging ⏳

#907 [14.0][REF] shopfloor_reception
  shopfloor_reception/services/reception.py
Labels: approved, bot is merging ⏳

#873 [14.0][FIX] s_a_promise_release: Reset last_release_date on unrelease
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease.py
Labels: enhancement, needs review, approved, bot is merging ⏳, stale

#912 [16.0] shopfloor cluster_picking: Custom sorting by device
  shopfloor/services/cluster_picking.py
  shopfloor_batch_automatic_creation/__manifest__.py
  shopfloor_batch_automatic_creation/models/__init__.py
  shopfloor_batch_automatic_creation/models/stock_device_type.py
  shopfloor_batch_automatic_creation/services/cluster_picking.py
  shopfloor_batch_automatic_creation/tests/test_batch_create.py
  shopfloor_batch_automatic_creation/views/stock_device_type.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#819 [16.0][ADD] stock_release_channel_shipment_advice_deliver
  setup/stock_release_channel_shipment_advice_deliver/odoo/addons/stock_release_channel_shipment_advice_deliver
  setup/stock_release_channel_shipment_advice_deliver/setup.py
  stock_available_to_promise_release/models/stock_move.py
  stock_release_channel/i18n/fr.po
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel_shipment_advice_deliver/README.rst
  stock_release_channel_shipment_advice_deliver/__init__.py
  stock_release_channel_shipment_advice_deliver/__manifest__.py
  stock_release_channel_shipment_advice_deliver/data/queue_job_channel.xml
  stock_release_channel_shipment_advice_deliver/data/queue_job_function.xml
  stock_release_channel_shipment_advice_deliver/i18n/fr.po
  stock_release_channel_shipment_advice_deliver/models/__init__.py
  stock_release_channel_shipment_advice_deliver/models/shipment_advice.py
  stock_release_channel_shipment_advice_deliver/models/stock_picking.py
  stock_release_channel_shipment_advice_deliver/models/stock_release_channel.py
  stock_release_channel_shipment_advice_deliver/readme/CONTRIBUTORS
  stock_release_channel_shipment_advice_deliver/readme/DESCRIPTION.rst
  stock_release_channel_shipment_advice_deliver/readme/USAGE.rst
  stock_release_channel_shipment_advice_deliver/security/stock_release_channel_deliver_check_wizard.xml
  stock_release_channel_shipment_advice_deliver/static/description/index.html
  stock_release_channel_shipment_advice_deliver/tests/__init__.py
  stock_release_channel_shipment_advice_deliver/tests/common.py
  stock_release_channel_shipment_advice_deliver/tests/test_stock_release_channel_deliver.py
  stock_release_channel_shipment_advice_deliver/tests/test_stock_release_channel_deliver_async.py
  stock_release_channel_shipment_advice_deliver/views/stock_release_channel.xml
  stock_release_channel_shipment_advice_deliver/wizards/__init__.py
  stock_release_channel_shipment_advice_deliver/wizards/stock_release_channel_deliver_check_wizard.py
  stock_release_channel_shipment_advice_deliver/wizards/stock_release_channel_deliver_check_wizard.xml
Labels: ready to merge, needs review, approved, bot is merging ⏳

#645 [14.0][ADD] shopfloor location content transfer scan dest package
  setup/shopfloor_location_content_transfer_force_package/odoo/addons/shopfloor_location_content_transfer_force_package
  setup/shopfloor_location_content_transfer_force_package/setup.py
  shopfloor/actions/message.py
  shopfloor/services/location_content_transfer.py
  shopfloor/tests/test_location_content_transfer_base.py
  shopfloor/tests/test_location_content_transfer_set_destination_as_package.py
  shopfloor/tests/test_location_content_transfer_set_destination_package_or_line.py
  shopfloor_checkout_sync/services/location_content_transfer.py
  shopfloor_location_content_transfer_force_package/README.rst
  shopfloor_location_content_transfer_force_package/__init__.py
  shopfloor_location_content_transfer_force_package/__manifest__.py
  shopfloor_location_content_transfer_force_package/readme/CONTRIBUTORS.rst
  shopfloor_location_content_transfer_force_package/readme/DESCRIPTION.rst
  shopfloor_location_content_transfer_force_package/services/__init__.py
  shopfloor_location_content_transfer_force_package/services/location_content_transfer.py
  shopfloor_location_content_transfer_force_package/static/description/index.html
  shopfloor_location_content_transfer_force_package/tests/__init__.py
  shopfloor_location_content_transfer_force_package/tests/test_location_content_transfer_force_package.py
  shopfloor_mobile/static/wms/src/i18n/en.json
  shopfloor_mobile/static/wms/src/i18n/fr.json
  shopfloor_mobile/static/wms/src/scenario/location_content_transfer.js
Labels: bot is merging ⏳, no stale

#901 [FIX] sale_stock_available_to_promise_release MTO sale availability status
  sale_stock_available_to_promise_release/models/sale_order_line.py
Labels: bot is merging ⏳

#931 [IMP] stock_available_to_promise_release: Improve migration/init script to initialize field with default values
  requirements.txt
  stock_available_to_promise_release/__init__.py
  stock_available_to_promise_release/__manifest__.py
  stock_available_to_promise_release/hooks.py
  stock_available_to_promise_release/migrations/16.0.3.1.0/pre-migrate.py
Labels: bot is merging ⏳

#917 [16.0] shopfloor: location_content_transfer: get_work additional domain and sort key.
  shopfloor/__manifest__.py
  shopfloor/actions/move_line_search.py
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/migrations/16.0.2.2.1/post-init_search_move_line_options.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/menu.py
  shopfloor/services/service.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_actions_search_move_line.py
  shopfloor/tests/test_location_content_transfer_get_work.py
  shopfloor/tests/test_location_content_transfer_mix.py
  shopfloor/tests/test_menu_contrains.py
  shopfloor/tests/test_menu_counters.py
  shopfloor/views/shopfloor_menu.xml
Labels: enhancement, needs review, bot is merging ⏳

#834 [16.0][IMP] stock_available_to_promise_release: Unrelease when merging moves
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/test_merge_moves.py
Labels: enhancement, needs review, approved, bot is merging ⏳, stale

#899 [16.0] shopfloor: Extended details service for products and locations
  shopfloor/actions/data_detail.py
  shopfloor/actions/schema_detail.py
  shopfloor/tests/test_actions_data_base.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_mobile/static/wms/src/components/detail/detail_location.js
  shopfloor_mobile/static/wms/src/components/detail/detail_lot.js
  shopfloor_mobile/static/wms/src/components/detail/detail_product.js
Labels: enhancement, ready to merge, needs review, approved, bot is merging ⏳
