Repository OCA/wms, pull requests merged in 2025-04, with the labels that each got.

#971 [14.0] stock_available_to_promise_release: Allow unrelease processed qties
  stock_available_to_promise_release/models/stock_location_route.py
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_rule.py
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_unrelease_cancel.py
  stock_available_to_promise_release/views/stock_location_route_views.xml
Labels: approved, bot is merging ⏳

#1000 [14.0][ADD] stock_available_to_promise_release_shipment_advice
  setup/stock_available_to_promise_release_shipment_advice/odoo/addons/stock_available_to_promise_release_shipment_advice
  setup/stock_available_to_promise_release_shipment_advice/setup.py
  stock_available_to_promise_release_shipment_advice/README.rst
  stock_available_to_promise_release_shipment_advice/__init__.py
  stock_available_to_promise_release_shipment_advice/__manifest__.py
  stock_available_to_promise_release_shipment_advice/models/__init__.py
  stock_available_to_promise_release_shipment_advice/models/stock_move.py
  stock_available_to_promise_release_shipment_advice/readme/CONTRIBUTORS.rst
  stock_available_to_promise_release_shipment_advice/readme/DESCRIPTION.rst
  stock_available_to_promise_release_shipment_advice/static/description/index.html
  stock_available_to_promise_release_shipment_advice/tests/__init__.py
  stock_available_to_promise_release_shipment_advice/tests/test_unrelease_cancel.py
Labels: approved, bot is merging ⏳

#952 [16.0][MIG] shopfloor_reception_mobile
  setup/shopfloor_reception_mobile/odoo/addons/shopfloor_reception_mobile
  setup/shopfloor_reception_mobile/setup.py
  shopfloor_reception_mobile/README.rst
  shopfloor_reception_mobile/__init__.py
  shopfloor_reception_mobile/__manifest__.py
  shopfloor_reception_mobile/i18n/it.po
  shopfloor_reception_mobile/i18n/shopfloor_reception_mobile.pot
  shopfloor_reception_mobile/readme/CONTRIBUTORS.rst
  shopfloor_reception_mobile/readme/DESCRIPTION.rst
  shopfloor_reception_mobile/static/description/icon.png
  shopfloor_reception_mobile/static/description/index.html
  shopfloor_reception_mobile/static/src/demo/demo.reception.js
  shopfloor_reception_mobile/static/src/scenario/reception.js
  shopfloor_reception_mobile/static/src/scenario/reception_states.js
  shopfloor_reception_mobile/templates/assets.xml
Labels: migration, ready to merge, needs review, approved, bot is merging ⏳

#1010 [16.0][MIG] stock_warehouse_flow_release
  setup/stock_warehouse_flow_release/odoo/addons/stock_warehouse_flow_release
  setup/stock_warehouse_flow_release/setup.py
  stock_warehouse_flow_release/README.rst
  stock_warehouse_flow_release/__init__.py
  stock_warehouse_flow_release/__manifest__.py
  stock_warehouse_flow_release/i18n/it.po
  stock_warehouse_flow_release/i18n/stock_warehouse_flow_release.pot
  stock_warehouse_flow_release/models/__init__.py
  stock_warehouse_flow_release/models/stock_move.py
  stock_warehouse_flow_release/readme/CONTRIBUTORS.rst
  stock_warehouse_flow_release/readme/DESCRIPTION.rst
  stock_warehouse_flow_release/static/description/icon.png
  stock_warehouse_flow_release/static/description/index.html
  stock_warehouse_flow_release/tests/__init__.py
  stock_warehouse_flow_release/tests/test_warehouse_flow_release.py
Labels: bot is merging ⏳

#1016 [FIX] shopfloor_reception_mobile: Make product info works on picking detail
  shopfloor_reception_mobile/static/src/scenario/reception.js
Labels: needs review, approved, bot is merging ⏳

#1009 [16.0][FW PORT] stock_available_to_promise_release: Allow unrelease processed qties
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/models/stock_route.py
  stock_available_to_promise_release/models/stock_rule.py
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/common.py
  stock_available_to_promise_release/tests/test_reservation.py
  stock_available_to_promise_release/tests/test_unrelease_cancel.py
  stock_available_to_promise_release/views/stock_route_views.xml
Labels: bot is merging ⏳

#1017 [FW PORT][16.0] shopfloor: better messages when transfer has been cancel and product is reserved by a return
  shopfloor/actions/message.py
  shopfloor/actions/stock_unreserve.py
  shopfloor/services/checkout.py
  shopfloor/services/delivery.py
  shopfloor/services/location_content_transfer.py
  shopfloor/services/service.py
  shopfloor/tests/test_checkout_scan.py
  shopfloor/tests/test_checkout_scan_line.py
  shopfloor/tests/test_checkout_select.py
  shopfloor/tests/test_delivery_scan_deliver.py
  shopfloor/tests/test_delivery_set_qty_done_line.py
  shopfloor/tests/test_delivery_set_qty_done_pack.py
  shopfloor/tests/test_location_content_transfer_start.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_return_scan_line.py
Labels: approved, bot is merging ⏳
