Repository OCA/wms, pull requests merged in 2025-05, with the labels that each got.

#999 [16.0][FIX] stock_release_channel_partner_by_date: properly detect the exception
  sale_stock_release_channel_partner_by_date_delivery/tests/test_sale_release_channel.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel_partner_by_date/tests/common.py
  stock_release_channel_partner_by_date/tests/test_release_channel_partner_date.py
  stock_release_channel_shipment_lead_time/models/stock_picking.py
Labels: ready to merge, approved, bot is merging ⏳, no stale

#1031 [14.0][IMP] stock_available_to_promise_release: Do not copy picking responsible to cancel picking
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease_cancel.py
Labels: approved, bot is merging ⏳

#1015 [14.0][BACKPORT] stock_available_to_promise_release : backport fixes for unrelease from 16.0
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease.py
Labels: merged 🎉

#1034 [16.0][IMP] stock_available_to_promise_release: Do not copy picking responsible to cancel picking
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease_cancel.py
Labels: approved, bot is merging ⏳

#1025 [16.0][FIX] stock_release_channel_partner_delivery_window: Fix channel assignment computation
  stock_release_channel_partner_delivery_window/__manifest__.py
  stock_release_channel_partner_delivery_window/models/stock_release_channel.py
  stock_release_channel_partner_delivery_window/readme/USAGE.rst
  stock_release_channel_partner_delivery_window/tests/test_release_window.py
Labels: bot is merging ⏳

#1035 [16.0][IMP] stock_release_channel* : cleanup candidate domains
  stock_release_channel/models/res_partner.py
  stock_release_channel/models/stock_picking.py
  stock_release_channel_delivery/models/stock_picking.py
  stock_release_channel_geoengine/models/__init__.py
  stock_release_channel_geoengine/models/res_partner.py
  stock_release_channel_geoengine/models/stock_picking.py
  stock_release_channel_partner_by_date/models/stock_picking.py
  stock_release_channel_partner_by_date/tests/common.py
  stock_release_channel_partner_by_date_public_holidays/tests/test_release_channel_partner_date.py
  stock_release_channel_partner_delivery_window/__manifest__.py
  stock_release_channel_partner_delivery_window/models/stock_picking.py
  stock_release_channel_partner_delivery_window/models/stock_release_channel.py
  stock_release_channel_partner_public_holidays/models/stock_picking.py
  stock_release_channel_shipment_advice_deliver/models/__init__.py
  stock_release_channel_shipment_advice_deliver/models/stock_picking.py
  stock_release_channel_shipment_lead_time/models/stock_picking.py
Labels: approved, bot is merging ⏳

#1038 [16.0][FIX] stock_release_channel_partner_by_date: show archived
  stock_release_channel_partner_by_date/models/res_partner.py
  stock_release_channel_partner_by_date/views/res_partner.xml
Labels: bot is merging ⏳

#1037 [16.0][ADD] stock_release_channel_partner_by_date_delivery_window : add tests
  setup/stock_release_channel_partner_by_date_delivery_window/odoo/addons/stock_release_channel_partner_by_date_delivery_window
  setup/stock_release_channel_partner_by_date_delivery_window/setup.py
  stock_release_channel_partner_by_date_delivery_window/README.rst
  stock_release_channel_partner_by_date_delivery_window/__init__.py
  stock_release_channel_partner_by_date_delivery_window/__manifest__.py
  stock_release_channel_partner_by_date_delivery_window/readme/CONTRIBUTORS.rst
  stock_release_channel_partner_by_date_delivery_window/readme/DESCRIPTION.rst
  stock_release_channel_partner_by_date_delivery_window/static/description/index.html
  stock_release_channel_partner_by_date_delivery_window/tests/__init__.py
  stock_release_channel_partner_by_date_delivery_window/tests/test_release_channel_partner_date.py
Labels: bot is merging ⏳

#916 [16.0][ADD] stock_release_channel_plan_depot
  setup/stock_release_channel_plan_depot/odoo/addons/stock_release_channel_plan_depot
  setup/stock_release_channel_plan_depot/setup.py
  stock_release_channel_plan_depot/README.rst
  stock_release_channel_plan_depot/__init__.py
  stock_release_channel_plan_depot/__manifest__.py
  stock_release_channel_plan_depot/i18n/fr.po
  stock_release_channel_plan_depot/i18n/stock_release_channel_plan_depot.pot
  stock_release_channel_plan_depot/models/__init__.py
  stock_release_channel_plan_depot/models/stock_release_channel_preparation_plan.py
  stock_release_channel_plan_depot/readme/CONTRIBUTORS.rst
  stock_release_channel_plan_depot/readme/DESCRIPTION.rst
  stock_release_channel_plan_depot/static/description/index.html
  stock_release_channel_plan_depot/views/stock_release_channel_preparation_plan.xml
Labels: ready to merge, approved, bot is merging ⏳, blocked by dependency, no stale

#1022 [16.0][ADD] sale_stock_release_channel_delivery_date: add delivery date computation
  sale_stock_release_channel_delivery_date/README.rst
  sale_stock_release_channel_delivery_date/__init__.py
  sale_stock_release_channel_delivery_date/__manifest__.py
  sale_stock_release_channel_delivery_date/models/__init__.py
  sale_stock_release_channel_delivery_date/models/sale_order.py
  sale_stock_release_channel_delivery_date/models/sale_order_line.py
  sale_stock_release_channel_delivery_date/readme/CONTRIBUTORS.rst
  sale_stock_release_channel_delivery_date/readme/DESCRIPTION.rst
  sale_stock_release_channel_delivery_date/static/description/index.html
  sale_stock_release_channel_delivery_date/tests/__init__.py
  sale_stock_release_channel_delivery_date/tests/test_delivery_date.py
  setup/sale_stock_release_channel_delivery_date/odoo/addons/sale_stock_release_channel_delivery_date
  setup/sale_stock_release_channel_delivery_date/setup.py
  stock_release_channel/models/stock_release_channel.py
  stock_release_channel/tests/__init__.py
  stock_release_channel/tests/common.py
  stock_release_channel/tests/models/__init__.py
  stock_release_channel/tests/models/generator_test.py
  stock_release_channel/tests/test_release_channel_delivery_date.py
Labels: approved, bot is merging ⏳
