Repository OCA/wms, pull requests merged in 2025-01, with the labels that each got.

#957 [16.0][FIX] stock_available_to_promise_release: fix view
  stock_available_to_promise_release/views/stock_move_views.xml
Labels: bot is merging ⏳

#965 [16.0][PERF] stock_release_channel: kanban display performance
  stock_release_channel/models/stock_release_channel.py
Labels: approved, bot is merging ⏳

#951 [16.0][MIG] shopfloor_reception
  setup/shopfloor_reception/odoo/addons/shopfloor_reception
  setup/shopfloor_reception/setup.py
  shopfloor_reception/README.rst
  shopfloor_reception/__init__.py
  shopfloor_reception/__manifest__.py
  shopfloor_reception/data/shopfloor_scenario_data.xml
  shopfloor_reception/demo/shopfloor_menu_demo.xml
  shopfloor_reception/demo/stock_picking_type_demo.xml
  shopfloor_reception/docs/reception_sequence_graph.mermaid
  shopfloor_reception/docs/reception_sequence_graph.png
  shopfloor_reception/hooks.py
  shopfloor_reception/i18n/it.po
  shopfloor_reception/i18n/shopfloor_reception.pot
  shopfloor_reception/models/__init__.py
  shopfloor_reception/models/stock_picking.py
  shopfloor_reception/readme/CONTRIBUTORS.rst
  shopfloor_reception/readme/DESCRIPTION.rst
  shopfloor_reception/readme/ROADMAP.rst
  shopfloor_reception/services/__init__.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/static/description/icon.png
  shopfloor_reception/static/description/index.html
  shopfloor_reception/tests/__init__.py
  shopfloor_reception/tests/common.py
  shopfloor_reception/tests/reception_return_common.py
  shopfloor_reception/tests/test_manual_selection.py
  shopfloor_reception/tests/test_reception_done.py
  shopfloor_reception/tests/test_return_reception_done.py
  shopfloor_reception/tests/test_return_scan_document.py
  shopfloor_reception/tests/test_return_scan_line.py
  shopfloor_reception/tests/test_return_set_quantity.py
  shopfloor_reception/tests/test_select_dest_package.py
  shopfloor_reception/tests/test_select_document.py
  shopfloor_reception/tests/test_select_move.py
  shopfloor_reception/tests/test_set_destination.py
  shopfloor_reception/tests/test_set_lot.py
  shopfloor_reception/tests/test_set_lot_confirm.py
  shopfloor_reception/tests/test_set_quantity.py
  shopfloor_reception/tests/test_set_quantity_action.py
  shopfloor_reception/tests/test_start.py
Labels: migration, needs review, approved, bot is merging ⏳

#967 [16.0][FW] [14.0][FIX] stock_release_channel: _pickings_sort_key
  .oca/oca-port/blacklist/stock_release_channel.json
  stock_release_channel/models/stock_release_channel.py
Labels: approved, bot is merging ⏳, port

#827 [16.0][ADD] stock_release_channel_plan_shipment_lead_time
  setup/stock_release_channel_plan_shipment_lead_time/odoo/addons/stock_release_channel_plan_shipment_lead_time
  setup/stock_release_channel_plan_shipment_lead_time/setup.py
  stock_release_channel_plan_shipment_lead_time/README.rst
  stock_release_channel_plan_shipment_lead_time/__init__.py
  stock_release_channel_plan_shipment_lead_time/__manifest__.py
  stock_release_channel_plan_shipment_lead_time/models/__init__.py
  stock_release_channel_plan_shipment_lead_time/models/res_partner.py
  stock_release_channel_plan_shipment_lead_time/models/stock_release_channel.py
  stock_release_channel_plan_shipment_lead_time/readme/CONTRIBUTORS.rst
  stock_release_channel_plan_shipment_lead_time/readme/DESCRIPTION.rst
  stock_release_channel_plan_shipment_lead_time/static/description/index.html
  stock_release_channel_plan_shipment_lead_time/tests/__init__.py
  stock_release_channel_plan_shipment_lead_time/tests/test_lead_time_weekday.py
  stock_release_channel_plan_shipment_lead_time/views/release_channel.xml
Labels: bot is merging ⏳, no stale

#969 [16.0][FIX] stock_release_channel: do not `write` records in `_compute_picking_count`
  stock_release_channel/models/stock_release_channel.py
Labels: bug, approved, bot is merging ⏳

#970 [14.0][FW] [16.0][FIX] stock_release_channel: do not `write` records in `_compute_picking_count`
  stock_release_channel/models/stock_release_channel.py
Labels: bug, approved, bot is merging ⏳, port

#927 [14.0][IMP] stock_reception_screen_measuring_device: measure smaller packages
  stock_reception_screen_measuring_device/__manifest__.py
  stock_reception_screen_measuring_device/migrations/14.0.2.0.0/post-migration.py
  stock_reception_screen_measuring_device/migrations/14.0.2.0.0/pre-migration.py
  stock_reception_screen_measuring_device/models/stock_reception_screen.py
  stock_reception_screen_measuring_device/tests/__init__.py
  stock_reception_screen_measuring_device/tests/fake_components.py
  stock_reception_screen_measuring_device/tests/fake_models.py
  stock_reception_screen_measuring_device/tests/test_reception_screen_measurement.py
  stock_reception_screen_measuring_device/views/stock_reception_screen_view.xml
Labels: enhancement, ready to merge, approved, bot is merging ⏳

#902 [16.0][IMP] shopfloor: Zone picking no destination package required
  shopfloor/__manifest__.py
  shopfloor/data/shopfloor_scenario_data.xml
  shopfloor/migrations/16.0.2.4.2/post-init_search_move_line_options.py
  shopfloor/migrations/16.0.2.4.2/post-migration.py
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/__init__.py
  shopfloor/tests/test_zone_picking_require_destination_package.py
  shopfloor/tests/test_zone_picking_set_line_destination.py
  shopfloor/views/shopfloor_menu.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#959 [IMP] shopfloor_base: Don't filter for registry sync
  shopfloor_base/data/server_action.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#977 [16.0] shopfloor: checkout scan change lot - port of #712
  shopfloor/actions/change_package_lot.py
  shopfloor/actions/message.py
  shopfloor/services/checkout.py
  shopfloor/tests/test_checkout_base.py
  shopfloor/tests/test_checkout_scan_line.py
  shopfloor_mobile/static/wms/src/scenario/checkout_states.js
Labels: bot is merging ⏳
