Repository OCA/wms, pull requests merged in 2025-07, with the labels that each got.

#990 [IMP] stock_release_channel_shipment_advice_toursolver: link ts task to release channel
  stock_release_channel_shipment_advice_toursolver/models/__init__.py
  stock_release_channel_shipment_advice_toursolver/models/shipment_advice.py
  stock_release_channel_shipment_advice_toursolver/tests/test_shipment_advice_planner_toursolver.py
Labels: enhancement, approved, bot is merging ⏳

#1023 [IMP] shopfloor: Don't split operations at user assignation
  shopfloor/actions/stock.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1076 [16.0][FW] stock_available_to_promise_release: multiple ports from 14.0
  .oca/oca-port/blacklist/stock_available_to_promise_release.json
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/test_unrelease.py
  stock_available_to_promise_release/tests/test_unrelease_cancel.py
Labels: approved, bot is merging ⏳

#790 [14.0][ADD] stock_full_location_reservation: Extend reservation to full content of location
  setup/stock_full_location_reservation/odoo/addons/stock_full_location_reservation
  setup/stock_full_location_reservation/setup.py
  stock_full_location_reservation/README.rst
  stock_full_location_reservation/__init__.py
  stock_full_location_reservation/__manifest__.py
  stock_full_location_reservation/models/__init__.py
  stock_full_location_reservation/models/stock_move.py
  stock_full_location_reservation/models/stock_move_line.py
  stock_full_location_reservation/models/stock_picking.py
  stock_full_location_reservation/models/stock_picking_type.py
  stock_full_location_reservation/readme/CONFIGURE.rst
  stock_full_location_reservation/readme/CONTRIBUTORS.rst
  stock_full_location_reservation/readme/DESCRIPTION.rst
  stock_full_location_reservation/security/groups.xml
  stock_full_location_reservation/static/description/index.html
  stock_full_location_reservation/tests/__init__.py
  stock_full_location_reservation/tests/common.py
  stock_full_location_reservation/tests/test_full_location_reservation.py
  stock_full_location_reservation/views/stock_picking_type_views.xml
  stock_full_location_reservation/views/stock_picking_views.xml
Labels: ready to merge, needs review, approved, bot is merging ⏳, no stale
