Repository OCA/wms, pull requests merged in 2025-06, with the labels that each got.

#1027 [16.0][IMP] stock_release_channel_cutoff: delivery date generator
  stock_release_channel_cutoff/models/stock_release_channel.py
  stock_release_channel_cutoff/tests/test_compute_cutoff_time.py
Labels: bot is merging ⏳

#1032 [16.0][IMP] stock_release_channel_plan_shipment_lead_time: delivery date generator
  stock_release_channel_plan_shipment_lead_time/models/stock_release_channel.py
  stock_release_channel_plan_shipment_lead_time/tests/test_lead_time_weekday.py
Labels: approved, merged 🎉

#1030 [16.0][IMP] stock_release_channel_partner_public_holidays: delivery date generator
  stock_release_channel_partner_public_holidays/models/stock_release_channel.py
  stock_release_channel_partner_public_holidays/readme/CONTRIBUTORS.rst
  stock_release_channel_partner_public_holidays/tests/test_release_on_holiday.py
Labels: bot is merging ⏳

#1058 [16.0][FIX] sale_stock_available_to_promise_release_block: Unittests datetime
  sale_stock_available_to_promise_release_block/tests/test_sale_block_release.py
Labels: bot is merging ⏳

#1051 [14.0][PERF] stock_available_to_promise_release: add where condition in post-migrate
  stock_available_to_promise_release/migrations/14.0.2.5.0/post-migrate.py
Labels: ready to merge, approved, bot is merging ⏳

#1056 [16.0][FWP][FIX] stock_available_to_promise_release: Assign transfers after unrelease return
  stock_available_to_promise_release/models/stock_move.py
  stock_available_to_promise_release/tests/__init__.py
  stock_available_to_promise_release/tests/test_unrelease_cancel_fixed_pick.py
Labels: bot is merging ⏳

#1060 [16.0][FWP][ADD] shopfloor_reception_refund_return
  setup/shopfloor_reception_refund_return/odoo/addons/shopfloor_reception_refund_return
  setup/shopfloor_reception_refund_return/setup.py
  shopfloor/__manifest__.py
  shopfloor/models/stock_picking.py
  shopfloor_reception/__init__.py
  shopfloor_reception/__manifest__.py
  shopfloor_reception/migrations/16.0.1.2.0/pre-migration.py
  shopfloor_reception/models/__init__.py
  shopfloor_reception/models/stock_picking.py
  shopfloor_reception_refund_return/README.rst
  shopfloor_reception_refund_return/__init__.py
  shopfloor_reception_refund_return/__manifest__.py
  shopfloor_reception_refund_return/actions/__init__.py
  shopfloor_reception_refund_return/actions/stock.py
  shopfloor_reception_refund_return/readme/CONTRIBUTORS.rst
  shopfloor_reception_refund_return/readme/DESCRIPTION.rst
  shopfloor_reception_refund_return/static/description/index.html
  shopfloor_reception_refund_return/tests/__init__.py
  shopfloor_reception_refund_return/tests/test_action_stock.py
Labels: bot is merging ⏳

#1065 [16.0][FIX] shopfloor_reception: Fix migration stock.picking is_shopfloor_created
  shopfloor_reception/migrations/16.0.1.2.0/pre-migration.py
Labels: bot is merging ⏳
